### ISSUE TITLE
Color of 'edit assessment' icon

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#10]
Feedback from clussiana@psi.org : Can we color the pencil in yellow? It will help supervisors quickly identify active assessments. :)

 [Link to buddybuild feedback from build 4](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56d074ed04d0c60100678584&bnum=4)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d057fac8f4aa010054eac5/3189ef0a-ff59-4620-b906-8f3dfdbda89b.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>51% Unplugged</td></tr><tr><td>Memory free</td><td>365 MB / 1376 MB</td></tr></table>

**Comment by ifoche** [comment]
@cristinaelle  sure!

**Comment by rodmelia** [comment]
What happen on the yellow background? You wouldn't see the pencil, would you?
What about dark grey?

**Comment by cristinaelle** [comment]
What about an yellow pencil on a dark background? Or an yellow pencil on a rectangular background with its borders dark grey?

**Comment by rodmelia** [comment]
The plan is to get the graphic designer to do an overall review of the app.
We cannot continue asking ignacio to experiment with colors

**Comment by gtrsmith** [comment]
The edit icon actually looks alright for now even against the yellow 'overdue' ribbon. We can save this issue for a graphic design review for H15/16

**Comment by rodmelia** [comment]
Closing old issue
