### ISSUE TITLE
Assess: OU label seems to be dynamic - make it a PO Editor term 'Health Facilities'

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#100]
Feedback from gtsmith@psi.org : Change this name here to 'Health Facilities'

 [Link to buddybuild feedback from build 9](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56f2c33a64204a0100c4470d&bnum=9)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56e541525dc2880100ebb185/bf4b1857-e77b-4c0e-91a7-d40ce63418df.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>9</td></tr><tr><td>Device type</td><td>SM-T217S</td></tr><tr><td>Screen size</td><td>600</td></tr><tr><td>Screen size</td><td>600px by 1024px</td></tr><tr><td>Battery</td><td>92% Unplugged</td></tr><tr><td>Memory free</td><td>334 MB / 1347 MB</td></tr></table>

**Comment by ifoche** [comment]
@gtrsmith that comes directly from the OrgUnit level configuration in the server. I think it's better if you change it there. Does that makes sense for you?

**Comment by rodmelia** [comment]
ignancio - let's discuss tomorrow Friday March 25.

**Comment by gtrsmith** [comment]
What was the result of the discussion here? Should we still plan on this for H14?

**Comment by ifoche** [comment]
@rodmelia explained me the concern about what will happen when the OU hierarchy will change and will be more heterogeneous. I think (@rodmelia please correct me if I'm wrong) that we agreed to leave it like that for this version (so changing the OU level name in the server would produce a change in that "level 6") and address the issues of a complex hierarchy for H15. Can you confirm? (So I would move this issue's milestone to H15)

**Comment by gtrsmith** [comment]
This is fine with me if Rodolfo agrees.

**Comment by rodmelia** [comment]
Moved to H15

**Comment by rodmelia** [comment]
Closing old issue

**Comment by cristinaelle** [comment]
Reopening this because in 1.3, it is still showing 'Subnational level X'.

**Comment by rodmelia** [comment]
Below what I get using the demo mode. It looks like the top label is being generated based on server OU Level labels. We want this to become a PO editor term, initially set to 'Health Facility'

![Screen Shot 2017-12-15 at 08.53.20.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56b36ea0c587de1300b8b565/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216455f66b7191a378e70c2e52415d4ebe5d4a1f06a3a3dc78e2a436628f5a59e9d16b0c72c66e18aeb8861cbf01ba22824c86beef9850d2aa6c7bb3d4d216744b470a83ed5c3caa984ec95bf549e5495ca5153465f43b.png)

**Comment by cristinaelle** [comment]
See picture below: I have "Subnational level 2" and the full DHIS2 Program name for survey ("KE HNQIS IMCI"), while Rodolfo when he tests on the demo server has 'Organization Units' and a short name for the Program names ("HIV" / "IMCI"). Please, replace "Organization Units" with "Health Facility".
![68747470733a2f2f73332d75732d776573742d322e616d617a6f6e6177732e636f6d2f62756464796275696c642d73637265656e73686f74732f3536623430386164363563353637303130306164663464662f3561303262653561343638653939303030313633633865302f62353534313931632d61323](https://user-images.githubusercontent.com/12784825/34032273-57deb842-e186-11e7-958f-3a0fe8e5c38a.jpeg)

**Comment by cristinaelle** [comment]
Done.
