### ISSUE TITLE
buddybuild feedback from clussiana@psi.org on build #10: Improve module: All assessmenrs allows for seeing All…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#103]
Feedback from clussiana@psi.org : Improve module: All assessmenrs allows for seeing All assessments, while the other drop down menu (OUs) doesn't allow for seeinfg all OUs. H15?

 [Link to buddybuild feedback from build 10](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56fe5b36e06f1201005fc1ce&bnum=10)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56f521494f7dee0100eab3e9/34405e35-3ae2-4e34-806f-f6a7b6173934.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>10</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>95% Unplugged</td></tr><tr><td>Memory free</td><td>283 MB / 1376 MB</td></tr></table>

**Comment by ifoche** [comment]
@cristinaelle yes, this is something we made intentionally. We had a problem with the list when it shows multiple OU, so to give a quick workaround for H14 we forced that dropdown to be set on a single OU and for H15 we're now working to solved the issue and we'll be able to reintroduce the "All Org Units" option.

**Comment by cristinaelle** [comment]
Ok, thanks.

**Comment by cristinaelle** [comment]
Fixed with current filters of 1.3. Closing.
