### ISSUE TITLE
A survey with no Comp scores will just crash the app

### ISSUE THREAD

**Issue by rodmelia** [EyeSeeTea/QAApp#106]
If a survey has a question referring to a Comp Score for which the data element is missing, the survey can be completed and submitted, but then the application crashes, and it is impossible to continue working - needs to be re-installed.

**Comment by rodmelia** [comment]
If a survey has a question referring to a Comp Score for which the data element is missing, the survey can be completed and submitted, but then the application crashes, and it is impossible to continue working - needs to be re-installed.

**Comment by ifoche** [comment]
@rodmelia wouldn't this be a sanity check problem?
