### ISSUE TITLE
Facility name gets cut off

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#11]
Feedback from gtsmith@psi.org : The name of the health facility keeps getting cut off when it moves to a second line.  This happens throughout the tablet

 [Link to buddybuild feedback from build 4](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56d08d67238141010099ad51&bnum=4)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d057fac8f4aa010054eac5/bc65e6a7-dda4-4fc5-9970-049603d76df2.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>SM-T217S</td></tr><tr><td>Screen size</td><td>600</td></tr><tr><td>Screen size</td><td>600px by 1024px</td></tr><tr><td>Battery</td><td>41% Unplugged</td></tr><tr><td>Memory free</td><td>201 MB / 1347 MB</td></tr></table>

**Comment by ifoche** [comment]
@cristinaelle thanks, I agree. The solution risks not to be very straight-forward, but it's completely true.

**Comment by gtrsmith** [comment]
This is related to issue #11
