### ISSUE TITLE
Monitor module: Translations

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#112]
Feedback from clussiana@psi.org : Monitor module doesn't automatically translate in the correct language when Language settings are changed in the Tablet setting. If selected language is French, Monitor module keeps being English. 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/5734aab7ed3829010035e991/45a09ca4-9f4b-446b-a4a4-ca18df864627.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>11</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>84% Unplugged</td></tr><tr><td>Memory free</td><td>174 MB / 1376 MB</td></tr></table>

 [Link to buddybuild feedback from build 11](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=574807320d2a1b01002c7c41&bnum=11)

**Comment by gtrsmith** [comment]
Cristina is correct - there are a few terms in the monitor module that are not translated:
-- Assessment undertaken
-- Target
-- Quality of care: Last 6 months

**Comment by ifoche** [comment]
I think this is a great opportunity to use POEditor. You both are authorized to edit HNQIS translations for French. Can you try to edit there and this way we see if we're happy with this translation method?

**Comment by ifoche** [comment]
Once you are happy with the translation I can "create a commit" with the translated terms by just clicking a button

**Comment by cristinaelle** [comment]
Actually, the 3 terms you mentioned seem to have a translation in POEditor. I've included French translations for the following ones that to me are relevant to the Monitor module:

dashboard_info_future_assessments 
dashboard_title_planned_type_next_30 
dashboard_title_planned_type_future
dashboard_title_planned_type_never 
performance_title_target 
dashboard_title_planned_quality_of_care

Let me know if I have to translate others.

**Comment by ifoche** [comment]
We've improved all translations (we didn't pay too much attention to French translations as it was not being very used). Those 3 terms are in fact not translatable using POEditor because they're inside a web box (monitor charts are represented using a web library). So we're going to implement a solution for that, but it won't be immediate (it'll take a few days). In the meanwhile we'll release a bb version to test the rest of the bugfixing. 

Thanks for using POEditor and sorry for this bug.

**Comment by rodmelia** [comment]
I'm closing this issue: It is 2 years old.

The monitoring module for 1.3 has been revamped. If there are any translations issues, please open a new issue, with the associated screenshot.
