### ISSUE TITLE
ZM VMMC: Tool B - Other supplies. Change If YES

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#113]
Other Supplies: there are 2 Conditional questions in this section. For both of them, child questions should open if YES, not if NO. AnswerOptions for both questions are Yes0N01, but actually child questions open in case of YES answer. 

![screen shot 2016-06-17 at 12 40 08 pm](https://cloud.githubusercontent.com/assets/12784825/16146811/b20c5718-3488-11e6-9f31-05cdf60ec26b.jpg)

**Comment by gtrsmith** [comment]
I will address soon

**Comment by ifoche** [comment]
The last message on this issue is one year ago. If no progress is made in a week, I will close this issue and tag it as invalid
