### ISSUE TITLE
Assess module: ZM VMMC: Tool B - PrePex Devide Male Circumcision. Change If YES

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#114]
PrePex Device Male Circumision, change the wording in the header after the conditional question from If YES, to If NO. 

![screen shot 2016-06-17 at 12 43 16 pm](https://cloud.githubusercontent.com/assets/12784825/16146913/2c4f8694-3489-11e6-8799-74646ba9026e.jpg)

**Comment by gtrsmith** [comment]
I will fix soon

**Comment by ifoche** [comment]
The last message on this issue is one year ago. If no progress is made in a week, I will close this issue and tag it as invalid
