### ISSUE TITLE
ZM VMMC: Tool C - Keep crushing

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#115]
HNQIS keeps crushing when I work on Tool C. 

![screen shot 2016-06-17 at 12 46 19 pm](https://cloud.githubusercontent.com/assets/12784825/16146997/96449d6e-3489-11e6-8962-2f3ee64733c9.jpg)

**Comment by gtrsmith** [comment]
This is an old comment and i think its been addressed by fixing the metadata
