### ISSUE TITLE
Assess module: left and right arrows to move from one tab to another don't work

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#118]
Assess module: I can't move from one tab to another by clicking on the right/left arrows. Both of them don't work.

![screenshot_2016-07-19-06-19-06](https://cloud.githubusercontent.com/assets/12784825/16938774/027ba398-4d84-11e6-81f5-6ef159772fbb.png)

**Comment by gtrsmith** [comment]
Agreed - we need to fix

**Comment by ifoche** [comment]
yes. I agree with @gtrsmith. That clickable area need to be bigger.

**Comment by cristinaelle** [comment]
Fixed.
