### ISSUE TITLE
Improve: add some buffer room between rows

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#12]
Feedback from gtsmith@psi.org : Can we add some additional buffer room here? It is very difficult to select an individual assessment here accurately,  especially if you have larger fingers :)

 [Link to buddybuild feedback from build 4](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56d08dc62149f40100ed8eba&bnum=4)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d057fac8f4aa010054eac5/43a694ff-5f37-47ac-9002-acbf8c72fc85.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>SM-T217S</td></tr><tr><td>Screen size</td><td>600</td></tr><tr><td>Screen size</td><td>600px by 1024px</td></tr><tr><td>Battery</td><td>41% Unplugged</td></tr><tr><td>Memory free</td><td>193 MB / 1347 MB</td></tr></table>

**Comment by ifoche** [comment]
Thanks @gtrsmith, I agree

**Comment by gtrsmith** [comment]
Looks good - thanks
