### ISSUE TITLE
Improve module: mismatch between what being clicked and showed

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#120]
Improve module: here we have 2 surveys sent, IMCI and HIV. 
When I click on HIV, it opens the IMCI one; when I click on IMCI, it opens the HIV one.

![screenshot_2016-07-19-18-09-01](https://cloud.githubusercontent.com/assets/12784825/16957330/9d2aeae2-4de4-11e6-9cba-8a27011a4a6f.png)

**Comment by gtrsmith** [comment]
I've noticed this too. Seems to be particularly a problem with HIV. See video below

https://drive.google.com/open?id=0BwFVG9gNmqDySHFJQWZHaFJYSkE
