### ISSUE TITLE
Composite scores: functionality review

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#121]
Composite scores from HIV checklist: Top: 200% (3.6 Testing interruptions) and Bottom: 116.5% (4.4 Supplies, Reagents and Equipment).

![screenshot_2016-07-19-18-21-06](https://cloud.githubusercontent.com/assets/12784825/16957737/5210c098-4de6-11e6-99f0-731346f79f01.png)

**Comment by gtrsmith** [comment]
I will review ticket in depth to make sure scoring is functioning as expected throughout.

**Comment by ifoche** [comment]
The last message on this issue is one year ago. If no progress is made in a week, I will close this issue and tag it as invalid
