### ISSUE TITLE
Assess: CHILD question loading time

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#122]
Feedback from clussiana@psi.org : Parent questions take a very long time to get answered, either for Y or N answers. Any chance we can reduce lag time here?

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/578d303c4b18a0010061010c/0ac42607-1c55-4543-b06f-89610125d183.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>22</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>40% Charging</td></tr><tr><td>Memory free</td><td>564 MB / 1376 MB</td></tr></table>

 [Link to buddybuild feedback from build 22](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=578e6bc7b24d780100fd4283&bnum=22)

**Comment by cristinaelle** [comment]
This happens for FP checklist, too.

**Comment by gtrsmith** [comment]
I've noticed this too. It seems related to ticket #127 . 

I think this is an issue with long, complicated checklists. This example is from HIV, which has almost 600 data elements included

Over to Ignacio

**Comment by ifoche** [comment]
yes, definitively this is related to the size of the survey. When a parent question is activated we need to verify all the list of questions. We will try to make an optimisation, but this seems to be not so easy...I think that we will face the rest of the issues before this one and #127 if you're ok with that

**Comment by ifoche** [comment]
This is a big optimisation work. We've realized that we will probably need the whole next week to improve the system that queries for the parent-child relationships. This is something we're facing now but it won't be in the release we've just deployed but in the next one (in about one week).
