### ISSUE TITLE
Assess: Stalled scrolling

### ISSUE THREAD

**Issue by purdych1** [EyeSeeTea/QAApp#127]

**Comment by purdych1** [comment]
Scrolling stalls significantly in some parts of the assessment - see video for example.  The application then becomes completely unusable. https://drive.google.com/open?id=0BwFVG9gNmqDyaDZQdERsVEI1NUE

**Comment by purdych1** [comment]
When HIV checklist is removed, this issue goes away.  In addition, when the HIV checklist alone is is loaded, the app functions normally.  There is evidence that the 'heaviness' of the HIV checklist is slowing the rest of the application down critically.

**Comment by ifoche** [comment]
Just like with issue #122, this is part of a big optimisation work that we need to do next week. So it won't be solved in the release we've just deployed, but we don't forget about it, in one week this will be solved.

**Comment by adrianq** [comment]
Closing this card. Last bubbybuild release improved the scrolling performance a lot according to our tests and users feedback. Also. next release will improve the scrolling even more...
