### ISSUE TITLE
ekiambi@psi.org on build #24: Monitor module - There is a score that reflects  116.8% which is not…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#130]
Feedback from ekiambi@psi.org : There is a score that reflects  116.8% which is not accurate.

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/579e7e98a699010100a20373/0c61b49a-15f3-459e-a6ba-ac818c8be641.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>24</td></tr><tr><td>Device type</td><td>SM-P555</td></tr><tr><td>Screen size</td><td>768</td></tr><tr><td>Screen size</td><td>768px by 1024px</td></tr><tr><td>Battery</td><td>92% Unplugged</td></tr><tr><td>Memory free</td><td>978 MB / 1890 MB</td></tr></table>

 [Link to buddybuild feedback from build 24](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=57a065d2d8a58c01009fcbb1&bnum=24)

**Comment by adrianq** [comment]
It seems like some DataElements have a wrong denominator (see list of uids at the bottom of this comment). These DE have a denominator equal to 0 and numerator greater than 0. In theory denominator should always be equal or greater than numerator. 

@gtrsmith I am assignating it to you but I am not sure if this is somebody else responsability. Let me know...

![2016-08-04](https://cloud.githubusercontent.com/assets/6850223/17406961/75529f08-5a5d-11e6-8eca-65de3a4375b3.png)

List of uids:
"eFRdzJfPsX0"
"B8FI1bNDcS1"
"CmGf7Dfgcv7"
"aisdMWuG1Ap"
"VEIvlKWZuz3"
"ki886XI3xsU"
"WN95pooA1jh"
"IRHqYNjkohi"
"j62IiFLL879"
"jqz8VXM6jaT"
"L8VfBHYVlGC"
"xDGfVg1mTy2"
"fk0XwqL5ka1"
"fp0sELLfrQ2"
"x7qJjIPK9AV"
"QQsDuyo9hQX"
"vjpEJimH5jO"
"hlSIiVOAZ7k"
"jpgtT9mGOVA"
"R6Wy8Mx8ra7"
"MWbB61M6Rlr"
"Mtq7Ag0eCbw"
"GiMQkk7NHOK"
"xbe9vvqlaQw"
"IhkcP8cNirs"
"RqDopZ0piHX"
"rCi0s2rvzPv"
"HRMofSyO1Gl"
"Y3Qw8oKp1Bi"
"JnRMVFEyM4u"
"PayYRuwlgOX"
"IOAAmNjHDgh"
"XQNVzMtiRsw"
"G9WgSy3HpEq"
"x3ZaEWoheuY"
"Tjfeb3EwEqg"
"vODUhJcLXuw"
"AbvkP3lIFkl"
"ZFNQoLN9FiD"
"s98DEmMnWz8"
"HK6dSGKnefa"
"yOMecbhfgkX"
"e4uu3K0AxmJ"
"MJdQDxZU4pH"
"zCScyhDumEy"
"uPTs2HmcO4x"
"ocn9W3WEkPz"
"ozjx50UdN6c"
"HaBhEbfDrCU"
"Ml8OnVk0L8M"
"IO4p7nPQrTj"
"WPlvUTrtrbf"
"ovf5yu79kxB"
"ZS56xbEt4ez"
"Ol9NNqrKjPK"
"M5EmZvrXhkp"
"GPJ3fwyvu7l"
"sffC6PCjelb"
"q6a8M1fQ9cp"
"OFTw4lB21xf"
"wwBN51A8KMZ"
"BAP2AA08jx3"
"JwJ2s69e2Fj"
"F0UI3VNYW50"
"mFmV24e3pXP"

**Comment by cristinaelle** [comment]
we can fix this from our end, our team has identified wrong den and we'll change them. 
you can delete this thread. 
tks
