### ISSUE TITLE
ekiambi@psi.org on build #24: Critical questions "applies cryotip to the nipple. .." are…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#133]
Feedback from ekiambi@psi.org : Critical questions "applies cryotip to the nipple. .." are reflecting with an NA 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/579e7e98a699010100a20373/fbff3895-ff9c-434a-b00c-c9d4c2725c2f.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Tue Aug 09 2016 07:22:04 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>24</td></tr><tr><td>Device type</td><td>SM-P555</td></tr><tr><td>Screen size</td><td>768</td></tr><tr><td>Screen size</td><td>768px by 1024px</td></tr><tr><td>Battery</td><td>82% Unplugged</td></tr><tr><td>Memory free</td><td>990 MB / 1890 MB</td></tr></table>

 [Link to buddybuild feedback from build 24](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=57a9849c38c00a01003dbd90&bnum=24)

**Comment by adrianq** [comment]
This probably has to do with #132. Solving #132 should also removed this problem

**Comment by cristinaelle** [comment]
I think this had to do with a mismatch of columns in the gSheet we use to import content. 
Last update for this DE in the server: 
Last updated Tue Aug 09 2016 14:57:47 GMT+0300 (EAT)
Meaning we have addressed this from our ends ( I guess).

**Comment by ifoche** [comment]
Hi @cristinaelle, can we close this issue? I think it's not happening in build 28 anymore...am I right?

**Comment by cristinaelle** [comment]
yes, you are. thanks.
