### ISSUE TITLE
ekiambi@psi.org on build #28: NG HNQIS - Plan Module - Allocation of surveys

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#134]
Feedback from ekiambi@psi.org : I see 12 surveys in never been assessed but they should be under future category

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/57b49390b25d78010037b842/83039027-b4ed-4709-9641-8be2079607be.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Wed Aug 24 2016 07:43:03 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>28</td></tr><tr><td>Device type</td><td>SM-P555</td></tr><tr><td>Screen size</td><td>768</td></tr><tr><td>Screen size</td><td>768px by 1024px</td></tr><tr><td>Battery</td><td>55% Unplugged</td></tr><tr><td>Memory free</td><td>896 MB / 1890 MB</td></tr></table>

 [Link to buddybuild feedback from build 28](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=57bd5007f58d77010017bd8d&bnum=28)

**Comment by ifoche** [comment]
Hi, we've seen a similar situation when an attribute is pulled as null from the server. That can happen if there's a DE with its DEType attribute badly configured. This attribute can only have the following values:
- 92 (QUESTION)
- 93 (COMPOSITE_SCORE)
- 94 (CONTROL_DATAELEMENT)

We've experimented this in a server where the control DEs were not properly set in that attribute...could that be the problem?

**Comment by cristinaelle** [comment]
Can we assign this to @purdych1, please?
