### ISSUE TITLE
ekiambi@psi.org on build #28: The question: "close the incision with butterfly closure" is…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#135]
Feedback from ekiambi@psi.org : The question: "close the incision with butterfly closure" is missing yes or no options

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/57b49390b25d78010037b842/ba2038d6-2460-4a3b-9076-74dd12d4a000.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Wed Aug 24 2016 07:47:39 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>28</td></tr><tr><td>Device type</td><td>SM-P555</td></tr><tr><td>Screen size</td><td>768</td></tr><tr><td>Screen size</td><td>768px by 1024px</td></tr><tr><td>Battery</td><td>56% Unplugged</td></tr><tr><td>Memory free</td><td>939 MB / 1890 MB</td></tr></table>

 [Link to buddybuild feedback from build 28](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=57bd511bf58d77010017bdc8&bnum=28)

**Comment by cristinaelle** [comment]
this is content-related. we'll take care of this.
