### ISSUE TITLE
ekiambi@psi.org on build #28: NG HNQIS - Assess module - Maternal and Newborn Health - End of tab missing

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#136]
Feedback from ekiambi@psi.org : No end of tab notification for this checklist

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/57b49390b25d78010037b842/4d4b6c73-b989-47f3-bd59-cf89884bdf0d.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Wed Aug 24 2016 07:50:51 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>28</td></tr><tr><td>Device type</td><td>SM-P555</td></tr><tr><td>Screen size</td><td>768</td></tr><tr><td>Screen size</td><td>768px by 1024px</td></tr><tr><td>Battery</td><td>57% Unplugged</td></tr><tr><td>Memory free</td><td>917 MB / 1890 MB</td></tr></table>

 [Link to buddybuild feedback from build 28](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=57bd51db5370d7010050c919&bnum=28)

**Comment by ifoche** [comment]
I understand this as a content-related problem, the DE "End of tab" is probably not associated to that ProgramStageSection

**Comment by cristinaelle** [comment]
Can we assign this to @purdych1 ?
