### ISSUE TITLE
url to show up automatically

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#140]
critical. too many typos when supervisors log in to HNQIS. is it possible to make the url in the logging in page showing up automatically, please? https://www.psi-mis.org unless it's Nigeria.

**Comment by rodmelia** [comment]
How do we know is nigeria?
We can certainly make it default to https://www.psi-mis.org

**Comment by cristinaelle** [comment]
What if we include a text box above the log-in box saying something like:
"If you're logging in from Nigeria, url: https://hnqis.psi-mis.org
If you're logging in from other countries, url: https://psi-mis.org"

It doesn't even save the url automatically when people log out; I think it'd b nice to offer them the correct url address to type on the log-in page.
