### ISSUE TITLE
clussiana@psi.org on build #33: Error message when landing on the Improve module after…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#143]
Feedback from clussiana@psi.org : Error message when landing on the Improve module after marking a survey as complete. "One more conflicts encountered please check import summary."

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/57e54bc1a2eef90100b90bfc/67c4ef56-2033-4cfd-ad94-e26aa2152c9a.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Fri Sep 30 2016 10:55:06 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>33</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>29% Charging</td></tr><tr><td>Memory free</td><td>225 MB / 1376 MB</td></tr></table>

 [Link to buddybuild feedback from build 33](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=57ee448aa05a5201001da89b&bnum=33)

![img_20160930_134701 2 copy](https://cloud.githubusercontent.com/assets/12784825/18989775/68f071be-8716-11e6-9797-def8cb1f2221.jpg)

**Comment by ifoche** [comment]
Taking care of it...

**Comment by ifoche** [comment]
@cristinaelle  problem comes from DEs MUeZYkrEAJQ and aKtPt6qSf59. I don't have permission access and configure this program nor DEs. Can anyone take a look to these DEs?

**Comment by cristinaelle** [comment]
Kindly note that we get this message with all the checklists of KE HNQIS, too, with the staging.hnqis.psi-mis server.

**Comment by ifoche** [comment]
sorry @cristinaelle, but or that server is down or it doesn't exist. Is there any typo staging.hnqis.psi-mis.org ? However, could you send me an email too with the credentials for that server (once clarified which exactly it is)?

**Comment by cristinaelle** [comment]
sorry, ignacio, there was a typ: https://hnqis-staging.psi-mis.org.

**Comment by ifoche** [comment]
After Chris modifications in the access groups, is the problem still there? if that's the case, can you send me (by email) credentials to test it?

**Comment by ifoche** [comment]
Just for the record, this problem was related to a couple of DEs that didn't have the access groups properly set. I'm moving it to testing. Please @cristinaelle take it back to in progress if I'm missing something.
