### ISSUE TITLE
clussiana@psi.org on build #37: It gets stuck when doing something on this Reschedule…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#146]
Feedback from clussiana@psi.org : It gets stuck when doing something on this Reschedule feature.

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/57f12ef8cd5ee1010096a18b/1b06505e-c6a5-4f35-9066-ddcd603c0bf9.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Mon Oct 03 2016 09:59:29 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>37</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>63% Unplugged</td></tr><tr><td>Memory free</td><td>261 MB / 1376 MB</td></tr></table>

 [Link to buddybuild feedback from build 37](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=57f22c01938eb1010049288f&bnum=37)

**Comment by ifoche** [comment]
sorry @cristinaelle, this feature you reported bugs for (#144, #145 and #146) shouldn't be included in this release. This is something that was incorporated and properly working on H14.4 (videos release). Thanks for reporting it, we'll remove it asap and regenerate a new release. Sorry for it

**Comment by cristinaelle** [comment]
It works on 1.3.
