### ISSUE TITLE
rmelia@knowming.com on build #41: What's this empty line?

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#148]
Feedback from rmelia@knowming.com : What's this empty line?

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/57f5f4f060a4140100bbdb2e/21238290-f28a-439c-8fd4-46369c44264d.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Tue Nov 15 2016 11:55:07 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>41</td></tr><tr><td>Device type</td><td>ZTE Blade A460</td></tr><tr><td>Screen size</td><td>480</td></tr><tr><td>Screen size</td><td>480px by 854px</td></tr><tr><td>Battery</td><td>38% Unplugged</td></tr><tr><td>Memory free</td><td>220 MB / 900 MB</td></tr></table>

 [Link to buddybuild feedback from build 41](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=582af79b38d84c0100275e13&bnum=41)

**Comment by rodmelia** [comment]
old version - closing outdated card
