### ISSUE TITLE
rmelia@knowming.com on build #41: The white space is even bigger here

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#149]
Feedback from rmelia@knowming.com : The white space is even bigger here

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/57f5f4f060a4140100bbdb2e/2a983de5-4a20-46d2-aeec-7519966559e5.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Tue Nov 15 2016 12:05:26 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>41</td></tr><tr><td>Device type</td><td>ZTE Blade A460</td></tr><tr><td>Screen size</td><td>480</td></tr><tr><td>Screen size</td><td>480px by 854px</td></tr><tr><td>Battery</td><td>35% Unplugged</td></tr><tr><td>Memory free</td><td>225 MB / 900 MB</td></tr></table>

 [Link to buddybuild feedback from build 41](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=582afa0638d84c0100275e45&bnum=41)

**Comment by rodmelia** [comment]
Old card - closing
