### ISSUE TITLE
buddybuild feedback from gtsmith@psi.org on build #4: This feedback mechanism is fantastic!  Wow!

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#15]
Feedback from gtsmith@psi.org : This feedback mechanism is fantastic!  Wow!

 [Link to buddybuild feedback from build 4](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56d08f4b04d0c601006786a5&bnum=4)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d057fac8f4aa010054eac5/4fceeb7d-01e9-44eb-8c6e-0d7fe1dcfd48.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>SM-T217S</td></tr><tr><td>Screen size</td><td>600</td></tr><tr><td>Screen size</td><td>600px by 1024px</td></tr><tr><td>Battery</td><td>40% Unplugged</td></tr><tr><td>Memory free</td><td>195 MB / 1347 MB</td></tr></table>

**Comment by gtrsmith** [comment]
Nothing to actually address here :) Just pointing out how cool this new tool is for providing feedback. Feel free to delete once read
