### ISSUE TITLE
build #42: Possible to submit survey with non-answered compulsory questions

### ISSUE THREAD

**Issue by davidhuser** [EyeSeeTea/QAApp#151]
Hi
I discovered today that it's possible to send a survey although not all compulsory questions have been answered with yes or no.
Screenshare: https://i.imgur.com/C60lOh4.gif

**Comment by purdych1** [comment]
Hi Ignacio - could you investigate this with high priority?  See above for David's screenshare of this issue.

Thanks,
Chris

**Comment by purdych1** [comment]
Following up on this issue again - Ignacio, have you had a chance to look into this yet?

Thanks a lot,
Chris

**Comment by ifoche** [comment]
Sorry @davidhuser & @purdych1, I didn't see this issue. I'm so sorry...I don't know how did it happened. Please @davidhuser, can you provide me by email the server & credentials to replicate the problem? It must be a corner case we missed to check. Thanks, and apologizes again.

**Comment by ifoche** [comment]
@davidhuser effectively I chased the bug. You're using 1.1.x version, right? (the videos one). Do you want me to generate a new version with the bug fixed or do we wait to incorporate this with the upgrade to 2.25 in the next months?

**Comment by davidhuser** [comment]
Hi
Thank you! Yes it was 1.1.3 version. I hope @purdych1 knows the answer regarding the second question.

**Comment by purdych1** [comment]
Hi David and Ignacio - if i am understanding this correctly, this is only an issue for those that have access to buddybuild and have downloaded the HNQIS videos buddybuild, right? If that is the case, since we haven't rolled the videos features out to countries as part of a release yet, I think we are okay to wait to process this fix along with the 2.25 upgrade version.  Looping in Cristina in case she has other thoughts.

**Comment by cristinaelle** [comment]
Chris is right: we have extensively tested the app that is in users' hands with checklists configured for Uganda, Guate, Angola, etc, and so far we have not seen this issue. So I guess this is related to an old or bb version.

**Comment by ifoche** [comment]
@purdych1, @cristinaelle @davidhuser. That's fine. The fix is already in our code, we'll incorporate it to next version as per Chris & Cristina comments. Thanks
