### ISSUE TITLE
Slowness/Hanging in App

### ISSUE THREAD

**Issue by purdych1** [EyeSeeTea/QAApp#152]
When a significant amount of content is loaded in the app, (ex. 1000-2000 questions), the app starts to slow down in terms of responsiveness and moving between screens.

**Comment by purdych1** [comment]
Screenshare: https://drive.google.com/open?id=0B7ZwFN0mH_L-WGI0bTBoMTRpQzQ

**Comment by purdych1** [comment]
I know we worked on a performance boost for the app last fall, but perhaps it is time for another given that this large checklists aren't going away any time soon.  Looping in Cristina to see how/if we should prioritize this for H2.0.0 (H15).

**Comment by cristinaelle** [comment]
It's all about users, right? Would be nice to improve app speed when loading 10^3 questions, please.

**Comment by ifoche** [comment]
We will solve this issue by introducing a progress bar (animated circle) when back button is clicked, until the questions ratio calculations (answered vs mandatory) is finished

**Comment by rodmelia** [comment]
and thanks for the excellent video !

**Comment by rodmelia** [comment]
This was solved many versions ago by the introduction of an animated progress ball
