### ISSUE TITLE
ekiambi@psi.org on build #54: Yes and no are reversed here. Yes should be on the right and…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#153]
Feedback from ekiambi@psi.org : Yes and no are reversed here. Yes should be on the right and no on the left.    

![screenshot](https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/58b4c59062a7d801008b471f/ea973dbe-f7e0-4c71-a646-118621ab39ee.jpg)

| Item | Value |
| --- | --- |
| Created | Fri Mar 10 2017 12:00:05 GMT+0000 (UTC) |
| App uptime | undefined |
| Build | 54 |
| Device type | SM-T531 |
| Device name | undefined |
| Screen size | 800 |
| Screen size | 800px by 1280px |
| Battery | 40% Unplugged |
| Memory free | 392 MB / 1369 MB |
| Network IP | undefined |

 [Link to buddybuild feedback from build 54](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=58c2954575c6000100063f4e&bnum=54)

**Comment by cristinaelle** [comment]
Confusing to have “No” box on the left and “Yes” box on the right + Inconsistent alignment of Yes/No answers. In cases of inverted Yes/No the “Yes” box is appearing on left and the “No” box on the right.

**Comment by ifoche** [comment]
Just a question. Do the Yes-No questions point to the same optionSet than the No-Yes ones? Could you email me the result of the API call for those 2 (or one) optionSets?

**Comment by purdych1** [comment]
Hi Ignacio,

The questions use different option sets.  Interestingly, the inverted option set is the one showing the answers in the correct order ('Yes' first), while the standard option set now has inverted answers.  See below for the questions, their option sets, and associated API calls.

Question: Within the past 3 months… (correct order, 'Yes' first)
Option set: HNQIS - InvYesNo 

API call:

<optionSet xmlns="http://dhis2.org/schema/dxf/2.0" created="2016-02-29T22:32:03.935+0000" lastUpdated="2016-06-12T16:10:44.981+0000" name="HNQIS - Yes1No0" href="https://www.psi-mis.org/api/optionSets/v6QYyj8ihWn" id="v6QYyj8ihWn">
<displayName>HNQIS - Yes1No0</displayName>
<publicAccess>rw------</publicAccess>
<version>1</version>
<externalAccess>false</externalAccess>
<valueType>INTEGER</valueType>
<access>
<read>true</read>
<update>true</update>
<externalize>false</externalize>
<delete>true</delete>
<write>true</write>
<manage>true</manage>
</access>
<user id="eme9LfVIBlm"/>
<userGroupAccesses/>
<attributeValues/>
<options>
<option id="WuIjp1ZkvuQ"/>
<option id="mWUrJ69gb1b"/>
</options>
</optionSet>

Question: The testing interruption lasted 3-13 days (wrong order, 'No' first)
Option Set: HNQIS - Yes1No0

API call:

<optionSet xmlns="http://dhis2.org/schema/dxf/2.0" created="2016-02-29T22:33:10.313+0000" lastUpdated="2016-06-12T16:10:44.824+0000" name="HNQIS - InvYesNo" href="https://www.psi-mis.org/api/optionSets/Lei8l6rWtPD" id="Lei8l6rWtPD">
<displayName>HNQIS - InvYesNo</displayName>
<publicAccess>rw------</publicAccess>
<version>1</version>
<externalAccess>false</externalAccess>
<valueType>INTEGER</valueType>
<access>
<read>true</read>
<update>true</update>
<externalize>false</externalize>
<delete>true</delete>
<write>true</write>
<manage>true</manage>
</access>
<user id="eme9LfVIBlm"/>
<userGroupAccesses/>
<attributeValues/>
<options>
<option id="ZSav2FtzhC2"/>
<option id="uzKdL0uVU1G"/>
</options>
</optionSet>

**Comment by purdych1** [comment]
Pasting a link to my response here, as it gets cut off in Waffle: https://docs.google.com/a/psi.org/document/d/1TgT7PBqS61yrJMoH4x0jIXFTkNcpZ_K8HxfaPPeMorg/edit?usp=sharing

**Comment by ifoche** [comment]
Thank you very much @purdych1 I will study the case asap. I'm a bit confused about one thing, that maybe you can clarify. This report was opened using Build 54, that is intented to be used with 2.25 servers, like staging.psi-mis.org, but I see www.psi-mis.org traces in your API call. I guess the optionSet didn't changed between those servers and even the UID was preserved, but could you please confirm me which server are you using and which user in that server if it's different from what Rodolfo sent on the release notes?

**Comment by purdych1** [comment]
Hi @ifoche - my mistake! I believe that @cristinaelle tested this using the staging server, but the API query I used was erroneously in www.psi-mis.org.  In any case, as you noted, the UIDs of the option sets are the same.  I have updated the gDoc with the API calls from staging here: https://docs.google.com/a/psi.org/document/d/1TgT7PBqS61yrJMoH4x0jIXFTkNcpZ_K8HxfaPPeMorg/edit?usp=sharing

**Comment by cristinaelle** [comment]
Confirmed, we used the staging server.

**Comment by rodmelia** [comment]
Reviewed with Ignancio - he will check the Options sort order, and make sure that the app preserves it.

**Comment by rodmelia** [comment]
Old issue - all options are now listing based on the options set order.
