### ISSUE TITLE
ekiambi@psi.org on build #54: "Runs the test" question  is functioning as a parent but it…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#154]
Feedback from ekiambi@psi.org : "Runs the test" question  is functioning as a parent but it isn't a parent question. 'Prepares  the testing kit' child pops up  2 questions above the parent. But this not a child question.  Also, The bottom 2 questions are color coded  as parent questions. 

![screenshot](https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/58b4c59062a7d801008b471f/60b839ac-4016-403b-ba93-c93401dabf69.jpg)

| Item | Value |
| --- | --- |
| Created | Fri Mar 10 2017 12:09:13 GMT+0000 (UTC) |
| App uptime | undefined |
| Build | 54 |
| Device type | SM-T531 |
| Device name | undefined |
| Screen size | 800 |
| Screen size | 800px by 1280px |
| Battery | 40% Unplugged |
| Memory free | 381 MB / 1369 MB |
| Network IP | undefined |

 [Link to buddybuild feedback from build 54](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=58c29769624e7301002bc99c&bnum=54)

**Comment by ifoche** [comment]
Sometimes it's a parent question but children question received a question order so big that is not just below it's parent where the children question appears but somewhere else. Can you please verify the children question is not elsewhere in the survey?

**Comment by lindasato** [comment]
I have explained the error in more details here:

KE HNQIS HIV: HIV Testing Services (HTS) tab

Header: Pre-test counseling
1. KE HNQIS HIV.1HT-140-Seeks clarification and obtains verbal or written consent (if the client decides to test)
This is functioning as a parent question, but no hidden logic or hidden logic code is assigned to this question
2. KE HNQIS HIV.1HT-130-Explains result interpretation, explains confirmatory test and ensures patient understands
This is functioning as a child question to the question above (KE HNQIS HIV.1HT-140). This question does not have the hidden logic or hidden logic code assigned to it. It pops up when then answer to the parent question is "No"
3. KE HNQIS HIV.1HT-180-Is safer conception/pregnancy counseling routinely offered onsite to PLHIV who wish to have children?
This question is functioning as a grandchild. It pops open when KE HNQIS HIV.1HT-130 is answered. Interesting thing is that it pops up to both "Yes" and "No" answer. This question does not have the hidden logic or hidden logic code assigned to it.

Header: Testing Process
1. KE HNQIS HIV.1HT-220-Runs the test (and confirmatory test if positive) based on protocols
This is functioning as a parent question, but no hidden logic or hidden logic code is assigned to this question
2. KE HNQIS HIV.1HT-200-Prepares the testing kit
This is functioning as a child question to the question above (KE HNQIS HIV.1HT-220). This question does not have the hidden logic or hidden logic code assigned to it. It pops up when then answer to the parent question is  a "Yes"

**Comment by ifoche** [comment]
Ok, I think this is very specific, thank you @lindasato. I'll check it the latest next Monday, and give you a concrete answer about each case. Thank you for the detailed report. Just to confirm, can you please send me in a separate email the credentials you're using for testing so I can generate the exact situation?

**Comment by ifoche** [comment]
Hi again, please let me analyze the problem one by one in different comments. 
- KE HNQIS HIV.1HT-140. I think this is related to the new new way of creating parent-child relations between questions, that may not be very clear yet. In fact, that question do have a child question associated, and it is the question [KE HNQIS HIV.1HT-130](https://staging.psi-mis.org/api/dataElements/GGEyzqWlozc), and concretely, when pressing the option [No](https://staging.psi-mis.org/api/options/mWUrJ69gb1b). The program is configured in a very strange way because the child question has a lower question order than its parent, so it appears above, but everything seems to be working as configured. Remember that with the new logic, to configure a parent-child relation, you don't need to touch the parent question dataelement anymore. You configure everything in its children question. So you only have to tell to all children which parent question shows him, and concretely which parent option inside that parent question. And you do that using the "38 Question Parents" and "39 Question Parent Options" attributes. if you enter that DE (the children one), you'll see that those DEs are configured as follows:

   38 Question Parents: W2rQWW3E7jZ
   39 Question Parent Options: mWUrJ69gb1b

   If you check it, you'll see those UIDs correspond to "KE HNQIS HIV.1HT-140" DE (its parent question) and "No" option (the option inside that parents that deploy the child question). 

- KE HNQIS HIV.1HT-130. For the same reason I just explained, this is configured as a child question of the above, but using the new system, and not the old one. 

- KE HNQIS HIV.1HT-180. This is the same as before. The question is configured to do that. If you check the question, its attributes are like follows:
38 Question Parents: GGEyzqWlozc
39 Question Parent Options: mWUrJ69gb1b,WuIjp1ZkvuQ

   That means if we answer any of the options listed in "39 Question Parent Options" to the question listed in "38 Question Parents", then this question is deployed. 

So I think the app has the expected behavior. If your question is "does that make sense to have that distribution of parent-child questions?", of course the answer may be no...I think that configuration is only there to demonstrate the new parent-child logic, and can be changed by you at any moment if you think those questions cannot have those relations between them. 

I will stop here and wait for your answer because I have the impression that the lasting 2 problems have the same nature, right? So can we consider this issue as solved?

BTW, thanks for doing such a detailed revision and reporting bugs. I really appreciate it

**Comment by ifoche** [comment]
closing the issue as it is a content issue (server side), not an App issue
