### ISSUE TITLE
clussiana@psi.org | '0 files synced' message

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#159]
This is immediately after the log-in was complete. The app froze and gave me this error “0 files synced”. It then automatically started the log-in process again. It completely reloaded taking the same amount of time (7 minutes) and everything was fine.

![picture1](https://cloud.githubusercontent.com/assets/12784825/23862873/3a2cc1d6-081f-11e7-8897-82a0381cb8f7.png)

**Comment by ifoche** [comment]
0 files synced is only notifying you that no media file was downloaded for the last check cycle. It's probably too much information for the user. I think we may need to show that message only when some media file is downloaded and not always...to avoid the confusion.  So I would say your report doesn't have to do with that message but with a blocking behavior followed by a pull you didn't ordered, right? Just for clarification, you were not using a virtual device right?

**Comment by cristinaelle** [comment]
I think this is too much info for the user, correct. According to where we are taking the multimedia library/download, it might be better to move this into a thread related to the multimedia library and we'll add it as a 5th module to HNQIS, as suggested by @rodmelia some time ago.

**Comment by ifoche** [comment]
Ok, just a little annotation. I guess HNQIS graphical design relies on each module colors, not only for the tabs, but also for the logo. Maybe you are planning to change the logo and introduce this new concept with a new symbol for the tab? If so, I would suggest to provide a new logo artwork so I can get the color of the new module from there and keep homogeneity among the app in terms of graphic design. 

Can we leave this issue for changing the message of the number of synced files to only when a file's synced and open a new one for adding a new module and maybe, change the logo? Does that make sense?

**Comment by cristinaelle** [comment]
I don't think we will change the HNQIS logo any time soon. The Multimedia module could be optional from the Setting menu? It pops up in case users want? I leave with you and RM the best way to include get users access to Multimedia files in the app, according to what makes most sense from a user experience perspective.

**Comment by cristinaelle** [comment]
I am closing this ticket because we won't go ahead with a multimedia library at the moment.
