### ISSUE TITLE
Planing: Can the first color in a accordion section have white background

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#16]
Feedback from gtsmith@psi.org : Can the first color in a drop down like this after a header always be white?  You can se how the color use here looks a bit poor

 [Link to buddybuild feedback from build 4](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56d09e48238141010099ae37&bnum=4)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d057fac8f4aa010054eac5/009b4514-3238-44e8-a329-c7d571b2799a.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>SM-T217S</td></tr><tr><td>Screen size</td><td>600</td></tr><tr><td>Screen size</td><td>600px by 1024px</td></tr><tr><td>Battery</td><td>36% Unplugged</td></tr><tr><td>Memory free</td><td>271 MB / 1347 MB</td></tr></table>

**Comment by ifoche** [comment]
@gtrsmith sure!

**Comment by gtrsmith** [comment]
resolved
