### ISSUE TITLE
clussiana@psi.org | Assess module Hanging

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#160]
Sometimes when you tap on the assess icon (+ sign), the page hangs for about 5 seconds looking like the image to the left before changing to the image on the right.

![picture 2](https://cloud.githubusercontent.com/assets/12784825/23862970/81423272-081f-11e7-8bc6-ef63e49dd09c.jpg)

**Comment by ifoche** [comment]
The app there is calculating the different OUs assigned to the user and populating the menus. Maybe you're asking for a circle progress bar to give a "loading sensation" to the user?
