### ISSUE TITLE
clussiana@psi.org | Text box content

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#161]
"When marking a survey as complete, the message says ‘You’ll find it now in the Improve tab’  It should say Improve Module."

![picture3](https://cloud.githubusercontent.com/assets/12784825/23863055/c2d1fa42-081f-11e7-8fc5-abdb3ce527e2.png)

**Comment by ifoche** [comment]
I would turn this report into another different thing. I think we need a deeper work cleaning up all the unused strings from POEditor to clearly show what string do they refer to, so it become easier for you to change it in POEditor or report any string that may have escaped to POEditor and we need to create. Does that make sense for you?

**Comment by cristinaelle** [comment]
Yep, it does.
