### ISSUE TITLE
clussiana@psi.org | Download medialist

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#163]
We saw the list in the settings menu but we don’t know where these files are within the app.  We tried tapping the file to open it but it didn’t work. Where are we supposed to access these files?

**Comment by ifoche** [comment]
Yes, the feature we were asked for only included showing the list of media files that existed in the system, not playing them, to at least now what is there. Maybe we can put this feature in H1.2 work estimation for @rodmelia right?

**Comment by cristinaelle** [comment]
Right,
