### ISSUE TITLE
clussiana@psi.org | Plan module - Reschedule

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#164]
If you tap on _TestKE it brings you to a RESCHEDULE Tab. Was this intended?

**Comment by ifoche** [comment]
Yes, in principle the feature we were asked for had that entry point. It's not it's impossible to do it in a different way, it's just what it was designed. Maybe it's not very clear and that feature need to be re-designed again? Do you have any suggestion? Would you need us to propose a different interaction for accessing the re-schedule feature?

**Comment by ifoche** [comment]
closing it as this feature is behaving as expected
