### ISSUE TITLE
ekiambi@psi.org on build #54: Feedback script for the first question under 1.1 has some…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#165]
Feedback from ekiambi@psi.org : Feedback script for the first question under 1.1 has some code appearing  _x000D_

![screenshot](https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/58b4c59062a7d801008b471f/8e1dd26f-c4db-47b7-9550-8adc01fe5600.jpg)

| Item | Value |
| --- | --- |
| Created | Mon Mar 27 2017 11:42:23 GMT+0000 (UTC) |
| App uptime | undefined |
| Build | 54 |
| Device type | HTC One 801e |
| Device name | undefined |
| Screen size | 1080 |
| Screen size | 1080px by 1920px |
| Battery | 48% Unplugged |
| Memory free | 639 MB / 1819 MB |
| Network IP | undefined |

 [Link to buddybuild feedback from build 54](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=58d8fa9f792f2a0001bce947&bnum=54)

**Comment by rodmelia** [comment]
@cristinaelle @purdych1 - Hi Chris/ Cristina - could you please send the URL for this DE?
TO make troubleshooting easier, we will add in a very discrete way UIDs and server URL in developer mode, which will be automatically activated in BB releases - so we not longer have to fish for DE.

**Comment by davidhuser** [comment]
@rodmelia - this was imported as a normal string because of a conversion from Excel .xls to gSheet. I will fix this.
