### ISSUE TITLE
dhuser on build #55: Clicking questions in Feedback does not make DE feedback pop up

### ISSUE THREAD

**Issue by davidhuser** [EyeSeeTea/QAApp#171]
Screenshare: https://i.imgur.com/IQ7L3ec.gif
Tested on build #54 (it works there)
Server is singapore-dev.psi-mis.org, User: MMdemo1

**Comment by davidhuser** [comment]
Server is singapore-dev.psi-mis.org, User: MMdemo1

**Comment by purdych1** [comment]
Thanks for raising this issue David.  @ifoche  - thanks in advance for looking into this, this is a priority issue for us to address in time for Myanmar's testing of the app on Monday next week.
