### ISSUE TITLE
lsato@psi.org on build #55: All questions appearing duplicated.

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#173]
Feedback from lsato@psi.org : All questions appearing duplicated. 

![screenshot](https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/58ef53787153020001597337/5da2bc75-b3de-4e18-90de-d3e67a1e01bf.jpg)

| Item | Value |
| --- | --- |
| Created | Wed Apr 26 2017 14:02:14 GMT+0000 (UTC) |
| App uptime | undefined |
| Build | 55 |
| Device type | HTC One 801e |
| Device name | undefined |
| Screen size | 1080 |
| Screen size | 1080px by 1920px |
| Battery | 16% Unplugged |
| Memory free | 399 MB / 1819 MB |
| Network IP | undefined |

 [Link to buddybuild feedback from build 55](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=5900a8667db89e0001c902b7&bnum=55)

**Comment by lindasato** [comment]
I have resubmitted this since I was not seeing it on the list of issues. @ifoche, if this is appearing elsewhere please let me know so that I can close it to avoid duplication.

**Comment by ifoche** [comment]
@lindasato, can you attach a screenshot to this issue but with developers options activated so we can see the dataElements UIDs? Thanks in advance

**Comment by lindasato** [comment]
@ifoche, let me clarify that the duplication is across ALL checklists and ALL health areas, not just one section. The duplication is occurring for questions only, headers are not affected. In addition, I have just discovered that when "Show developer options' is activated, the questions are not duplicated, but when the developer's option is turned off, the questions are duplicated. I have attached 3 examples-from different health areas showing both the developer's option view and "normal" view. (I have paired the screenshots as 1a/1b, 2a/2b, 3a/3b to show the "normal view" and the samescreenshot but with developer's option activated.
![1a-fp normal view](https://cloud.githubusercontent.com/assets/26415203/25472341/99e75622-2b33-11e7-9b73-7cf222bfe692.png)
![1b-fp developer s view](https://cloud.githubusercontent.com/assets/26415203/25472369/aeefdeae-2b33-11e7-9906-d5d0a5365fa2.png)
![2a-cc normal view](https://cloud.githubusercontent.com/assets/26415203/25472374/b5be639a-2b33-11e7-8225-93dffbe74c51.png)
![2b-cc developer s view](https://cloud.githubusercontent.com/assets/26415203/25472377/b8232f30-2b33-11e7-9a95-50c9e54c13d7.png)
![3a-htn normal view](https://cloud.githubusercontent.com/assets/26415203/25472380/ba0efd10-2b33-11e7-9441-3e738a54ec2b.png)
![3b-htn developer s view](https://cloud.githubusercontent.com/assets/26415203/25472385/bbd93bb0-2b33-11e7-8374-b3d1bd04b94b.png)
