### ISSUE TITLE
HIV: Missing questions. All first answer options in questions with multiple choices are missing.

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#174]
Feedback from lsato@psi.org : HIV: Missing questions. All first answer options in questions with multiple choices are missing.

![screenshot](https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/58ef53787153020001597337/5f80ca67-283f-40f1-9ead-60bed49d21e8.jpg)

| Item | Value |
| --- | --- |
| Created | Fri Apr 28 2017 08:28:25 GMT+0000 (UTC) |
| App uptime | undefined |
| Build | 55 |
| Device type | SM-T555 |
| Device name | undefined |
| Screen size | 768 |
| Screen size | 768px by 1024px |
| Battery | 19% Charging |
| Memory free | 749 MB / 1891 MB |
| Network IP | undefined |

 [Link to buddybuild feedback from build 55](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=5902fd29e661e90001ddcf3e&bnum=55)

**Comment by lindasato** [comment]
@ifoche, I had reported this error on 19th April by shaking the tablet and sending feedback. But just like the error for duplicated questions, I realised it is not captured on the list of issues -probably I lost internet connection when sending. Apologies-going forward, after sending feedback directly from the tablet, I will be confirming that it is displaying here. 
A detailed description: In the HIV assessments, some questions have multiple answer choices. In build #55, the first answer options are missing for ALL such questions in the HIV assessments. Please see examples of screenshots below-both for "normal view" and developer's view (I have just put 2 examples).
![1a_20170428](https://cloud.githubusercontent.com/assets/26415203/25521747/7c367370-2c09-11e7-95c3-0cce830f7cc4.png)
![1b_20170428](https://cloud.githubusercontent.com/assets/26415203/25521748/7f4610fc-2c09-11e7-8dfd-10bdd3ed151c.png)
![2a_20170428](https://cloud.githubusercontent.com/assets/26415203/25521756/8669baf0-2c09-11e7-9762-281239fbe660.png)
![2b_20170428](https://cloud.githubusercontent.com/assets/26415203/25521765/8d4613e6-2c09-11e7-8fb7-09d5e2df2f0f.png)

**Comment by ifoche** [comment]
Hi @lindasato, we've realised what's happening there. When we introduced the link to open the DE directly by clicking on the UID link, what we did was to encapsulate the whole question and interpret its text as HTML. That's very good because you could potentially use every symbol and logic you use in HTML, but then if you use the < symbol, as it's reserved for HTML code to declare tags, the question simply cannot be interpreted. If you go to the [example you were showing](https://staging.psi-mis.org/api/dataElements/UsJch9GRVuc) you'll see that's the case. So, for now, we're going to interpret HTML only for the UID link, and that will make the trick (make questions reappear), but we will think about how to deal with it in the future so we could potentially have all the power of HTML in the questions (format text in a different way, include images when you have connexion, other links to external webs, etc etc etc).
