### ISSUE TITLE
Missing "ALL ASSESSMENTS bar with drop down list to select assessments in monitor module

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#175]
Feedback from lsato@psi.org : Missing "ALL ASSESSMENTS bar with drop down list to select assessments in monitor module

![screenshot](https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/59039347070a090001bdc666/ebed1584-9a56-4f3a-87ee-5c126d31e88e.jpg)

| Item | Value |
| --- | --- |
| Created | Mon May 01 2017 08:40:32 GMT+0000 (UTC) |
| App uptime | undefined |
| Build | 56 |
| Device type | SM-T555 |
| Device name | undefined |
| Screen size | 768 |
| Screen size | 768px by 1024px |
| Battery | 39% Unplugged |
| Memory free | 485 MB / 1891 MB |
| Network IP | undefined |

 [Link to buddybuild feedback from build 56](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=5906f48024fc3b00018de9e4&bnum=56)

**Comment by lindasato** [comment]
Hi @ifoche , this was noted this Mali's app. Server: https://data.psi-mis.org.  Please see attached a screenshot of the Assessments bar missing in Mali's Monitor module
![all assessments bar](https://cloud.githubusercontent.com/assets/26415203/25575984/54ff670a-2e64-11e7-8b70-4c685e7e95f8.png)

**Comment by ifoche** [comment]
@lindasato can you send me in separate email credentials to test it? Thanks!

**Comment by cristinaelle** [comment]
@ifoche: all access credentials are in this file - HNQIS log-in contacts tab. 

https://docs.google.com/spreadsheets/d/18Z_bJVLVb-Rwll6S8jGe_eGodYnYsOp_ErUH8cZa8Mc/edit#gid=1276503948

**Comment by ifoche** [comment]
thanks!

**Comment by ifoche** [comment]
Finally, this problem came from the fact that Mali program contained quote chars in its name, and that was creating problems with the way we passed the program names to the filter. we've escaped those characters and now seems to work. We're releasing a new version with the fix
