### ISSUE TITLE
Push user Control DE sending UID instead of username

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#176]

**Comment by ifoche** [comment]
![event reports](https://cloud.githubusercontent.com/assets/10931645/26690284/f657f160-46f8-11e7-9b25-d93da5b179e6.png)

**Comment by cristinaelle** [comment]
@davidhuser : can we close this? Robi is still seeing a mix of user IDs and usernames. has this been fixed?

**Comment by davidhuser** [comment]
@cristinaelle it is fixed but not deployed to google play - I don't interfere with Ignacio's Waffle cards, but IMO it can be closed

**Comment by cristinaelle** [comment]
@ifoche: pliz, confirm this is included in 1.2.4 (I assume so - I wanted to check in DHIS2 from all assessments sent today, but I can't see any event in DHIS2).

**Comment by cristinaelle** [comment]
Checked in DHIS2 and everything works fine.
