### ISSUE TITLE
Wrong credentials but everything seems ok

### ISSUE THREAD

**Issue by davidhuser** [EyeSeeTea/QAApp#177]
so, this user...

- can *not log into* the new HNQIS app, username / password seems wrong
- he *can* log in into DHIS2 web version
- he *can* log in with HNQIS app on his phone
- I can log in with HNQIS on my tablet (with his exact account)
- has already *reinstalled* the HNQIS app
- Has entered the password in another app to see if it's not the keyboard that plays games
- DHIS2 logs say that the username/password seems wrong
- Uses mobile Internet

His tablet:
Device name: REH-16799
Model number: SM-T531
Android version: 5.0.2
HNQIS app from Play Store (not SFH)

I ruled out every user fault, it's very odd. Would you know what that is?

**Comment by ifoche** [comment]
Hi @davidhuser. The user has a Google Account configured in the tablet, right?

**Comment by davidhuser** [comment]
@ifoche must be, he needs this to download HNQIS from Play Store

**Comment by ifoche** [comment]
Sorry @davidhuser for the long wait. Sure, if he is not an alpha tester using buddybuild, he certainly needs to have a Google Account to use it. Can I have that user credentials by email? I didn't experiment myself any similar issue. Thanks in advance

**Comment by davidhuser** [comment]
@ifoche I sent you the credentials and asked him not to change his pw for the time being

**Comment by ifoche** [comment]
@davidhuser that user's working for me. Maybe the user is introducing a space after the username? (See the screenshot below)

![user_not_logging.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54e12dad64acc92700d55240/125516c66e82c728ace21e0d46fd879f31bd8da69bd6b34ca35af99a2e046b313b05ad2f7f88ea32ba50395b4d5d48a6405c5642f5f98f23a0b738708f4e17ff912f002e936e55beb2901ab953be208d1c83b6ef834ec0ec3e25e78b8d463d1d0d4b9bb2.png)

**Comment by davidhuser** [comment]
Hi @ifoche - that's the thing, it also worked for me, using his password. He was also able to log in on his phone and on the web, just not on his tablet. It is a weird thing. I will ask him to reset his tablet...

**Comment by ifoche** [comment]
@davidhuser if you're asking the user please ask him to delete any extra space after the username before resetting the tablet. Sometimes the suggestions from the keyboard, when you have already introduced a few times the same word propose that word, but when you accept the keyboard suggestion (at least on samsung keyboards) it adds a space after the word. So maybe he's not realizing about that space...
