### ISSUE TITLE
Improve module - Fix wrong drop-down menu that pops up on blue arrow (filter OU)

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#178]
There are 2 different menus for the filter OU in the Improve module: 

1) When clicking on the blue arrow of the drop-down menu for selecting OUs, it pops up a menu composed of 'All Org Units' and all other facilities, but then when selecting one facility from this menu, the app doesn't change the facility selected in the Improve module. 

2) When clicking on the black line listing the OUs (click on the actual name of the facility), all facilities pop up, then you can select any facility and the app correctly retrieves the one selected in the Improve module. 

![screen shot 2017-06-07 at 12 29 50 pm](https://user-images.githubusercontent.com/12784825/26875530-0c30ab9e-4b8b-11e7-8c0d-a938c5d997b2.jpg)

**Comment by ifoche** [comment]
Confirmed. Thank you @cristinaelle. I'll wait for you to move it to ready in order to start with the solution
