### ISSUE TITLE
Improve module - Long press on a survey line take to the Assess module

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#179]
In the Improve module, in case the user does a long press on a survey line (instead of just clicking on it to open the respective Improve module), the app takes the user to the Assess module of that survey with all the questions answered. It is not possible to modify the answers (and that's good), however, in case another survey for that health area for that OU is open/active in the Assess module, it overwrites it. In the Assess module the user now sees what has already been submitted, not what he was working on.

**Comment by ifoche** [comment]
Hi @cristinaelle. This is a shortcut to open the survey in the assess module in read-only mode. The assess module is designed to only show one survey at a time. The previous survey is not being overwritten, it's just closed, but still there with the answers the user introduced. To access that survey you only need to exit the survey you ask the improve module to show and open the other survey again. Is that the behavior you're reporting?

**Comment by cristinaelle** [comment]
Yes, this is the behavior I am reporting. I was not aware of this behavior and we have never taught it. Let me check with Janet and Linda to see whether this is what we want or not because the Myanmar team reported this as a bug :) @

**Comment by cristinaelle** [comment]
Ok - let's remove this behavior because i) we'll be offering the possibility to access past submitted Assess modules from Monitor, ii) compulsory questions will be visible in the Monitor module. So, there is no need for this, thanks.
