### ISSUE TITLE
buddybuild feedback from gtsmith@psi.org on build #4: The app won't let me shake in the right screen.  Was trying…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#18]
Feedback from gtsmith@psi.org : The app won't let me shake in the right screen.  Was trying to add a comment in the date selection section of this page but am unable to click 'ok' and save the comment.  I tried to capture the screen but when i shake my tablet it goes back to landing page. Let me know if this does not make sense

 [Link to buddybuild feedback from build 4](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56d0a2b8c98d430100d8a6a7&bnum=4)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d057fac8f4aa010054eac5/41d69d76-fbd4-4be3-a673-e6c1911e63b6.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>SM-T217S</td></tr><tr><td>Screen size</td><td>600</td></tr><tr><td>Screen size</td><td>600px by 1024px</td></tr><tr><td>Battery</td><td>33% Unplugged</td></tr><tr><td>Memory free</td><td>273 MB / 1347 MB</td></tr></table>

**Comment by ifoche** [comment]
@gtrsmith Unfortunately it is something we cannot control. I think you found a bug in the buddybuild sdk (when there is a dialog over a screen, it doesn't takes the screenshot of the dialog. However, if I can suggest you a workaround, it can be manually done by taking a screenshot with the tablet/phone, sending it to your computer and then attaching the image to a manually added task in waffle. To attach it, you just have to press in the top-left number (the issue number) of the issue once opened it, and it will take you to the github issue. In the github interface, just throwing the image in a comment will imply uploading it and attaching it.

Of course, it is much more difficult than just using the buddybuild interface, but if you think the screenshot is not easy to explain with words, I suggest you that

**Comment by ifoche** [comment]
As I suppose you will open a new issue with the bug report you was trying to report here, I close it

**Comment by gtrsmith** [comment]
ok - i just submitted another ticket with an updated screenshot. no worries
