### ISSUE TITLE
Plan module - Lorem ipsum, etc.., showing

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#180]
Can't take a screenshot from where I am. Please:
- Plan module, select a survey from the Never assessed tab, 
- Click on Reschedule,
- There is nothing the user can do because instead of the date it shows 'Lorem ipsum, etc...'

**Comment by ifoche** [comment]
You're completely right. Do you want us to proceed with a solution?

**Comment by ifoche** [comment]
If so, please just move the issue to ready

**Comment by rodmelia** [comment]
Ignacio - please check if 1.3.1 still shows this error.
Testers: please check if the release 1.3.1 still shows this problem. If it does, please send BB screenshot.

**Comment by cristinaelle** [comment]
assigned to Linda to test on 1.3

**Comment by cristinaelle** [comment]
Done.
