### ISSUE TITLE
Untranslated strings

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#182]
There are 2 strings that are not translated because they exist in POEditor but we're not using the translated strings but hardcoded ones. These are:
https://poeditor.com/projects/po_edit?order=&filter=&id=46637&id_language=50&search=dialog_info_ask
https://poeditor.com/projects/po_edit?order=&filter=&id=46637&id_language=50&search=survey_info_exit

These other 2 strings ("Reschedule" and "Due date") are directly hardcoded in xml files and don't have an alternative in POEditor (assessment_planning_header.xml)

**Comment by ifoche** [comment]
@purdych1 please just le me know by moving this issue to ready if you want me to proceed and solve this issue

**Comment by rodmelia** [comment]
Moving to ready for Ignacio to check. If the strings are missing, Ignacio please add. If the strings are already in, Ignacio, please move back to testing, with a note.
