### ISSUE TITLE
Video questions are not part of feedback module

### ISSUE THREAD

**Issue by davidhuser** [EyeSeeTea/QAApp#183]
If a question is configured with DE attribute "Video URL" (containing real gDrive video IDs) they are skipped in Feedback module.

https://i.imgur.com/c0GJzLo.png

After 6th question and before the header "2 Copper IUD ..." there should be another question feedback with a video.

Videos are downloaded as shown in ... > Downloaded media.

example data element:
https://staging.psi-mis.org/api/dataElements/PAB7DfDc4r7

User "ignacio_hnqis" should have access to the server.

Version: 1.2.3

**Comment by ifoche** [comment]
Hi @davidhuser I'm sorry but I cannot remember ignacio_hnqis password on that server and my user ifoche is not allowed to change ignacio_hnqis password. Could you please email me credentials to test the issue? Thank you in advance

**Comment by ifoche** [comment]
Hi @davidhuser I didn't find the problem yet, but just in case this helps I'm getting a "Found an unsupported tag body" error recursively. In my opinion, there are problems parsing feedback on description field. Looking a little bit to the description field it looks like you introduced the video ID in the description field and not only in the Video attribute. Can you try removing the description from those DE's?

**Comment by davidhuser** [comment]
@ifoche I removed all descriptions again from this program. I remember from our earlier discussion on the first round of testing that the video did not show up if the DE description was empty, so I tried to put something there as well

**Comment by davidhuser** [comment]
In case you want to add something to the description, you can edit DEs now on that server

**Comment by ifoche** [comment]
@davidhuser I've tried to edit with ifoche and ifoche_hnqis without success. However, I think I've got the reason why it's not appearing. The DE doesn't belong to any Composite Score. The feedback list is CS-oriented, so it first take all the CS and then retrieve all the DEs that belong to each CS in order to build the list. I'm not 100% sure that will solve the issue but I think at least it cannot show. Can you try and let me know?

**Comment by davidhuser** [comment]
Thanks, they show up!
