### ISSUE TITLE
New Scoring Classification to reflect in the app

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#185]
Modify the classification of QoC score by Class A, B and C to reflect new Scoring System as follows:
- Class A - green: >= 90%
- Class B - yellow: 80% >= and <= 89%
- Class C - red: <80%

This affects scheduling for Plan module, scores in the Monitor module and Improve module.

**Comment by ifoche** [comment]
sorry @cristinaelle I didn't include this on the new release. Is this something you want us to do? Looks like something to include on a new release rather than a bugfixing issue, right?

**Comment by rodmelia** [comment]
Cristina - this will also be needed for the sticky data elements.

**Comment by cristinaelle** [comment]
Yes, 3 arms here: Linda to change all scores (because new classes go together new scoring system), Ignacio to reflect new classes in the app, David to reflect changes in Fixed DEs, Indicators and Program Indicators. 

Do you want me to report this in 1.3 instead of here?

**Comment by cristinaelle** [comment]
Closing because it's a duplication of #210 .
