### ISSUE TITLE
Upgrade <-> Pull from DHIS2 to HNQIS

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#186]
Something to keep in mind for when we upgrade HNQIS versions (like the one Ignacio has just released on BB): make sure we also have a pull of data from DHIS2 to HNQIS on QoC scores from past assessments in the last 6 months in Monitor + dates of assessments in Plan. 

The last time we upgraded the app (for 2.25), the moment users logged into HNQIS, both the Plan and the Monitor module were blank (because no data was pulled from DHIS2 to HNQIS?).

**Comment by ifoche** [comment]
@cristinaelle I guess we could solve this by introducing a message when no data is available. Would that work?

**Comment by cristinaelle** [comment]
not sure I am getting your question: what I am trying to say is that when users upgrade to a new version of HNQIS, it'd be nice to automatically download on the new version historical data, too (data entered so far), otherwise every time they upgrade to a new version, HNQIS is blank - no historical data.

**Comment by ifoche** [comment]
oh! I get your point now. But I think upgrading shouldn't touch historical data. For last version it did because we were forced to upgrade due to the sdk upgrade. But next times in principle it shouldn't be necessary and the historical data should be there without problem.

**Comment by cristinaelle** [comment]
Linda saying this is not an issue anymore. Closing this.
