### ISSUE TITLE
Mismatch between Overall QA score calculated by the app and _Overall score

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#189]
Not sure this is DHIS2 or Android -related.

I have noted a mismatch between KE HNQIS CC.0CS-100-Overall QA Score and _Overall Score. We have picked up 14 events where 'Overall QA Score' is NA (reported as 0 in Event Reports), while the _Overall Score reports another number. Those assessments are not blank assessments because there are scores from other sections, meaning supervisors have conducted assessments. Why is this happening. And not sure what the Plan module takes into account in this case: 0 or the actual score that we cannot see? 

[events (1).xlsx](https://github.com/EyeSeeTea/QAApp/files/1179499/events.1.xlsx)

**Comment by cristinaelle** [comment]
I want to report that this is happening for the Program TZ HNQIS WEA, too. In this case, _Overall Score is correct, while the Overall 100 QA Score is 0 for all assessments that have been conducted in Tanzania  in 2016 and 2017. 
Can you fix this, please? Thanks. 

[events (2).xlsx](https://github.com/EyeSeeTea/QAApp/files/1197239/events.2.xlsx)

**Comment by cristinaelle** [comment]
When HNQIS calculates the date of next visit, it also feed Fixed DE Status and it stores a value from 1 to 4 where 1 is Never Assess, 2 is Overdue, 3 is This month and 4 is Future.
According to the screenshot attached, it is not clear what it is going on because Fixed Status is blank for many surveys. Please, note that for some of those surveys, we have a mismatch between Overall 100 QA Score and _Overall Score: Overall 100 QA Score is 0 and _Overall Score is correctly retrieved.

Any help on this?

@davidhuser : we might need you to run the script you mentioned to double check (and fix) where Overall 100 QA score =! _Overall Score. 

![screen shot 2017-08-04 at 1 02 30 pm](https://user-images.githubusercontent.com/12784825/28964530-cc774d56-7915-11e7-8959-5addc2f7498e.jpg)

**Comment by ifoche** [comment]
@cristinaelle could you please provide a DB from a user with that problem? Thanks!

**Comment by ifoche** [comment]
@cristinaelle it would also help a lot to track the problem having a user with a test OU assigned so we can test against it. Our main suspect is the root CS configuration of the server, but we would like to verify before ensuring that.

**Comment by cristinaelle** [comment]
@ifoche it's difficult to get a DB for this because this is happening in many countries (Kenya, Tanzania and Cambodia) with multiple users. regarding the user, I have created demoifoche Temp1234 on data.psi-mis.org and he has the KH HNQIS - FP user role active and a test OU that have KH HNQIS CC active. Please, select a survey from KH HNQIS CC to test this and let me know if you need anything else from our side. 

Also waiting for David to come back from his holiday and run the script he recently mentioned. I think it's useful to find out more of these mismatches that could help you fixing this. 

thanks!!

**Comment by ifoche** [comment]
Thanks @cristinaelle! I think that's enough for us to try to replicate it. I'll come back with whatever we will find out.

**Comment by ifoche** [comment]
@cristinaelle we've checked it and it looks like those events for whom the scores don't match are generated using old versions of the app before we introduced a fix for the CS. In principle that shouldn't happen with any recent event. And in our case we've been unable to reproduce it with the user that you provided and the last version. Concretely for those events generated with 1.0.5 and older, that mismatch problem is present, but in more recent versions it is not.

**Comment by cristinaelle** [comment]
ok - got it.

**Comment by ifoche** [comment]
Hi @cristinaelle I can't see the mismatch in your screenshot. The status DE is not something that we're sending with the app but probably something that is calculated server side using a script that we're not aware. When I was saying that the mismatch was corrected on those versions I was meaning the mismatch that existed with the _Overall Score control DE and the root CS. Could you develop a little bit more on the problem? I think I didn't understand the whole problem and probably answering to a different question.

Thanks!

**Comment by rodmelia** [comment]
@cristinaelle - The problem that you are reporting is on a Fixed Score - so this is responsibility of the HQNIS Script that runs overnight, and NOT Android - so we need to start an email about this with him

**Comment by cristinaelle** [comment]
Closing this because it has been fixed server-side.
