### ISSUE TITLE
Multiple nested Parent/Child logic with same option

### ISSUE THREAD

**Issue by davidhuser** [EyeSeeTea/QAApp#190]
I have a question regarding the use of Parent Options. Given the following setup where the sub-question pop up if `Yes` is ticked:

```
Question1
|__ Question2
	|__ Question3
```

_**Metadata setup:**_

**Question 1**
UID: `Question1`
Options: Yes UID = `Option1`, No UID = `Option2`

**Question 2**
UID: `Question2`
Options: Yes UID = `Option1`, No UID = `Option2` (the same options)
Question Parents DE attribute: `Question1`
Question Parent Options DE attribute: `Option1`

**Question 3**
UID: `Question3`
Options: Yes UID = `Option1`, No UID = `Option2` (the same options)
Question Parents DE attribute: `Question1,Question2`
Question Parent Options DE attribute: `Option1;Option1` <--

How do I set it up so that every time `Option1` is ticked, the sub-questions appear when there are two-level questions with the same Option (`Option1`, or in the app `Yes`)? I tried both `Option1;Option1` and `Option1` with no success. Also the Question3 is not hidden from the beginning. Thanks for any hints.

**Comment by ifoche** [comment]
Hi @davidhuser I'm not sure if I'm understanding the scenario you want to build, but if you one Question 3 to appear only when question 2 is answered yes, then you don't need to mention Question 1 in Question 3 configuration. Just point to Question 2 and Option1. I mean, you don't need to describe all your ancestors in each question configuration, but just your immediate parents. Does that help?

**Comment by davidhuser** [comment]
Yes it does! Overthought it. Thank you!
