### ISSUE TITLE
Survey can be pushed more than one time

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#191]
This was reported by @cristinaelle in [this comment](https://github.com/EyeSeeTea/QAApp/issues/187#issuecomment-316055650)

**Comment by ifoche** [comment]
@cristinaelle this is no longer possible in last version (not yet deployed) because we removed the long click action...so as a collateral effect this problem just disappeared

**Comment by cristinaelle** [comment]
Ok, thanks!
When do you think we are posting the new version (bb#59)?

**Comment by ifoche** [comment]
I think it depends only on the time that #189 will take. I hope not too much, but I will let you know as soon as we analyze the scores problem. We can also generate a new bb now, but I guess it makes more sense to wait for that fix too, right?

**Comment by cristinaelle** [comment]
correct, let's wait to fix #189 first. tks!
