### ISSUE TITLE
Missing Pass/Fail label for unscored questions in Improve Module

### ISSUE THREAD

**Issue by lindasato** [EyeSeeTea/QAApp#192]
Hi @ifoche,
We just noticed that in the Improve module, only scored questions are flagged with either "PASS/FAIL". We have checked several country apps and realised that it occurs in any, as long as a question is not scored. It wasn't obvious earlier since we were using a different scoring system where most questions were scored. We are now scoring critical questions only in most of the checklists but feedback needs to be given for all failed questions, whether critical or not. Initially we thought it was because the score column was blank for non-scored questions, but fixing 0 scores did not  make a difference. I have attached a screenshot of an example.
![example-missing pass_fail](https://user-images.githubusercontent.com/26415203/29216703-33ef378a-7eb8-11e7-8fd0-72ad7f4d0dfd.png)
Linda

**Comment by purdych1** [comment]
@lindasato the one complication I can see for non-scored questions is Videos - for these questions, we wouldn't want to force a pass/fail message because it wouldn't make sense for those.  It actually looks nice in the app now, because since they are non-scored, the pass/fail does not appear.  However, I understand this is important for other types of questions.  We'll see what @ifoche says!

**Comment by lindasato** [comment]
@ifoche , we tried to work around this by adding a very small score to the non-scored questions (0.000001 for each question). So, by adding this small score, the QoC is calculated correctly (the small score is insignificant) and the Pass/Fail appear for both critical and non-critical questions in the improve module. However, when a section does not have a critical question, then the small score becomes significant and is factored in the calculation of the section score. So with this method, the QoC is correct, but the section score for a section without critical questions will be "incorrect" in the sense that it should actually be zero. This means we may still need a solution that enables Pass/Fail to appear in Improve Module without us having to add the small score to the non-critical questions.
