### ISSUE TITLE
1.2.8 Two assessments for same health area displaying in Plan Module

### ISSUE THREAD

**Issue by lindasato** [EyeSeeTea/QAApp#193]
Hi @ifoche 
Two different assessments for MW HNQIS Maternal and Newborn Health are displaying in Plan module. Initially the assessments in plan module were 16 (which is the correct number), but after I did a second assessment for MNH, it appeared as an additional health area in Plan module, making it a total of 17. Both events arrived at the server. I did similar assessments on a different device but I was not able to replicate the error. See screen shot below of the plan module. I have exported the database to nacho@eyeseetea.com
![mw mnh in plan](https://user-images.githubusercontent.com/26415203/29351046-aabe76dc-8269-11e7-997c-8183b0706a78.png)

**Comment by lindasato** [comment]
@ifoche , I would like to revisit this. The duplication is still happening in Plan Module. It seems to occur with MW HNQIS only. Today it Duplicated Hypertension once I completed the assessment. And it increases the number of assessments. I had a total of 16, health areas, after it duplicated then the total is 17

**Comment by cristinaelle** [comment]
@ifoche and @purdych1 : please, prioritize this bug because this should be fixed before MW starts using the 1.2.8 officially otherwise they will end up with multiple assessments. This is unique to the MW app. Not sure if the bug is app- or server- side. 

thanks.

**Comment by cristinaelle** [comment]
@lindasato : can you share the db for this one, please?

**Comment by lindasato** [comment]
@ifoche I am not able to replicate this issue and I am now wondering whether it was related to the server and not the app itself. (it was also specific to Malawi's app only).

**Comment by cristinaelle** [comment]
Done.

**Comment by lindasato** [comment]
Hi Ignacio,
This has now happened again, different test account and different server-please see screen shot below. I have exported the DB to you
![issues 193 on 1 3 5](https://user-images.githubusercontent.com/26415203/44327634-d9f37d00-a467-11e8-9796-637e192bc522.jpg)

**Comment by cristinaelle** [comment]
Linda reported this is happening for 1.3.5, too. Database below. 

[compressedData.zip](https://github.com/EyeSeeTea/QAApp/files/2301636/compressedData.zip)

**Comment by ifoche** [comment]
Thank you! I'll let you know as soon as we have an assessment

**Comment by ifoche** [comment]
@cristinaelle Effectively we can see in the DB the survey duplication in planning, but we cannot replicate that duplication. Do you have any extra information about how the duplication was created? What was the user doing when this happened? Any further information will be very helpful. Thanks!

**Comment by lindasato** [comment]
@ifoche , unfortunately I have never been able to replicate this issue. I completed the assessment, checked out the feedback module, then I simply looked in Plan module to check if the date of next visit was calculated correctly and that's when I noticed the duplication. Sorry I don't have more information on this.

**Comment by ifoche** [comment]
ok, we will try to replicate it, but if you by chance find a consistent way, please, just let me know. Thanks!

**Comment by ifoche** [comment]
unable to replicate
