### ISSUE TITLE
Feedback is not showing assessments

### ISSUE THREAD

**Issue by davidhuser** [EyeSeeTea/QAApp#194]
We have a user who has issues with displaying conducted assessments in the feedback module.

It seems that something is wrong with Mozambique's Improve module. As shown in the video, feedback is not showing in the Improve module, even with 'All Assessments' selected as the health area. 
Plan, Assess and Monitor work correctly.  The user (Adelaide Mahanjane) can see assessments submitted from the scores he has in the module Monitor, but can’t get to the assessments submitted in the Improve module and see the feedback. 

The local system adminstrator has already uninstalled all previous versions of HNQIS from tablets and simulators and installed a fresh one and still, this weird behavior is still there. This happens on both users Adelaide and Felizarda. When he stripped users of all OUs but one, the Improve module was working. When he includes more OUs (as it should be), the Improve module doesn’t work. 

I could not reproduce it in any platform/app version pair so I have attached his DB below.

Let me know if you need a replicated user account. 

Thank you

- User [video]( https://wetransfer.com/downloads/118d3e207dc71aa08e61bc11cde609d420170818121815/87c0de56f5b005369fa076661977001d20170818121815/b2dc23)
- User [video screenshot - should show 1 assessment result](https://i.imgur.com/vCnk5YI.png)
- User [database](https://drive.google.com/a/baosystems.com/file/d/0B3FU6Lx45t71a2ZFTjdwckt0elk/view?usp=sharing)
- User tablet: Galaxy Tab A, Android 6.0.1
- Server: data.psi-mis.org
- User HNQIS version: 1.2.3

**Comment by ifoche** [comment]
Hi @davidhuser. We've taken a look to the user both using the DB you provided and logging in by ourselves and we're not yet able to replicate the problem. Looks like a corner case that may depend on the memory of the devices and many other concrete situations. We'll give it another try by creating a virtual device and trying to approximate as much as possible to that device but we may not be able to replicate although all our efforts...I will keep you posted anyway.

**Comment by ifoche** [comment]
BTW, the video expired. I think we got the point from the image, but just for you to know that we were not able to see the video

**Comment by cristinaelle** [comment]
video reloaded - it's [here](https://we.tl/aAug1o6wvt).

cristina

**Comment by ifoche** [comment]
thanks @cristinaelle !!! we're still unable to replicate the problem, but having the video helps a lot to understand the issue

**Comment by ifoche** [comment]
Definitively, we're not able to replicate it and doesn't seem that more time is going to change that. @cristinaelle @purdych1 . What do you suggest? do we continue trying to find it or do you want us to proceed and release? (and later if we get any clue of how to replicate it we dedicate more time in the next version)

**Comment by cristinaelle** [comment]
I'd go for releasing as it is.
thanks for looking into this! it might be an isolated case. in case something else similar pops up, it might be worth investing more time.

**Comment by davidhuser** [comment]
The user who reported it said 

> Now it's working perfectly. Thank you

after installing 1.2.6. Closing the issue, thanks all!

**Comment by cristinaelle** [comment]
Just to let you know that 1.2.6 has fixed this (reported by Emidio from Moz).
