### ISSUE TITLE
Crash during event pull

### ISSUE THREAD

**Issue by davidhuser** [EyeSeeTea/QAApp#195]
There is a user whose metadata pull crashes every time he assigns a set of orgunits. DHIS2 config seems ok so far:

- No DHIS2 errors reported when inspecting the network calls done by the app
- User is assigned to these orgunits 
- Program is assigned to these orgunits
- User role has program and is assigned to User

- User: `KHMALQAT-TBK_dhuser` PW: sent seperately
- Server: data.psi-mis.org
- Troubling orgUnits:

```

[-] TAPAO RUBBER PLANTATION CO,L TD (00-90-40)
               Hout Meng Hong (00-90-40-1) <--
               Phab Sophat (00-90-40-3) <--
               Sann Seam (00-90-40-2) <--

UDnVtw42V7V
mmWHwfMmJCe
xqRHD4yIieX
```

Can you help me to identify why it crashes?
Also, if you have a documentation so that I could build the app in Android studio, that'd be great.

Thanks very much,
David

**Comment by ifoche** [comment]
@davidhuser this we have detected that it's a bug in the sdk. There was an event state not supported by the sdk and used in one of the events, so we just added that event and looks like working now. We'll release a new version later today or tomorrow to fix it. Thanks for reporting it.

Re documentation for developers, we've never been asked to create it, so we don't have it, but in principle, the project is open and you can clone the repository and move to development branch without any problem.

**Comment by purdych1** [comment]
@davidhuser is this resolved so we can close this?

**Comment by davidhuser** [comment]
I think so @purdych1 - the original user reported it is working fine. Closing
