### ISSUE TITLE
1.2.7 Change Show only last feedback

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#198]
Change from Show only last feedback per Program/OU to Show only last feedback. It stays on one row and it is less DHIS2 language.

![screen shot 2017-10-04 at 6 47 20 pm](https://user-images.githubusercontent.com/12784825/31185467-b6ed1dc2-a934-11e7-9bd5-47331ce59f3b.jpg)

**Comment by ifoche** [comment]
Thanks @cristinaelle. This translation issue can be quickly solved by changing the translation in POEditor (concretely in [this URL](https://poeditor.com/projects/po_edit?order=&filter=&id=46637&id_language=43&search=feedback_show_only_one) you'll find the specific key for that string)

**Comment by cristinaelle** [comment]
I don't have access to HNQIS project in POEditor.

**Comment by ifoche** [comment]
oh, that's true. I've just added you
