### ISSUE TITLE
Planning module: Lighten color for alternate rows in cascading view

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#20]
Feedback from gtsmith@psi.org : Please lighten this color as well

 [Link to buddybuild feedback from build 4](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56d0a5a2b9cf69010045b539&bnum=4)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d057fac8f4aa010054eac5/2579d916-4dd8-4914-999e-aa617912c24e.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>SM-T217S</td></tr><tr><td>Screen size</td><td>600</td></tr><tr><td>Screen size</td><td>600px by 1024px</td></tr><tr><td>Battery</td><td>31% Unplugged</td></tr><tr><td>Memory free</td><td>232 MB / 1347 MB</td></tr></table>

**Comment by ifoche** [comment]
@gtrsmith ok

**Comment by gtrsmith** [comment]
resolved
