### ISSUE TITLE
1.2.7 html takes me back to the Plan module

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#200]
When I click on html, it takes me back to the Plan module. FYI I am on Genymotion: does this have to do with emulators? Linda to confirm it works fine on actual Android devices.

**Comment by lindasato** [comment]
No, it doesn't work well. On one device it is leading back to Plan module, on another device, it leads to settings.

**Comment by ifoche** [comment]
oh, that's weird...@cristinaell, @lindasato, Did you create a new survey and tried to share the feedback for a recent survey? or did you create an obs&act plan for an old feedback? (just trying to guess where could it come from...as we have not replicated that issue yet)

**Comment by cristinaelle** [comment]
I created a new survey from scratch and when I click on the html button, it always takes me back to the Plan module.

**Comment by lindasato** [comment]
I also created a new survey and it always leads me to plan module. For Janet, whether it is an old or new assessment, it always leads her to Settings.

**Comment by ifoche** [comment]
Still not able to replicate it...but given that we don't have too much time ahead before full 1.3 version is out, I'm not sure if it makes more sense to treat this directly with the 1.3 version if you still have the same problem. Does it sound reasonable?

**Comment by cristinaelle** [comment]
It does, yes. Let's go ahead and in case there are other users with the same issue, we'll dig into this.
