### ISSUE TITLE
1.2.7 Full assessment link error

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#201]
When I click on the link provided in the message, this is what I get:

![screen shot 2017-10-04 at 6 59 30 pm](https://user-images.githubusercontent.com/12784825/31186054-4747957c-a936-11e7-9f3e-ef9df3f929d7.jpg)

(Again - on Genymotion)

**Comment by lindasato** [comment]
I get the same as above on Android.

**Comment by ifoche** [comment]
Yes...That URL was going to be implemented by somebody else as far as I know. @rodmelia, maybe you can provide more details on that?

**Comment by purdych1** [comment]
@rodmelia following up on this - do you have any updates?

**Comment by rodmelia** [comment]
Hi Chris - the associated web pages don't exist yet.
What's the full URL that the app is currently referring?
Ignacio: What's the logic (if any) to build the URL ?

**Comment by rodmelia** [comment]
@ifoche - we discussed with Chris P and decided that we will hive the link - we will reactivate this feature for v1.3 - at that time the web page will be ready.

**Comment by ifoche** [comment]
Hi @rodmelia. Ok. The logic under the link is as simple as this one by now:
```
if (survey.isSent()) {
            data += "https://apps.psi-mis.org/hnqis/feedback?event=" + survey.getEventUid() + "\n";
        } else {
            data += getString(R.string.url_not_available) + "\n";
        }
```

So if survey is sent, just put that URL changing the event UID, otherwise a string saying that URL is not available.

**Comment by cristinaelle** [comment]
Ok  - so, we'll be having HNQIS 1.7 with no feedback and action plan left to providers after conducting an assessment, correct? 
In case this is the way we are taking for 1.7, then I suggest removing the possibility to share the action plan at the bottom of the action plan. Doesn't make sense to share an invalid url or or a message that says that the URL is not available. Let's hold on the sharing feature until it's fully functional.

**Comment by purdych1** [comment]
@cristinaelle Rodolfo and I discussed simply hiding the URL - that way you can still transmit the score, next assessment date, obs and action plan to the provider in 1.2.7 (they just wouldn't be able to click the link to see the full survey results).  Then we can re-incorporate the URL when it is working correctly in 1.3.  What do you think?

**Comment by cristinaelle** [comment]
Hi Chris - I think it makes a lot of sense when providers share the Action Plan via email, WApp or others. When it comes to text, it seems that the only thing that is shared is the URL link, so in that case, we either incorporate other details like score, next ass date and obs in the text or we remove the possibility to share the URL link, only.

**Comment by rodmelia** [comment]
Conclusion: we hide the link for 1.2.7, we re-incorporate it  from 1.3
Work on the web page is scheduled to Start on Nov 10 - we should have something up&running by the end of November.
https://apps.psi-mis.org/hnqis/feedback?event=EventUid

**Comment by rodmelia** [comment]
Updated specs are in #206 - closing this one (URL details in this card are incorrect)
