### ISSUE TITLE
1.2.8 HNQIS crashes when users share the Action Plan as html (Formatted text)

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#205]
We are instructing users to not use the Formatted text as of now. Is there any possibility to remove the Formatted text button? In any case, this wouldn't work because we are waiting for the url where to send host Action Plan to be up and running. I suggest removing that option until it's fully functional.

**Comment by ifoche** [comment]
@cristinaelle I cannot replicate that crash.  You're using 1.2.8 version, right? The formatted text option is not showing the link now, but it embeds the HNQIS logo and looks a bit better...of course we can remove it but it would be interesting to be able to replicate that crash. Can you confirm that you consistently get a crash when you click on formatted text option, the version that you have installed and which version did you have installed when you installed that one on top? Thanks!

**Comment by cristinaelle** [comment]
I confirm this happens from the version that is on gPlay, 1.2.8. There is no HNQIS logo - there is a text saying ‘formatted text’ and when I click on it, the app crashes (‘Unfortunately, HNQIS has stepped working’). I had the 1.2.6 version before. I guess this is the one all users have - the one that was previously on gPlay, if I am not wrong.

**Comment by ifoche** [comment]
@cristinaelle I've installed 1.2.6, logged in, updated to 1.2.8 and created an action plan, sent it and shared it as formatted text without problems. Maybe you can export me your DB just to see if we can get some extra information from there?

**Comment by cristinaelle** [comment]
@ifoche : attached! I have logged in with KEdemo1 Kenyademo1 and shared an Action Plan as formatted text and it has crashed again.
thanks and let me know if this helps. 

[compressedData.zip](https://github.com/EyeSeeTea/QAApp/files/1486646/compressedData.zip)

**Comment by rodmelia** [comment]
1. Disable rich HTML
2. Investigate how to properly implement Rich Text for the future
