### ISSUE TITLE
1.2.8 Action Plan: date of the assessment and critical steps missing. Minor reformatting

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#206]
Please, include the date of when the assessment has been conducted into the Action Plan when this is shared. It's already in the Action Plan in the Improve module in the app.

**Comment by ifoche** [comment]
@cristinaelle you're completely right. Paradoxically we've introduced the assessment date on formatted text but somehow we forgot to do it in plain text option. So just in between while we include it, I would suggest you using formatted text option (if you confirm that #205 is not affecting 1.2.8 version)

**Comment by lindasato** [comment]
Hi @ifoche , The Date of next assessment is now displaying in the Action Plan and in the summary shared. However, these dates are not being correctly calculated based on QoC and productivity. They also do not match the dates in Plan Module which are appearing correctly.

**Comment by rodmelia** [comment]
Feedback below is only for plain text - we have not been able to get rich text working



Revise text for Plain Text

Subject: 
Results supervision on Test facility 2/ Family Planning on 24/12/2017

Body:
HNQIS - Results supervision on  Test facility 2/ Family Planning
DATE OF ASSESSMENT: 24/12/2017
QUALITY OF CARE (QoC) SCORE: 77 % (no decimals)
NEXT ASSESSMENT: 24/2/2018

GAPS:
<display the text>

ACTION PLAN:
<display the text>


ACTION: drop-down value 1, dropdown value2

See full assessment at https:/...

**Comment by ifoche** [comment]
Just for the record, the modications are:
1) No subject
2) Changes in the format just by lowcase uppercase the different words
3) Include the critical step missed
4) Change in the URL by adding Id to event and also including the server from preferences

**Comment by rodmelia** [comment]
Option 1: Long text - what we have
Option 2: Short Text
HNQIS - Results supervision on Test facility 2/ Family Planning on 24/12/2017

See full assessment at https:/...

**Comment by ifoche** [comment]
example of URL here:
https://apps.psi-mis.org/hnqis/feedback?eventId=QpYVIUm5EHo&server=https://clone.psi-mis.org

**Comment by cristinaelle** [comment]
Thanks, Ignacio. I think that RM and I mean to modify the content of the 'Simple text', too, based on what RM has shared in his comment.
