### ISSUE TITLE
Planing:  lighten color for the alternate rows

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#21]
Feedback from gtsmith@psi.org : Please lighten this colt as well

 [Link to buddybuild feedback from build 4](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56d0a5c8963673010084e464&bnum=4)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d057fac8f4aa010054eac5/5df88145-9e0b-4838-8985-f91e1298b329.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>SM-T217S</td></tr><tr><td>Screen size</td><td>600</td></tr><tr><td>Screen size</td><td>600px by 1024px</td></tr><tr><td>Battery</td><td>31% Unplugged</td></tr><tr><td>Memory free</td><td>236 MB / 1347 MB</td></tr></table>

**Comment by ifoche** [comment]
ok!

**Comment by gtrsmith** [comment]
resolved
