### ISSUE TITLE
Plan: 'All Assessments' font size

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#22]
Feedback from gtsmith@psi.org : Can we make this font larger by breaking into two lines?  It should also be 'all assessments' with an s at the end

 [Link to buddybuild feedback from build 4](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56d0a63c6e11a00100ae4f25&bnum=4)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d057fac8f4aa010054eac5/77187c47-026c-4e00-b68d-6c11820bb86e.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>SM-T217S</td></tr><tr><td>Screen size</td><td>600</td></tr><tr><td>Screen size</td><td>600px by 1024px</td></tr><tr><td>Battery</td><td>31% Unplugged</td></tr><tr><td>Memory free</td><td>243 MB / 1347 MB</td></tr></table>

**Comment by ifoche** [comment]
We agreed with Rodolfo that we have to think it a little bit before giving a definitive solution. I leave it with a question label

**Comment by cristinaelle** [comment]
Irrelevant in 1.3.
