### ISSUE TITLE
Monitor, OU filter

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#222]
I go to Monitor and select an OU (_survey filter: all assessed_, _OU filter: _Test KE_): HNQIS shows all the surveys conducted at that OU by Health Area (nice!!!!). Some of them are the AVG of multiple surveys (i.e. TB). I click on the asterisk, it shows the list of scores and dates (nice!!!!). I click on one of them and it opens the Improve module of the survey I have selected (nice!!!!). I go back to the Monitor module and my selection of filters have changed: as filters, I don't have _survey filter: all assessed_ and _OU filter: _Test KE_ anymore, but I have the Health Area I opened the survey (KE HNQIS Tuberculosis) and All Org Units (_survey filter: KE HNQIS Tuberculosis_, _OU filer: All Org Units_). 
Can we change this, so that when users go back to the Improve module, they go back to the same screen they had before going to the Improve module?

**Comment by ifoche** [comment]
@cristinaelle we could do it, but just for you to assess the priority of that, it's not a minor change. Back buttons are currently taking you to improve if you come from a feedback, or taking you to assess if you come from a survey. What you describe looks like keeping what in Android is commonly named as the Back Stack, so pushing the screens in a stack and taking the user to the last screen when back is pressed. Depending on how the app is implemented it can be more or less adapted to implement it, and in HNQIS it could be done, but it wouldn't be straightforward.

**Comment by rodmelia** [comment]
I think that what Cristina is asking is just to preserve the last selection of the filter (in this case from monitoring) - the filtering doesn't change  when you open the action plan

**Comment by ifoche** [comment]
Just for the record. This change is only avoid the application of the filter before moving from monitoring to improve module when a bubble is clicked
