### ISSUE TITLE
Assess: Hide/show loading time

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#23]
Feedback from gtsmith@psi.org : It seems to take longer than usual for an answer to register on a 'parent' question. Can we improve this speed? 

 [Link to buddybuild feedback from build 4](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56d0a712b9cf69010045b545&bnum=4)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d057fac8f4aa010054eac5/c62b08ef-7ef7-4150-b52e-6e75ce556dde.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>SM-T217S</td></tr><tr><td>Screen size</td><td>600</td></tr><tr><td>Screen size</td><td>600px by 1024px</td></tr><tr><td>Battery</td><td>30% Unplugged</td></tr><tr><td>Memory free</td><td>211 MB / 1347 MB</td></tr></table>

**Comment by ifoche** [comment]
@gtrsmith This is a complex task. Some code refactor is needed to be able to do that and can take more than 2/3 days of work. Do you want us to afford it in this release?

**Comment by gtrsmith** [comment]
ok - can we add a processing timer icon popup? Also ensure that you stop queuing further requests for an answer response while the question is processing.
