### ISSUE TITLE
1.3 - Features missing from tech specs docs

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#231]
Reference docs: 
- [Tech specs](https://docs.google.com/document/d/1YXHkMosYsREGN23kB0nq-p3X-x4J0cyrlvZKKObA1OU/edit#heading=h.csfrk6dqp7oa)
- [Estimation](https://docs.google.com/document/d/1SaXHbxCAWRtMo95PN8pJYNwhcr8t9tinw-ZXJkyVFTc/edit)

From Tech specs doc:

- C4 Start new survey with past Obs & Action Plan: it might have been dropped and that's fine
- C5 Critical steps missed: it might have been dropped and that's fine 
- C7 Obs & Action Plan: recording provider's name in the Obs & Action Plan of the Improve module and being able to retrieve it from past Obs & Action Plans are still critical things countries keep asking for (possibility to include sex, too?)
- C1 Customized dates of f/up visits: if this has been implemented, I would love to know how to test it via DHIS2
- O3 Loading programs: can't say, @purdych1 to check
- O5 Walk through: partially I guess because this has to do with the issues we are having with Assess/Improve locked filters
- O7 Refresh metadata: cant's say, @purdych1 to check
- O7b Replace + with Start still missing
- O8 Control DEs review: can't say, @purdych1 to check

(let me know if you want me to report these by email/skype, etc)

**Comment by cristinaelle** [comment]
RM and I have reviewed this list and:
- C4: dropped,
- C5: critical steps have been included in the simple text message (#233 ), 
- C7: see #251 ,
- C1: left for the next version of HNQIS (#98 ),
- O5: killed,
- O7b: see #249 ,
- O3, O7 and O8: to address after 1.3. being released.

**Comment by cristinaelle** [comment]
Esunly and Sam report that at the moment, when there is a change to upload for existing HNQIS checklists (a new DE, new feedback script, a change in a DE Form name, etc), everything switches off, and previous-captured surveys will fail to be sent to DHIS2 because DHIS2 won't recognise data for that checklist any more. They suggest considering updating the metadata that is necessary, only, rather than updating everything.

(I am just a messenger!)

**Comment by cristinaelle** [comment]
Assigning Chris & Chris to review the last outstanding things from the tech specs docs:

O3 Loading programs: can't say, @purdych1 to check

O7 Refresh metadata: cant's say, @purdych1 to check

O8 Control DEs review: can't say, @purdych1 to check

**Comment by rodmelia** [comment]
@cristinaelle  @ChrisR13  - what about this ticket? Anything pending?

**Comment by ChrisR13** [comment]
I am working on this. Will review with Chris Purdy. Thanks

**Comment by ChrisR13** [comment]
@cristinaelle  - can you clarify what is needed here to complete this?

**Comment by cristinaelle** [comment]
Reference docs: 
- [Tech specs](https://docs.google.com/document/d/1YXHkMosYsREGN23kB0nq-p3X-x4J0cyrlvZKKObA1OU/edit#heading=h.csfrk6dqp7oa)
- [Estimation](https://docs.google.com/document/d/1SaXHbxCAWRtMo95PN8pJYNwhcr8t9tinw-ZXJkyVFTc/edit)

Have a look at these reference docs for the following things that are missing:

O3 Loading programs
O7 Refresh metadata
O8 Control DEs review

Rodolfo had indicated that these ones require GBS support. Not sure how to move forward for these (if need still be).

**Comment by rodmelia** [comment]
For me, the question is if it is justified further investment.

**Comment by ifoche** [comment]
Hi @cristinaelle. Just wanted to add the following in case it's useful:
**O3 Loading programs**: This is already implemented. Only programs that contain the program attribute are translated into the tablet. Not sure if your idea was something more sophisticated or maybe I'm missing some other information about this.
**O7 Refresh metadata**: I found the metadata/data downloader screen very useful in order to clearly be able to select what you need to download, at some point we created a mockup and we could rescue it if you find it useful.
**O8 Control DEs review**: In 1.3 there was already a control DE review and we solved some bugs related to the use of date formats, but again, maybe this is something else you discussed about

I don't want to add more noise, just wanted to say that I find O7 a very good idea, and try to understand if there's something else in O3 and O8 I'm not aware of that we can help with.

**Comment by rodmelia** [comment]
I think at this point we should focus in releasing what we have, rather
than adding more requirements. The only exception is the syncing for the
Action Report fields that it is pending.

**Comment by cristinaelle** [comment]
Yep, agreed. Also, it seems that Ignacio already addressed everything apart from O7 which can wait.

**Comment by ChrisR13** [comment]
@cristinaelle , with Ignacio's comments, I think we can move this to done, yes?
