### ISSUE TITLE
Assess, Overall Percentage in % Complete doesn't get to 100%

### ISSUE THREAD

**Issue by lindasato** [EyeSeeTea/QAApp#235]
On the Assess module, the % complete wheel that appears when the 3 vertical dots on the extreme right is tapped---the Mandatory percentage is accurate, however, the percentage for the overall doesn't seem to get to 100% despite answering all questions in the checklist. I have double checked and tried on different assessments but it still does not get to 100%
![percent complete](https://user-images.githubusercontent.com/26415203/33876956-00edfa3e-df38-11e7-812e-f557d34b071a.jpg)

**Comment by ifoche** [comment]
Can we have a DB from this situation?

**Comment by ifoche** [comment]
@lindasato @cristinaelle just mentioning you to be sure that you receive this as an email

**Comment by lindasato** [comment]
@ifoche I had exported the db to you yesterday on nacho@eyeseetea.com, just resent it again and attached it here. Let me know if this is okay now.
[compressedData.zip](https://github.com/EyeSeeTea/QAApp/files/1558909/compressedData.zip)
