### ISSUE TITLE
1.3 - Improve, No Images and Videos

### ISSUE THREAD

**Issue by lindasato** [EyeSeeTea/QAApp#239]
The images and videos in the same checklists in 1.2.8 are not in 1.3
![improve-images and videos](https://user-images.githubusercontent.com/26415203/33886816-de50db9c-df58-11e7-9f1e-17d20c81f80d.jpg)

**Comment by rodmelia** [comment]
Server: data.psi-mis.org
User: KEdemo1 / pw: Kenyademo1

**Comment by ifoche** [comment]
@lindasato It looks like the DE doesn't have the video ID in the DE attribute but in the feedback description, and not as the ID alone, but the whole URL. Can you please share that DE configuration?

**Comment by cristinaelle** [comment]
please, assign this to Chris Purdy or Ruly - I am on a phone and can’t tag people.
