### ISSUE TITLE
Assess (and feedback): controls disappear

### ISSUE THREAD

**Issue by rodmelia** [EyeSeeTea/QAApp#250]
![HNQIS Assess controls disapear.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56b36ea0c587de1300b8b565/125516c66e82c728ace21e0d46c0baab0ab1c3889cfaba50b71df39b2752357c2517e32f7996e238ba436943434d0eee1e020a17b8eb8339a3b06e748a5a58ebd13e5676c63912acb8821db602b928d85d99a4fedb1294b7607caddecd5d340c041f83fe5834a39a4fcf59f448e24852b65e.png)

**Comment by rodmelia** [comment]
I cannot see the filters in the assess module anymore. Details:
- Android 8.1
- After login with KEdemo2 (clone server)
- After starting a demo login

**Comment by ifoche** [comment]
@rodmelia assess module didn't have filters in 1.2 version. They were added on 1.3. Please see the screenshot below

![Screenshot (19 Feb 2018 15_56_10).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54e12dad64acc92700d55240/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec0ca9d40f4325337b54f27330d4b617ea1444505f465cb053181d1ba6acda6fb4bc2e758c0e0fedd73e5974953413acbc811fbf01b829884c8de5ae965e82b96371b8d6d6056b5c17129bfe5a3fa19c4ac158f348e14950a7143f71ab.png)

I guess we could keep this card open for 1.3 blank screen, right? Should I change milestone accordingly?

**Comment by rodmelia** [comment]
Ignacio tells me that my screenshot is 1.3, and not 1.2. Closing the issue
