### ISSUE TITLE
Assess: when to show the + button

### ISSUE THREAD

**Issue by rodmelia** [EyeSeeTea/QAApp#252]

**Comment by rodmelia** [comment]
![If filters for OU and Survey return 1 suervey, do not ofer 'Add'.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56b36ea0c587de1300b8b565/125516c66e82c728ace21e0d46c192da258b8fbd8afbac03a252e2d4067367722700e3186597f52da60269041b1a0cf251594f07b9accb6df3ff2060de031bb38e294f2b906853bcaff34beb16a83c990fc7e9e6df1f84fa3737e28ddd4b3e18561e89ac5437a09d48c858f649e84e56ac40247ff434672213cb432c663e2534a1eede518d8465a5b9132c52c8e5e6ff1110b331.png)
![HNQIS - preserve filter selection when adding new survey.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56b36ea0c587de1300b8b565/125516c66e82c728ace21e0d46c0baab0ab1c3e4cff9ad46b758e2822c06217a2510a6393096e624ba416f0800015eeb190d0154adaddd72f8e12c2edf1b1bae942f19218f2f0dbef8c040e554e964994597b3bad848c0ee6e23e7d8864d3e1a061889ff5f3ca39a439b4aea59a31c0bf04c6b3aac23746e4d861f7c266a6227a8ffdc52878362a5bc123d1b.png)

**Comment by ifoche** [comment]
Just for the record:
1) Do not show + button when a survey in progress exists
2) Auto-fill OU and Survey selections from survey creation screen

**Comment by cristinaelle** [comment]
Done.
