### ISSUE TITLE
Assess: relocate Floating + button

### ISSUE THREAD

**Issue by rodmelia** [EyeSeeTea/QAApp#253]
![relocate + buttom.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56b36ea0c587de1300b8b565/125516c66e82c728ace21e0d46fa91962c8182bd8aa9f403a648e480264b653f6b14b1247a80e03cfd183954590d4aac470b5944aff08b2ba2b53c708a5e02eed2650c66da2f53fde6d640e258f075c95d8fa4bd8d46c1ed3c26e4888b4e3b16011d8aed10.png)

**Comment by ifoche** [comment]
Already implemented in 1.3

**Comment by cristinaelle** [comment]
Done in 1.3.

**Comment by rodmelia** [comment]
done in 1.3
