### ISSUE TITLE
All modules: Increase space between drop down options

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#26]
Feedback from gtsmith@psi.org : Unfortunately i cannot shake with a layover screen. The assessments in the drop down menu are too close together.  Please give then a little more space to make them easier to select

 [Link to buddybuild feedback from build 4](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56d0aa65e2893201006fdef1&bnum=4)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d057fac8f4aa010054eac5/136e8106-b33f-4bbe-b391-6687fd1af184.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>SM-T217S</td></tr><tr><td>Screen size</td><td>600</td></tr><tr><td>Screen size</td><td>600px by 1024px</td></tr><tr><td>Battery</td><td>28% Unplugged</td></tr><tr><td>Memory free</td><td>178 MB / 1347 MB</td></tr></table>

**Comment by gtrsmith** [comment]
We should apply standard spacing throughout - so this applies to all dropdown menus

**Comment by gtrsmith** [comment]
Nice - this is resolved
