### ISSUE TITLE
1.2.10: Inverted Yes/No Answer Boxes

### ISSUE THREAD

**Issue by lindasato** [EyeSeeTea/QAApp#261]
The answer boxes in 1.2.10 are appearing in reverse order, "No" then "Yes".
![1 2 10 inverted answer boxes](https://user-images.githubusercontent.com/26415203/37039192-e7fa8ee4-2167-11e8-9026-14a6212eebd4.png)

**Comment by cristinaelle** [comment]
Yep, it happens to me, too:

![screen shot 2018-03-07 at 13 36 31](https://user-images.githubusercontent.com/12784825/37088041-155d8102-220d-11e8-80f7-8ca7b71e554f.png)
