### ISSUE TITLE
1.2.10: Loss of Observation and Action Plan after Refreshing metadata

### ISSUE THREAD

**Issue by lindasato** [EyeSeeTea/QAApp#263]
When I refresh metadata then open the Observations and Action plan of an assessment I had completed before refreshing metadata, it is blank.  (Note: I had marked as complete before refreshing metadata and shared). Once it is blank, it is possible to type in new comments and send again which shouldn't be the case. This is the first time this is happening. The previous versions we had of the Obs and Action Plan would not be blank after refreshing metadata.

**Comment by ifoche** [comment]
@lindasato. Observation & Action Plan is not translated in the sense server -> app. So refreshing metadata will make the user think there's no previous observation & action plan. We were required to implement it in that way. However, I think that could be a good feature for the next release

**Comment by rodmelia** [comment]
@ifoche - what's the status for this in 1.3? Is HNQIS retrieving any saved data for action plan ?

**Comment by ifoche** [comment]
@rodmelia no. Pull of Observation & Action Plans from the server was never implemented.

**Comment by rodmelia** [comment]
Set for 1.4 - June 2018 ?

**Comment by cristinaelle** [comment]
I understand this is something very difficult to implement (and expensive). Please, work on an estimation of LoE before addressing this card.

**Comment by rodmelia** [comment]
Yes - we are working on that.

**Comment by rodmelia** [comment]
ESTIMATION: 20-30h

**Comment by rodmelia** [comment]
@ChrisR13  & @cristinaelle  - let us know final decision

**Comment by ChrisR13** [comment]
@rodmelia  @ifoche  - please hold off on this functionality for future iterations of HNQIS. We don't have the budget to support this right now.
