### ISSUE TITLE
1.3 - Plan: disable multiple selection of OU/Health Area when the user clicks on the 3 vertical dots

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#265]
In the Plan module, I have selected more than one OU/Health Area and then clicked on the 3 vertical dots of one pair OU/Health Area: HNQIS allows me to reschedule the date for the pair OU/Health Area I have selected, nice. However, the other OU/Health Area that I have previously selected is still selected, a bit confusing. Suggest removing the selection of multiple pairs OU/Health Area when the user clicks on the 3 vertical dots because the 3 vertical dots refers to one pair of OU/Health Area, only. When more than one pair of OU/Health Area is selected, only the blue calendar should be active. 

![1 plan](https://user-images.githubusercontent.com/12784825/38831503-48ea5088-41c8-11e8-9bc0-8ec18b08752a.png)

**Comment by rodmelia** [comment]
1. When rescheduling a single OU/ Survey, please add information on the heading of what OU/ Survey is currently selected (see screenshot red area above)
2. When more than one survey is selected, please:
- Hide the ... on the right 
- Display X number of surveys being re-schedule for OU XXXX (see screenshot red area above)

**Comment by janetpatry** [comment]
Assess Module, percent complete feature is not calculating correctly for IMCI. Other health areas are fine.
<img width="416" alt="incorrect percent complete" src="https://user-images.githubusercontent.com/38428114/39055151-1f0bed7a-44bc-11e8-95d8-000d080f4217.PNG">
