### ISSUE TITLE
1.3 - Plan: unlock Save button 

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#266]
From the Plan module, I want to reschedule an assessment: it seems that I can’t Save a rescheduling unless I click on the calendar, first. The Save button is not active until I click on the calendar and select a date. I understand the rationale for doing so, however it seems that the HNQIS calendar remembers the last date I have selected, so it'll be nice to allow users to click on Save straight away in case the date shown in the calendar is the one I have used the last time and still want to use this. 

![2 plan](https://user-images.githubusercontent.com/12784825/38831702-e82734e0-41c8-11e8-9ede-4788d2164136.png)

**Comment by rodmelia** [comment]
Another way to report the problem: when doing mass-rescheduling, the save button doesn't work UNLESS you select a new date. The save button should always work, even if you don't change the date.

**Comment by ifoche** [comment]
The rational under blocking the button is to avoid rescheduling to the same date that is already scheduled. It makes sense for normal rescheduling but it doesn't for massive rescheduling. As the component is the same one, this is something that we didn't see, but it's not very difficult to create a variation for the massive rescheduling. I agree with the complexity-low label
