### ISSUE TITLE
1.3 - Assess: message in case of no active surveys?

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#269]
In the Assess module, when I select a pair of OU/Health Area, in case there is no active survey for the selected pair, do you think we can have a message popping up that says ‘No active survey for your selection. In case you want to start a new survey for your selection, click +’?

![5 assess](https://user-images.githubusercontent.com/12784825/38832562-9f17846e-41cb-11e8-81dc-a7b83c91f6a8.png)

At the moment, when the user selects a pair of OU/Health Area, the screen is blank (because there is no active survey) and he has to intuitively click on + to start a new survey with the selected pair OU/Health Area (that automatically populate the filters, nice!!). 

![6 assess](https://user-images.githubusercontent.com/12784825/38832566-a3c915b8-41cb-11e8-8702-dbf63fbcc00d.png)

**Comment by rodmelia** [comment]
@ifoche: please add the following message to Assess and Feedback when no surveys are returned.

Initial PO editor sentences - will be updated later.
- Assess: 'No active survey(s) at this time for the selection you have made. Click on + to start a new survey'

- Feedback: 'No survey(s) completed for the selection you have made. '
