### ISSUE TITLE
Duplicate: Health Facility name 

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#27]
Feedback from gtsmith@psi.org : If we can throughout the tablet give the health facility it's own row and then color that row only i think it would be cleaner.  

 [Link to buddybuild feedback from build 4](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56d0ab136e11a00100ae4f41&bnum=4)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d057fac8f4aa010054eac5/0a8868de-cf42-406d-9cde-c9a4fa74ba2f.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>SM-T217S</td></tr><tr><td>Screen size</td><td>600</td></tr><tr><td>Screen size</td><td>600px by 1024px</td></tr><tr><td>Battery</td><td>27% Unplugged</td></tr><tr><td>Memory free</td><td>187 MB / 1347 MB</td></tr></table>

**Comment by gtrsmith** [comment]
This is issue number #11 and #13
