### ISSUE TITLE
URL: layout changes

### ISSUE THREAD

**Issue by rodmelia** [EyeSeeTea/QAApp#273]
Collect feedback and then list all necessary changes to the web page - sent as a single feedback doc

**Comment by cristinaelle** [comment]
1) See #210 for the new Scoring classes. 
2) Report Provider's name right below the score of every tab (i.e. for IMCI, we'll have a provider's name below 1. Inquiry and Physical Examination, for FP, we'll have a provider's name for several tabs). See #281.

**Comment by cristinaelle** [comment]
Can we make sure that the url works for sfhnigeria and singapore servers, too? Unfortunately, I can't test this.

**Comment by ifoche** [comment]
assigning to @rodmelia as it has to do with WS URLs
