### ISSUE TITLE
1.3 - Round of the scores

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/QAApp#277]
## User Report
Please round of the scores in monitor module. This is the only place I have seen this not rounded off ( see screenshot). The rest of the sections are displaying 100% for this example used.

## ScreenShot
![file](https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/android_screenshot592482888.jpg)
## Device Info
```
Time Stamp: 2018-04-21T02:49:01 UTC
App Version: 1.3.1 (42)
Install Source: com.android.packageinstaller
Android Version: 7.1.1 (25)
Device Manufacturer: SAMSUNG
Device Model: SM-T555
Display Resolution: 768x1024
Display Density (Actual): 160dpi
Display Density (Bucket) mdpi
---------------------

```

**Comment by lindasato** [comment]
For some reason reporting by shaking is only capturing the main page of the monitor module. I have attached below the appropriate screenshot.
![round off scores-issue 277](https://user-images.githubusercontent.com/26415203/39079797-521402c0-452a-11e8-9103-3575b7d1e6a7.jpg)
