### ISSUE TITLE
DESIGN: Assess and Improve: increase color contrast

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#278]
From Janet: 
Please increase the color contrast for better clarity. Compared to the older version of HNQIS, the new is very muted. And the Feedback module used to have gray questions and white feedback--it was easier to see the feedback that way. Please consider adding it back.

<img width="456" alt="39060788-0025b5ee-44cb-11e8-98ff-09ccb26ff328" src="https://user-images.githubusercontent.com/12784825/39080338-d4195a90-4534-11e8-9639-4ca0c7854874.png">

<img width="329" alt="39059196-8555f79c-44c6-11e8-9eba-b065422d3ecd" src="https://user-images.githubusercontent.com/12784825/39080339-d4452a1c-4534-11e8-9846-b7837e82a3d1.png">

**Comment by rodmelia** [comment]
1. I suggest changing the words fail/ pass by icons: a green check mark, a red cross. That way we eliminate the horrible problem of letters going into the next row.

2. About the colours 
2.a. Survey: I personally prefer the more muted tones. What is the opinion of users?
2.b. Feedback: I agree that we can increase the height of the header, as well as the get the background colour to extended across. Again, what's user's impression?

**Comment by ChrisR13** [comment]
Hi all - I am amenable to keeping the muted tones in the questions themselves. I think the titles of each section however,  should retain that original dark black contrast as it helps denote a clear separation between sections.

**Comment by cristinaelle** [comment]
Change from Fail/Pass to Red/Green icon (a tick mark? a square?): makes a lot of sense, great idea! We have issues with letters going into the next row for FR and PT, too, so this suggestion is welcome.

**Comment by rodmelia** [comment]
#197 addresses the issue of the replacing Pass/ Fail for icons. They have been provided.
We still need to resolve the issue of colours in general

**Comment by rodmelia** [comment]
I'm closing this issue and moving the discussion to #284, which addresses all open design issues.
