### ISSUE TITLE
1.3 - Assess: percent complete feature is not correctly calculated for IMCI

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#279]
From Janet: percent complete feature is not calculating correctly for IMCI. Other health areas are fine.

<img width="416" alt="39055151-1f0bed7a-44bc-11e8-95d8-000d080f4217" src="https://user-images.githubusercontent.com/12784825/39080366-3c001b4e-4535-11e8-96aa-a854e921e840.png">

**Comment by ifoche** [comment]
@cristinaelle I cannot clearly see how to reproduce it in your image. Do you mean that if you enter the survey the percent is different than from the listing?

**Comment by cristinaelle** [comment]
Over to Janet because she is the one who has reported this. I have given her a heads-up on this.

**Comment by janetpatry** [comment]
You can disregard this. I thought it was calculating the total number of questions answered out of 100%. But I now see it is calculating separately for each Overall and Mandatory. Sorry! It was me who was confused!
