### ISSUE TITLE
Improve: PASS / FAIL language

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#28]
Feedback from gtsmith@psi.org : This should be PASS unless Rodolfo or Cristina asked to change it

 [Link to buddybuild feedback from build 4](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56d0ac733e5db4010008915c&bnum=4)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d057fac8f4aa010054eac5/cc43d3bf-2895-4fe6-8b17-7d4ed951f8ef.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>SM-T217S</td></tr><tr><td>Screen size</td><td>600</td></tr><tr><td>Screen size</td><td>600px by 1024px</td></tr><tr><td>Battery</td><td>26% Unplugged</td></tr><tr><td>Memory free</td><td>217 MB / 1347 MB</td></tr></table>

**Comment by ifoche** [comment]
@gtrsmith That change was made following a meeting instructions...we can change it without problem, but does everybody agree? @rodmelia @cristinaelle ?

**Comment by cristinaelle** [comment]
Yes, please, change this to pass.

**Comment by gtrsmith** [comment]
Resolved
