### ISSUE TITLE
1.3 - Improve: provider's name DE missing in DHIS2

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#280]
In the Obs & Action Plan, supervisors fill in 4+1 fields: Provider name, Gaps, Action Plan, Action 1 and Action 2. In DHIS2, we can't locate the Provider name DE. We have DEs for Action Plan, Action 1 and Action 2, but not for Provider name. 

![screen shot 2018-05-02 at 17 51 37](https://user-images.githubusercontent.com/12784825/39530466-afd36d6e-4e31-11e8-810f-af14d93d5137.png)

**Comment by ifoche** [comment]
@cristinaelle I've just checked in clone server and for example for the program KE HNQIS IMCI the data element _ProviderName is not added. I think that the only thing that's missing is to add the DE to the program. But I don't have the permissions to do it on data...I guess this one is for @rodmelia ?

**Comment by ifoche** [comment]
assigning to @rodmelia for him to check it and verify if the server modification solves the issue.

**Comment by rodmelia** [comment]
Assigning to Chris

**Comment by ChrisR13** [comment]
hello! a ticket on Helpdesk has been created for the BAO team to implement across all countries, programs.

**Comment by ChrisR13** [comment]
The two DEs have been added to each program in production. @cristinaelle  feel free to confirm!

**Comment by cristinaelle** [comment]
Kindly note that it is not working. Empty value for the DE _ProviderName in DHIS2. 

![screen shot 2018-06-20 at 13 01 42](https://user-images.githubusercontent.com/12784825/41651831-301b5c06-748a-11e8-95a7-d91bce0be498.png)

**Comment by ifoche** [comment]
Hi @cristinaelle, did you refresh metadata after the DE was added to the server? The control DEs are processed in the app during the metadata pull, so if it was not present during that stage, it will not be sent later.

**Comment by cristinaelle** [comment]
yes, I logged out and logged in again with a new username / pw.

**Comment by ChrisR13** [comment]
Any thoughts @rodmelia ?

**Comment by rodmelia** [comment]
I've moved this to ready for Ignacio to investigate further.

**Comment by cristinaelle** [comment]
sent

**Comment by ifoche** [comment]
Thank you! We will study it. BTW, just to be sure, but people are filling in the provider's name field, right? I mean, is not like people are sending it blank and that's why it's blank in those cases...Because we're consistently getting it sent

**Comment by cristinaelle** [comment]
Now provider's name is showing up in data, too. Sorry! Closing this. 

![screen shot 2018-07-04 at 16 48 03](https://user-images.githubusercontent.com/12784825/42280674-17c1e60e-7faa-11e8-9f8e-87039eba6f7c.png)
