### ISSUE TITLE
DESIGN: Improve module: inconsistent layout

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#284]
This looks a bit confusing: below some question rows we have a dark black line, below others we don't have any  line, below others we have a light black line. I don't have a specific suggestion, just to clean this up a bit: leave a grey line between rows and a dark line between sections?

![screen shot 2018-05-15 at 18 13 17](https://user-images.githubusercontent.com/12784825/40066319-836195f4-586c-11e8-9e4c-2dde7f86c2f5.png)

Also note that when a feedback script is open, there is a line between the question row and the feedback script. Can we remove it, so that it is clear that the feedback refers to the question row above? This is related to #278 (color contrast).

![screen shot 2018-05-15 at 18 17 48](https://user-images.githubusercontent.com/12784825/40066301-7eff2d1e-586c-11e8-8e80-c2e088294588.png)

**Comment by cristinaelle** [comment]
We have tested this and we think it's not there yet. The difference between questions and feedback scripts is very unclear and the indentation doesn't help. Can we have a different background for questions and scripts, please? Also related to #278 .

**Comment by rodmelia** [comment]
@cristinaelle  - please review and comment the updated design below
![HNQIS revised June design.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56b36ea0c587de1300b8b565/125516c66e82c728ace21e0d46c0baab0ab1c3bb8affb650a159b0be3c4822332d01b022778ba164fd52690e050a1de853524d41faab8d2ba0e53a70d95509edd56e5f74c63f18afbb8a4cad1da862da11d1e9e1d30695aa2f2ff58a87453f1b071181fd5b30a2904ccb51e406.jpeg)

**Comment by cristinaelle** [comment]
approved! tks!
