### ISSUE TITLE
Version 1.2.14 Duplication of never assessed surveys in Plan Module

### ISSUE THREAD

**Issue by janetpatry** [EyeSeeTea/QAApp#286]
When the users logged in for the first time to version 1.2.14, Never Assessed had 40 surveys in it. The next day it had 80. The day after that it had 160. It kept doubling every day until it reached 240. It stopped at 240. This happened to multiple users in Kenya. I am unaware of it happening in other countries.
[compressedData.zip](https://github.com/EyeSeeTea/QAApp/files/2039513/compressedData.zip)

**Comment by ifoche** [comment]
@janetpatry we've found a solution (this one was really hard) but the solution wouldn't fix the never assess list for those that are currently experimenting the problem. It's not a big problem from the app's perspective, but the user can be confused seeing so much never assessed surveys. After applying the fix that we've created, if the user refresh metadata, the problem will disappear, but if not, the list of never assessed would still be there. How do you want us to proceed? Shall we go ahead creating a release and testing it?

Thank you!

**Comment by janetpatry** [comment]
Hi Ignacio,

Can we please combine this with the 1.3.3 release?

________________________________

**Comment by ifoche** [comment]
Hi Janet. I think that because of the way this is done in 1.3.x it shouldn't be happening in 1.3.3. Did you experienced this behavior in 1.3.x?

**Comment by cristinaelle** [comment]
Yes - Janet did.

**Comment by ifoche** [comment]
ok, we will review it also in 1.3. Should we generate the fix for 1.2.x too?

**Comment by cristinaelle** [comment]
We are very close to release 1.3, so I'd say to wait for 1.3.
