### ISSUE TITLE
1.3 - Enable viewer for Multimedia library

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#289]
Can't say whether the option to Download multimedia works in 1.3. Please, make sure to check that users have the possibility to download the multimedia onto their tablets and access them from this menu option (at the moment it doesn't work in 1.2.14). 

![screen shot 2018-06-14 at 14 01 24](https://user-images.githubusercontent.com/12784825/41408494-8daac48c-6fdb-11e8-868b-1451ed1139d4.png)

**Comment by ifoche** [comment]
@cristinaelle looks like the image you're showing doesn't contain any downloaded media. Does that user have access to programs whose metadata has been configured to point to some videos using the Drive UID in the data elements? Could you provide an example user to test on clone.psi-mis.org? Thank you!

**Comment by cristinaelle** [comment]
I have tried for a user in data (MWdemo1; Malawidemo1) and got the same issue. MWdemo1 has access to videos in 1.2.14, but it seems that videos are not loaded into the Multimedia library for 1.2.3 (sshot). 

![screen shot 2018-06-15 at 09 35 13](https://user-images.githubusercontent.com/12784825/41453864-00e76d0c-7080-11e8-89ab-927507901077.png)

@ChrisR13 : can you please replicate MWdemo1 in clone, so that we can see if a user who has access to video in 1.2.14 still has got access in 1.3?

**Comment by ChrisR13** [comment]
Hi @cristinaelle - I am unable to replicate MWdemo1 at this time due to a technical issue with DHIS2. I can't replicate any HNQIS accounts. I have raised the issue to @rodmelia , JM, and Rodrigo

**Comment by cristinaelle** [comment]
In case it helps - I have tested this on 1.3, data.psi-mis.org, KEdemo1, Demo1234, waited for the analytics to run and ER still shows no data values for _ProviderName.

**Comment by rodmelia** [comment]
@cristinaelle @ChrisR13  - what's the status fo this ticket?

**Comment by cristinaelle** [comment]
I saw Linda submitting a ticket to Esunly to investigate this further because it seems that videos appear randomly (some of them appear, others do not and there is no consistency in this behavior).

**Comment by ChrisR13** [comment]
@cristinaelle   - there appear to be some other tickets being submitted around issues with functionality. Janet and I experienced this.

**Comment by ChrisR13** [comment]
Just an FYI: This is the ticket @cristinaelle  is mentioning. https://helppsi.freshdesk.com/a/tickets/2507

**Comment by ifoche** [comment]
Looking into it, I'll come back with the result of the investigation soon.

**Comment by ifoche** [comment]
could we have the DB for this problem, too? We cannot replicate it (Thanks!). We're currently blaming a lack of space in the device or a 3g + intermittent wifi connexion. Videos will only download over WiFi, and maybe that could explain this behavior.

**Comment by lindasato** [comment]
In 1.3.4,  the Downloaded Media is just a list of the videos and Images (see screenshot below). Is there a way the videos/Images can be accessed from this page? Not sure how this is supposed to work.

![downloaded media 1 34](https://user-images.githubusercontent.com/26415203/43081216-326e7e6e-8e9a-11e8-8922-dfe7bc46a261.jpg)

**Comment by ChrisR13** [comment]
Agreed with Linda. I thought this feature would enable a user to click and view a video without having to go through Improved module.

**Comment by rodmelia** [comment]
HNQIS didn't have this functionality (Connect has it). We will include for a future release

**Comment by ifoche** [comment]
@lindasato, @cristinaelle any news on this?

**Comment by lindasato** [comment]
@cristinaelle, @ifoche  , I have tested this on 1.4 in latest server using the credentials, KEdemo1/Kenyademo1 and it is working well. I am able to play videos and view images from the downloaded media section.

**Comment by cristinaelle** [comment]
Great, thanks!
