### ISSUE TITLE
Improve: Increase size of checkbox

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#29]
Feedback from gtsmith@psi.org : Make this check box bigger if you can

 [Link to buddybuild feedback from build 4](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56d0acaaa7e42601004887ee&bnum=4)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d057fac8f4aa010054eac5/403d1802-2d13-4036-8f36-159aa2cce7f9.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>SM-T217S</td></tr><tr><td>Screen size</td><td>600</td></tr><tr><td>Screen size</td><td>600px by 1024px</td></tr><tr><td>Battery</td><td>26% Unplugged</td></tr><tr><td>Memory free</td><td>168 MB / 1347 MB</td></tr></table>

**Comment by ifoche** [comment]
sure! no problem

**Comment by gtrsmith** [comment]
Resolved for now unless we get feedback from field asking to increase size here further
