### ISSUE TITLE
Videos don't load randomly

### ISSUE THREAD

**Issue by esunly** [EyeSeeTea/QAApp#291]
For HNQIS 1.2.14 some videos load and others don't. On refreshing metadata, at times the ones which were missing load but then different videos don't load.  This appears to be random and not particular to any videos.

**Comment by esunly** [comment]
Some accounts to test:

User: KEdemo1
Password: Kenyademo1

User:MWdemo1
Password: Malawidemo1

**Comment by esunly** [comment]
Hi,

I just wanted to know if there is any progress with this issue.

Best,
Esunly

**Comment by rodmelia** [comment]
@esunly  - can you confirm that the device that you are using has enough storage space in the main memory?. Please send a screenshot of your device's storage availability.

**Comment by esunly** [comment]
@rodmelia, @ifoche  It seems that the issue was caused by the problems with data server. The user have tested again and the videos are loading now well. You can close this issue now.

Many thanks for following up!
Best,
Esunly
