### ISSUE TITLE
1.2.14 Repeatedly Crashing for Kenya

### ISSUE THREAD

**Issue by janetpatry** [EyeSeeTea/QAApp#292]
Kenya is reporting the app is crashing. When they open a new assessment, the app crashes. When they try to mark an assessment as complete, the app crashes. They get the message, HNQIS has suddenly stopped working. I'm trying to get them to export their database but so far they can't because of the crash. 
Other things to note in respect to this issue: 1) the data server is extremely slow--I raised a ticket for this, 2) Mali can't log into their account (Linda raised a ticket for this) 3) Kenya's Plan module is duplicating never assessed again after it had stopped for awhile (there is an existing issue #286 for this) 
All three of the above issues have occurred in the last 24 hours, so, perhaps they are related.

**Comment by cristinaelle** [comment]
@purdych1 and @rodmelia : the data server is extremely low these days. wonder if these issues are related to this?
