### ISSUE TITLE
1.3.4 - Assess: different message in case of inactive selection of pair OU/Health Area

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#293]
In case the pair OU/Health Area is not active because that Health Area is not assigned to the selected OU, if possible, let’s display a different message: ’This survey is not assigned to this facility. Please, select another survey.’
The current message doesn't make sense because the user can't start any new survey. 

![screen shot 2018-07-23 at 12 17 11](https://user-images.githubusercontent.com/12784825/43081237-3c913972-8e9a-11e8-965a-4749a68e6e7c.png)

**Comment by rodmelia** [comment]
This could be a bug - in theory you should not be able to get to this selection.
