### ISSUE TITLE
1.3.4 - Improve: pointers to % completion wheels are off

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#294]
Please, note that pointers to the % completion wheels are off and in some cases, the pointer to the inner circle lands on the outer circle. This happens for both ways users have to access the % completion wheels: from the landing page of the Assess module and from the top bar of the Assess module when you are completing a survey. 

![screen shot 2018-07-23 at 15 45 19](https://user-images.githubusercontent.com/12784825/43081348-79f74bd0-8e9a-11e8-974b-59dfd6b3a43f.png)

![ls screenshot](https://user-images.githubusercontent.com/12784825/43081349-7a27e52e-8e9a-11e8-9457-d7a57d551893.jpeg)

**Comment by rodmelia** [comment]
@cristinaelle - Below a simple proposal to adjust the control. What do you think?

Trying to align the reference lines dynamically will be a significant effort. I've also identified it as low priority (1.3 can be released as it is)
![Screen Shot 2018-07-30 at 11.56.01.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56b36ea0c587de1300b8b565/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246457f36b7191a379ee0c2e57415f4fbe5d4a1f06a3a3dc78e2a436628f5a59e9d16b0c72c66e18aeb8861cbf01ba22824c86beef9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecb5aff4de74956a5143463f43b.png)

**Comment by cristinaelle** [comment]
What if the line for the overall questions stay where it is and the line for mandatory questions goes right to the center of the circle(s)? This won't be dynamic - just making the line for mandatory questions closer to the inner circle. And the closer you can get it's right in the middle of the circle.
