### ISSUE TITLE
1.3.4 - Improve: consider reporting 0.0% on a grey background

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#296]
0.0% scores in the Feedback page are shown in white on a red background. Super confusing to the user. In case this is a minor change, do you think we can have 0.0% on a grey background? The users will greatly appreciate this. 

![screen shot 2018-07-23 at 17 09 04](https://user-images.githubusercontent.com/12784825/43081802-21cbb8e6-8e9b-11e8-9295-9c1d1d86c4c0.png)

**Comment by ChrisR13** [comment]
Can we use the same grey from the NA responses? I concur with @cristinaelle  that any sections with all NA responses should be changed to the grey color.
