### ISSUE TITLE
1.3.4 - Improve: not all critical questions are marked with an asterisk in the Feedback page

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#297]
Linda has tried to find a pattern, but couldn't find any. We have noticed that in the Feedback page of the Improve module, not all critical questions have an asterisk at the end. Some have, others don't.

**Comment by rodmelia** [comment]
@cristinaelle  - could you prove an example:
- Login details, survey to open

**Comment by cristinaelle** [comment]
data server
KEdemo1;Kenyademo1
IMCI checklist on any Test OU

First section - Inquiry and Physical Examination (2 random Qs don't ask asterisk in Improve):
- Provider asks whether there are lethargy, convulsions/convulsing now
- Provider asks if the patient can drink or breastfeed

![screen shot 2018-07-24 at 09 53 49](https://user-images.githubusercontent.com/12784825/43122021-540c62d2-8f28-11e8-9ab7-b222ac4803de.png)


Second section - Diagnosis, Treatment and Counseling (2 random Qs don't have asterisk in Improve):
- Does the provider give the correct treatment or refers in case of danger signs or sever illness?
- Provider counsels caregiver on proper dosage (no. of doses/days, side effects).

![screen shot 2018-07-24 at 09 57 35](https://user-images.githubusercontent.com/12784825/43122041-6049299a-8f28-11e8-84ff-52353d850103.png)

**Comment by rodmelia** [comment]
Probably just hidden behind a layout - Ignacio will review
