### ISSUE TITLE
1.3.4 - Bugs we can't replicate

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#299]
We are reporting some bugs that we have seen multiple times, but that we can't replicate in a consistent way - just for you to be aware. 

1) Plan: sometimes the massive rescheduling page is blank. When I select an OU, the page is blank. This happens on many servers.

![screen shot 2018-07-23 at 12 22 03](https://user-images.githubusercontent.com/12784825/43082359-8952e7cc-8e9c-11e8-9224-ae3e1ed651df.png)

2) Logging in scree: sometimes there is a black screen when logging in and nothing happens. 

3) Improve: we have issues with this module. Its behavior can be schizophrenic. Sometimes it randomly bounces you out of the module and takes you back to the landing page of the Improve module.

**Comment by rodmelia** [comment]
@cristinaelle & @ChrisR13  -  any further information on how to replicate this issues?
If you manage to replicate any of them, please send database
