### ISSUE TITLE
Assess: Buggy view in assess module when PLAN is hidden

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#30]
Feedback from gtsmith@psi.org : I get this funky view in the assess module when i hide the plan module

 [Link to buddybuild feedback from build 4](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56d0ad7a355eae0100bed339&bnum=4)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d057fac8f4aa010054eac5/e57000c8-a3c2-4a37-84d5-8cad17eb02e7.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>SM-T217S</td></tr><tr><td>Screen size</td><td>600</td></tr><tr><td>Screen size</td><td>600px by 1024px</td></tr><tr><td>Battery</td><td>25% Unplugged</td></tr><tr><td>Memory free</td><td>200 MB / 1347 MB</td></tr></table>

**Comment by gtrsmith** [comment]
resolved
