### ISSUE TITLE
1.3.4 - Improve: Grey w/ yellow text change 

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/QAApp#300]
## User Report
Please change the yellow NA text on the grey background as it is difficult to see. Recommend changing to a black font on grey background. 

## ScreenShot
![file](https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/android_screenshot1630166937.jpg)
## Device Info
```
Time Stamp: 2018-07-23T15:10:12 UTC
App Version: 1.3.4 (45)
Install Source: Package Installer
Android Version: 7.0 (24)
Device Manufacturer: SAMSUNG
Device Model: SM-T580
Display Resolution: 1920x1200
Display Density (Actual): 240dpi
Display Density (Bucket) hdpi
---------------------

```

**Comment by ChrisR13** [comment]
This is in conjunction with ticket #294, re: grey background.
