### ISSUE TITLE
1.4 - Error with date of next visit for Class B

### ISSUE THREAD

**Issue by lindasato** [EyeSeeTea/QAApp#306]
The date of the next visit for Class B is calculating as +2 months instead of +4 months
![1 4 - class b next visit](https://user-images.githubusercontent.com/26415203/46365065-41fccc00-c680-11e8-8639-1df8618c46fe.jpg)

**Comment by ifoche** [comment]
@lindasato, is this related to #307?

**Comment by lindasato** [comment]
@Ignacio, actually I just realized they are related. Let me close this since once #307 is sorted this will be fixed too.
