### ISSUE TITLE
1.4 - Mismatch in score and class due to rounding off 

### ISSUE THREAD

**Issue by lindasato** [EyeSeeTea/QAApp#307]
So, we assign a very small score (0.00001) to each non-critical/ non-mandatory questions so that the "✓" or "X" signs can show improve module. Please adjust the decimal places so that scores from the non-critical questions remain insignificant Currently, this is significant. Example
(a) 16/20=80%....this appears as yellow in the tablet (Class B) which is correct
(b) 16/20.00001=0.7999996. This displays as 80% in the tablet but as red (class C)
2 decimal places should fix the issue.

**Comment by ifoche** [comment]
@lindasato this may have much more implications than it may seem in a first look. Wouldn't be better to fix the original problem and avoid the need of providing a score to question just to make them appear in the improve module? (something like defining if a question contributes or not to the scores separately so we can show all questions with a score in the improve module but only some of them would contribute to the global score). The score concept is deep inside the app and used for other purposes, and we may be altering other behaviors (like control data elements) or adding unnecessary overload on some calculations. Does it make sense for you?

**Comment by lindasato** [comment]
@ifoche , yes this makes sense. But we don't really need to see which questions contribute to the scores in improve module, we just need to see whether the question was passed or failed by the appearance of the "✓"or "X" next to the question in Improve module . But I will defer this to @cristinaelle to make a decision since removing these scores (0.000001) will require additional LoE since this has been implemented for all programs for all the countries.

**Comment by cristinaelle** [comment]
We can't ask the developers to review ALL scores just to fix a misclassification in terms of Classes when the score is VERY close to 80%. There is a trade-off here. If we can't find another solution, let's leave with this little bug.

**Comment by ifoche** [comment]
@cristinaelle maybe there's no need to ask for the review of all scores. If we consider the default behavior of a score as "included" it would be backward compatible and just in those cases where we will be creating a new score or if we want to explicitly change a specific one that is particularly ambiguous we use it. Does it sound better?

**Comment by cristinaelle** [comment]
I am afraid I don't understand what you are proposing here as a solution, my bad! Can you explain further, please?

**Comment by ifoche** [comment]
Sure, sorry, probably I'm not explaining it very clear. 

The point is that you can decide if a composite score contributes or not to the global score (via e.g. a new attribute in the DE, or simply a new value for the current of DE type attribute called "COMPOSITE_SCORES_NOT_CONTRIBUTING" or something similar). 

In that case, if you decide to contribute to the global score, then the behavior is exactly the same as now (improve module shows the question, its answer and if the answer pass or fail, its value counts for the final score, and everything in the same way. 

But if you decide to use the new composite score type, then, improve module shows it with the answer and with the result pass or fail, but when doing the calculations for the global score it's simply ignored. So you can use the score as you want with this irrelevant score, that it will only work to decide which is the correct answer, but not for the global score. So if you currently leave the scores as they are, they keep behaving as they're doing now, but if a concrete score is producing problems then you can use the new mechanism to set that score to irrelevant and it won't be taken into account. For the future, you can train the people to build the new surveys using also this feature, but you don't need to review all the previous ones if they don't suppose a big problem for you.

Is it a bit more clear now?

**Comment by lindasato** [comment]
@cristinaelle, I agree with you. I thought it was a simple fix. We can let this go.

**Comment by lindasato** [comment]
@cristinaelle, I have just thought about this more. So, the issue of rounding off scores is minor and we can let it go, but Ignacio, mentions that adding the small score may be having more implications than we can see. @ifoche, are these potentially major problems or just minor ones? What's the trade off here?

**Comment by lindasato** [comment]
Hi @ifoche , circling back to this so that we find a solution to the first problem we were trying to go around. Is there a way to make "✓" or "X" appear next to a question in Improve Module even when the question is not scored? Please see screenshot for an example. The upper circled questions are not scored and consequently "✓" does not appear, the lower circled questions have scores assigned to them
 
![image 1](https://user-images.githubusercontent.com/26415203/49643168-0f77a280-fa26-11e8-99d5-bd8a38a24a91.jpg)
