### ISSUE TITLE
Collapse sections in improve module at tab level

### ISSUE THREAD

**Issue by lindasato** [EyeSeeTea/QAApp#308]
Is it possible to collapse the improve module at tab level (image 1) so that when you open, this is the default display? Right now, the default is all tabs and all sections are open (Image 2)

Image 1
![image 1](https://user-images.githubusercontent.com/26415203/46399798-76fd3300-c701-11e8-95cc-a88c53cbffff.jpg)

Image 2
![image 2](https://user-images.githubusercontent.com/26415203/46399811-7ebcd780-c701-11e8-892d-aa8332ab69cd.jpg)

**Comment by cristinaelle** [comment]
@ifoche : this has been reported as part of our 1.4 testing. Have you released a new version of 1.4 which has this issue fixed? If yes, which version is it?

**Comment by cristinaelle** [comment]
Please, release a 1.4 candidate in time for the upgrade to 2.30 with the collapsed tabs for the Improve module. 1.4.0 doesn't show all tabs collapsed in the Improve module.

**Comment by ifoche** [comment]
Taking care of this

**Comment by ifoche** [comment]
Following @rodmelia instructions related to the total amount of time that can be dedicated to the release, this task is not implemented and moved to future releases
