### ISSUE TITLE
Assess: Buggy display when Plan module is hidden

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#31]
Feedback from gtsmith@psi.org : This appears when a page loads when i have the plan module hidden

 [Link to buddybuild feedback from build 4](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56d0adb9e48b640100580f8e&bnum=4)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d057fac8f4aa010054eac5/3fb1bf47-8285-42b5-8016-bcbe776e64d3.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>SM-T217S</td></tr><tr><td>Screen size</td><td>600</td></tr><tr><td>Screen size</td><td>600px by 1024px</td></tr><tr><td>Battery</td><td>25% Unplugged</td></tr><tr><td>Memory free</td><td>172 MB / 1347 MB</td></tr></table>

**Comment by gtrsmith** [comment]
resolved
