### ISSUE TITLE
Prioritization matrix server-dependent

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#310]
+2, +4 +6 months by default
+1, +1, +6 months for ZW server

**Comment by cristinaelle** [comment]
Please, make sure that the prioritization matrix for the ZW server applies to the 2.30 zw server, too (https://clone-zw.hnqis.org). At the moment this server has the default matrix +2, +4, +6 months.

**Comment by ifoche** [comment]
Reviewing prioritization matrix

**Comment by ifoche** [comment]
Actually, this was a 1.3 task, so it's normal that 1.4 prioritization matrix is not different, as it was not introduced on 1.4. We will introduce also this in 1.4
