### ISSUE TITLE
URL from a dropdown menu in the login page with a subset of servers

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#311]
Drop-down menu for servers:
data.psi-mis.org
sfhnigeria.psi-mis.org
singapore-dev.psi-mis.org
zw.hnqis.org
clone.psi-mis.org
Others (text)
 
If others is selected then a textfield is displayed to enter the server

**Comment by cristinaelle** [comment]
Just saw that South Africa will have their own server, too: https://sfhza.psi-mis.org
In case you are able to include this in 1.4, let's change the milestone of this issue to 1.4.

**Comment by ifoche** [comment]
ok, we will introduce this on 1.4, then
