### ISSUE TITLE
Date DE failure

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#312]
Report from Esunly:
I wanted to ask for your help about an issue I have with a date question. I'm getting the error in the attached screenshot. I also notice that when I enter a date an then complete any other question, the date entered disappears.

I configured this data element with question type "DATE". Check data element configuration here:
https://data.psi-mis.org/dhis-web-maintenance/#/edit/dataElementSection/dataElement/avhtGYcxsfB?_k=mo970y

If you want to test it yourself you can use this credentials (not showing credentials) the in data server.

**Comment by esunly** [comment]
Hi Ignacio,

Any updates on this?

Many thanks,
Esunly

**Comment by cristinaelle** [comment]
Let's fix this for 1.4.

thanks,

cristina

**Comment by ifoche** [comment]
@cristinaelle I'm scheduling the next maintenance release. This issue we already found a solution and incorporated to 1.4, but we're not releasing yet waiting just in case there are other issues for 1.4 that have not yet been reported. Do you know if there are still tests coming and we need to wait for them in order to release a new version? Do you prefer us to release, let's say, early next week with the fix to this issue?

**Comment by cristinaelle** [comment]
hi! our data server is not in 2.30, so we can't release 1.4 until we upgrade to 2.30 (estimated date of update: Jan 27th). also, I know that there are some issues for 1.4 with the zw server (I have opened a freshdesk ticket for that) and esunly is taking care of those server-side. I hope this helps?

**Comment by cristinaelle** [comment]
a lot, tks!

**Comment by lindasato** [comment]
You can close this ticket. This is working
