### ISSUE TITLE
HNQIS 1.4 not working on clone-zw server

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#313]
Hi Ignacio,

Linda and I have been trying to test HNQIS in the clone.zw.hnqis.org server but the app crashes when we try to start a new survey from the assess module. We are able to start a survey from Plan but not Assess. Please see the video of what is happened here. 

We would like to thoroughly test the app with all the health areas but we can't do that because of this issue. 
Also, is the URL generated in the action plan supposed to work on this server?  We get this error when we click the link. 
Please let me know if you have any questions.

**Comment by cristinaelle** [comment]
Reported this in Freshdesk, so we can close this issue because it is not related to the app according to what Ignacio is saying.

**Comment by esunly** [comment]
Hi Ignacio,

When I click on the API link provided I can see the organisationUnitLevels well. If this is not the case for you, can you please send a screenshot? Can you also confirm which user are you using and if there are any specific users that need access to this endpoint?

Many thanks,
Esunly
