### ISSUE TITLE
1.4.2 - HNQIS server urls (log-in page and Action Plan)

### ISSUE THREAD

**Issue by lindasato** [EyeSeeTea/QAApp#318]
Hi @ifoche , in Myanmar server (https://myanmar.psi-mis.org), the URL for the shared action plan is available but on clicking the URL there is no assessment. Please see screenshot below. 

![blank](https://user-images.githubusercontent.com/26415203/54269972-6e056d00-458f-11e9-8a41-d55917db0a73.png)

**Comment by lindasato** [comment]
@ifoche , in addition to https://myanmar.psi-mis.org server, please make the change for https://im-dev.psi-mis.org too.

**Comment by cristinaelle** [comment]
@ifoche :@rodmelia : please, have a look at this.

**Comment by cristinaelle** [comment]
@ifoche : please, in the log-in page, can you include in the drop-down menu of url the following servers:
- https://myanmar.psi-mis.org
- https://im-dev.psi-mis.org
- https://ao.hnqis.org
- https://sm.hnqis.org
and remove:
- https://clone.zw.hnqis.org
- https://singapore-dev.psi-mis.org

@rodmelia : can you make the necessary changes to the Web App in order to parse (?) the correct url when the supervisor shares the Obs & Action Plan?

thanks,

cristina

**Comment by cristinaelle** [comment]
@ifoche : kindly note that there have been some changes in the list of urls: 

- ao-dev.hnqis.org
- so-dev.hnqis.org (from sm.hnqis.org to so-dev.hnqis.org because of geopolitics)

the other urls stay the same. 

thanks!

**Comment by cristinaelle** [comment]
@rodmelia and @ifoche : can you please follow up on the url generated when sharing the Obs & Action Plan for the servers zw.hnqis.org and myanmar.psi-mis.org? Users are saying HNQIS doesn't generate any url when they do assessments on those servers. thanks!

**Comment by cristinaelle** [comment]
@ifoche: This is a never ending conversation, sorry! 

**Final** list of servers we need on the log-in page:
https://data.psi-mis.org
https://ao-dev.hnqis.org
https://im-dev.psi-mis.org
https://jl-dev.hnqis.org
https://myanmar.psi-mis.org
http://sfhza.psi-mis.org 
https://sm-dev.hnqis.org
https://zw.hnqis.org

Can we have this as a silent release at some point next week, please?

Best,

cristina

**Comment by lindasato** [comment]
@cristinaelle , please confirm if sfhnigeria should be removed from the list of servers in 1.5.0

**Comment by cristinaelle** [comment]
@lindasato: yes, to remove. The final list of server urls doesn't include sfhnigeria

@ifoche: kindly note that I have removed jl-dev.hnqis.org from the list. 

cristina

**Comment by lindasato** [comment]
@ifoche : kindly correct Angola and Somaliland server names. They are both missing "**-dev**"
-should be https://sm-dev.hnqis.org
-should be https://ao-dev.hnqis.org

**Comment by cristinaelle** [comment]
@ifoche: can we have this in 1.4.7? The version you are going to publish after we test 1.4.6?

**Comment by cristinaelle** [comment]
@ifoche : one more server to add to the drop-down menu in the login page:
https://imdatahub.org

thanks a lot! :)

cristina

**Comment by rodmelia** [comment]
Updated list to be added initially in 1.4.2a, and later as a POeditor field on 1.5:
(please keep the order)

https://data.psi-mis.org
https://ao-dev.hnqis.org
https://im-dev.psi-mis.orghttps://imdatahub.org - URL not working on Nov 25, but it will soon.
https://myanmar.psi-mis.org
http://sfhza.psi-mis.org
https://sm-dev.hnqis.org
https://zw.hnqis.org

**Comment by ifoche** [comment]
Rodolfo and Ignacio: please, release 1.4.8 with the amended url for sfhza (https instead of http: https://sfhza.psi-mis.org), remove the dev server for IM (https://im-dev.psi-mis.org) and keep the prod server, only, for IM (https://imdatahub.org).
