### ISSUE TITLE
Improve: Android tab navigation with Plan module is hidden

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#32]
Feedback from gtsmith@psi.org : Switching to the improve module when the plan module is hidden takes up to 5 seconds to load the improve module. Can we improve? 

 [Link to buddybuild feedback from build 4](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56d0ae1f355eae0100bed3a0&bnum=4)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d057fac8f4aa010054eac5/c35bc92b-6759-48ba-8f8d-6f3e1b232d4a.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>SM-T217S</td></tr><tr><td>Screen size</td><td>600</td></tr><tr><td>Screen size</td><td>600px by 1024px</td></tr><tr><td>Battery</td><td>25% Unplugged</td></tr><tr><td>Memory free</td><td>166 MB / 1347 MB</td></tr></table>

**Comment by gtrsmith** [comment]
This is resolved - thanks!
