### ISSUE TITLE
Limiting selection to one option for questions with multiple choices

### ISSUE THREAD

**Issue by lindasato** [EyeSeeTea/QAApp#320]
We have checklists with multiple choice options where only one answer should be selected as "Yes". We are getting a lot of user errors where the users are selecting more than one "Yes" for such questions. Is it possible to gray out/or block the rest of the options once one answer has been selected as "Yes" for such set of questions? For this to work, we also need the app to allow partial scoring of questions e.g 0.33 (numerator) out of a possible 1 mark (denominator). Please see image for example.
![image](https://user-images.githubusercontent.com/26415203/55403532-b4caff00-555e-11e9-885d-70c9df294d7d.png)

**Comment by ifoche** [comment]
@lindasato currently there's no mutually exclusive behaviour in HNQIS for multiple options. If I've properly understood, what you want to do is to limit to one the number of answers that you can provide to a group of Yes/No. Is this still valid?

**Comment by cristinaelle** [comment]
very valid, yes! thanks! any chance we can implement this for 1.5.X?
