### ISSUE TITLE
Settings not loading in 1.4.2

### ISSUE THREAD

**Issue by emedinaBAO** [EyeSeeTea/QAApp#322]
<img width="532" alt="Screenshot 2019-07-22 at 14 48 01" src="https://user-images.githubusercontent.com/31136796/61639517-931f9000-ac93-11e9-9fef-cab9eed272a5.png">
Hi Ignacio,

I've tried to see the settings page in 1.4.2  (both in my tablet and in Genymotion) and it doesn't load. I was trying to enable the developers mode and also to be able to import databases into the app. Is this a known issue? Can you please help troubleshoot?

Many thanks,
Esunly

**Comment by ifoche** [comment]
Dear @emedinaBAO, could you please share also the Android version you're using for us to replicate it?

Thanks!

**Comment by emedinaBAO** [comment]
Hi @ifoche, the Android version I'm using in my tablet is 7.0. But I also tried with 5.1 in Genymotion.

Many thanks,
Esunly

**Comment by ifoche** [comment]
Thank you for that, we're investigating it

**Comment by ifoche** [comment]
@emedinaBAO we're not able to replicate the issue and tested already in a tablet with Android 7, and also in emulators...is there anything else you could tell me so we can replicate the issue?

**Comment by emedinaBAO** [comment]
@ifoche Thanks so much for looking into it! So settings are working well from your end (for the current version in gPlay)? Another colleague and I are having the same issue. Can you advice on how to sort this out?

**Comment by cristinaelle** [comment]
Hi @ifoche,

Kindly note that there are several users from Ghana who are reporting the same issue. Janet is in Ghana training 40+ supervisors from the MoH on the use of HNQIS and most of them have reported this issue, as well. Unfortunately, from my side, I cannot replicate this issue.
We appreciate your investigation. I have asked Janet to tell me what type of devices the users have, as well as the Android version. Will let you know. 

Best,

Ccing @emedinaBAO

**Comment by esunly** [comment]
Hi @ifoche,

Any updates on this issue? We need to use the settings menu to be able to see developers mode and import database files so this is really important for us.

Many thanks,
Esunly

**Comment by esunly** [comment]
Hi @ifoche!

Can you please let me know if there is any progress with this? Any ideas on what might be causing this problem?

Many thanks,
Esunly

**Comment by lindasato** [comment]
@ifoche and @esunly , James, one of our new team members just figured this out. If you change the font size in the device to large, the settings appear. Sadly, the issue reverses when you change back the font size to small. Some of the devices we have seen this include:
-Samsung galaxy tab A (SM-P555), Android version, 7.1.1
-Samsung galaxy tab A (SM-T555), Android version, 7.1.1
I hope this is useful. In case you need info on more devices, let me know and I can try to find out from more users.

**Comment by esunly** [comment]
Thanks for looking into this @lindasato!

I tried what you said but it's not working for me. I have a Samsung galaxy tab A (2016)  (SM-T585), Android version, 7.0.

Can you please specify the steps your team member followed? 

Many thanks,
Esunly

**Comment by lindasato** [comment]
@emedinaBAO , there is really no formula. For us it works when we simply change the font size in the device settings, then when you go to the app the settings page is populated. The order of steps (whether you go to app first, then go back to change font or the other way round) doesn't produce different results.

**Comment by esunly** [comment]
Hi @ifoche 

Can you please clarify if this issue is related with the HNQIS app or with the tablet itself? If related with the app, can this be fixed?

Many thanks,
Esunly
