### ISSUE TITLE
Control Data Elements

### ISSUE THREAD

**Issue by rodmelia** [EyeSeeTea/QAApp#33]
_CreatedBy
_CreatedOn
_UploadBy
_UploadOn

**Comment by rodmelia** [comment]
@ifoche - these are the control data elements that we discussed yesterday, that we want to include. Contrary to what I said, I would like them in H14/v1.0.0, rather than to wait for H15 (v1.1.N): 
_CreatedOn should be the date that the Survey was added (i.e. the '+' button was pressed). That should be the same value used for 'Event Date', which is used for anaytics
_UploadedOn is the date the push happens
_CreatedBy and _UploadedBy are the Name of the supervisor. 
@josemp10 - We need to add these control data elements to all surveys.

Last, the correct names are:
_Created by
_Created on
_Uploaded by
_Uploaded on

**Comment by gtrsmith** [comment]
I dont see these control DEs in the HNQIS programs. Can someone else confirm whether or not this ticket is addressed?

**Comment by josemp10** [comment]
It is done. I forgot to include them in the hnqis server. They should be ok now

**Comment by ifoche** [comment]
I had included the dataElements myself in the development server for the testing last week, please @josemp10 please check the dataElements there to be sure that you're using the same code/configuration we're using in the development. We had already checked in the development server as you can see in the attached images. 
- The CreatedOn and UpdatedOn DEs are date type DE. The app send them and during the pull if it cannot find them, it assumes eventDate as the creation and completion date (to avoid crashes)
- The CreatedBy and UpdatedBy DEs are text type DE. They store the UUID of the user.

![controlde4](https://cloud.githubusercontent.com/assets/10931645/14135069/75cc7096-f65b-11e5-8981-ce0d2874e330.png)

![controlde3](https://cloud.githubusercontent.com/assets/10931645/14135077/82a4c9b2-f65b-11e5-9dc6-90dde20e9bdb.png)

![controlde2](https://cloud.githubusercontent.com/assets/10931645/14135080/87ae14ae-f65b-11e5-9732-238a07a44eeb.png)

![controlde1](https://cloud.githubusercontent.com/assets/10931645/14135082/8c8d3d10-f65b-11e5-9ae4-d6a852652572.png)
