### ISSUE TITLE
Somalian app crashing on Assess module

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#330]
Report from Esunly:

The Somaliland is finding some issues with the app. It is very weird but if we start a survey for from the Plan module the app works well but if I try the same survey and facility from the Assess module, the app crashes. I reviewed the users settings and the orgunits and I found everything well. Can you kindly help troubleshoot? These are the details:

- Server:  https://sm-dev.hnqis.org
- User Credentials: in separate email
- App version 1.4.2

**Comment by ifoche** [comment]
The app needs the user to have access to the OU levels any OU he's assigned to belongs. In this case, there's a level 6 that the user cannot see through the API but the OUs are assigned to that level. That's not important for creating a survey via the plan module, but the Assess needs to read the OU levels.

https://sm-dev.hnqis.org/api/organizationUnits/UVsWsU6MWJQ
https://sm-dev.hnqis.org/api/organizationUnits/lBul4KtUSbH
https://sm-dev.hnqis.org/api/organizationUnits/rHeWgOGqWwV
https://sm-dev.hnqis.org/api/organizationUnits/QYd0dIk9W8i
https://sm-dev.hnqis.org/api/organizationUnits/wlckuIlWLTH
https://sm-dev.hnqis.org/api/organizationUnits/cZfuhIqzIpe
https://sm-dev.hnqis.org/api/organizationUnits/obWFZbhVTxR
https://sm-dev.hnqis.org/api/organisationUnitLevels

So look like just a configuration issue

It was already reported not very long time ago. Please check this issue:
https://github.com/EyeSeeTea/QAApp/issues/329

**Comment by esunly** [comment]
Hi @ifoche!

Thanks so much for looking into it. I fixed the OU levels and tested. everything is working well from my end. You can close this issue.

Many thanks,
Esunly
