### ISSUE TITLE
1.4.2: Unable to share action plan from ao-dev.hnqis.org

### ISSUE THREAD

**Issue by lindasato** [EyeSeeTea/QAApp#331]
Unable to share an action plan from Angola's app, instead, the app bounces to Plan module or out of the app.

**Comment by cristinaelle** [comment]
@ifoche : to replicate this bug, use:
https://ao-dev.hnqis.org
AOdemo1;Angolademo1!

cristina

**Comment by lindasato** [comment]
Hi @ifoche , see below the recording of how it happens
[AO-Action plan bug.pptx](https://github.com/EyeSeeTea/QAApp/files/3868457/AO-Action.plan.bug.pptx)
