### ISSUE TITLE
1.5.1 - Random Crashing Behavior

### ISSUE THREAD

**Issue by lindasato** [EyeSeeTea/QAApp#335]
1.5.1 is crashing quite a bit. This is random, it could be just after loading the app and you want to log in, or within the app when moving from one module to another or when you want to start conducting an assessment after selecting the HA and Org Unit. We have experienced this on 4 different devices and different servers. The other versions of the app, 1.4.2 and 1.4.6 are not exhibiting this behavior while testing under the same conditions.

**Comment by ifoche** [comment]
We've not been able to reproduce it. The only one we've seen is when one pointed in the issue #338 . Could you please try to narrow a bit the scenario to replicate it? We have the feeling that we can spend much time trying and we prefer to do it when we will have something more specific  if you don't mind

**Comment by lindasato** [comment]
Hi Ignacio. This is quite random and we can't tell what triggers it. We have seen this when testing on tablets and phones. Janet says it doesn't crash when using an emulator. I have emailed you some sample recordings of the crash behavior.
