### ISSUE TITLE
1.5.1 - Action plans wiped out in improve and monitor modules after refreshing metadata

### ISSUE THREAD

**Issue by lindasato** [EyeSeeTea/QAApp#339]
The issue of action plans being wiped out when metadata is refreshed is not new, please see issue # 263. But now it is critical to have this working. It will not be possible to track completion status of action plans if there is nothing to look at in the app if for any reason the users need to refresh metadata or logout the log back into the app.

**Comment by ifoche** [comment]
Hi @lindasato . Actually, Obs&Action plans were not being taken with the pull in HNQIS, so it would be a matter of implementing the functionality from zero. This might be a minor maintenance task or more complicated, but we need to investigate and provide you and estimate of how long would it take.

**Comment by cristinaelle** [comment]
@ifoche : please, go ahead and investigate how long this will take in terms of LoE (and hence budget). 

thanks!

ccing @lindasato
