### ISSUE TITLE
Assess: End of tab display

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#34]
Feedback from clussiana@psi.org : End of tab is repeated. Remove one, please.

 [Link to buddybuild feedback from build 4](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56d46068c90c7b010061ed9e&bnum=4)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d057fac8f4aa010054eac5/85c34088-a01e-4ce4-8391-86a88e7a905e.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>45% Unplugged</td></tr><tr><td>Memory free</td><td>175 MB / 1376 MB</td></tr></table>

**Comment by gtrsmith** [comment]
This is a content modification I can work on. No need to address technically

**Comment by rodmelia** [comment]
@gtrsmith - perhaps you can mark this one as 'Done" ?
