### ISSUE TITLE
1.4.2 and 1.5.1 - Mass Reschedule takes very long to load

### ISSUE THREAD

**Issue by lindasato** [EyeSeeTea/QAApp#342]
The mass reschedule feature at times takes very long to load, up to even 10 minutes. This is random, with different devices. The internet connection during the initial pull is very strong since all videos loaded without a delay.

**Comment by ifoche** [comment]
Hi @lindasato is there anything else you could tell us to replicate the issue? We've not been able to replicate the problem. If the problem's happening, does it help if you change to another tab and back again to the planning one? or does it continue slow loading?

**Comment by lindasato** [comment]
Hi @ifoche, sadly we can't see a pattern on this. It is very random. At times changing tabs fixes it but in most cases it doesn't. Then at times it works just fine. Janet has just mentioned to me that this is not an issue in 1.5.1 only and she has seen this behavior when conducting trainings on 1.4.2 also.

**Comment by ifoche** [comment]
oh...ok...then maybe it's not an issue on 1.4.6 either? Because we're testing there and there has been some improvements in 1.4.6 in the way lists are displayed...maybe that's the point?

**Comment by cristinaelle** [comment]
@lindasato: to review this before our meeting tomorrow, tks.

**Comment by lindasato** [comment]
I have done several tests on 1.4.6, not seen the issue.

**Comment by ifoche** [comment]
closing the issue given it was not replicable
