### ISSUE TITLE
Sharing URL with duplicated headings

### ISSUE THREAD

**Issue by esunly** [EyeSeeTea/QAApp#345]
Hi @ifoche,

Several users have reporting issues with the format of the surveys provided by the link created when clicking the sharing symbol (in the Action Plan page). The headings and numbering is being repeated several times.

Is this due to a bug in the app or is this something we can sort out somehow?

Many thanks,
Esunly
![Screenshot 2019-11-13 at 18 38 02](https://user-images.githubusercontent.com/8968736/68789212-5104ca80-0645-11ea-9177-51f027c0fa61.png)

**Comment by ifoche** [comment]
@esunly I leave @rodmelia to answer, as it looks like a server-side problem

**Comment by cristinaelle** [comment]
@rodmelia : can you please look into this? I also think it'll be nice to tackle issue https://github.com/EyeSeeTea/QAApp/issues/288 
The point is that we need the server url to work from the sharing Obs & Action plan with all servers, as they are typed in / selected in the log-in page.
