### ISSUE TITLE
Assess: Confirmation of delete assessment

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#35]
Feedback from clussiana@psi.org : Make sure there's a confirmation question before deleting an assessment. Something like: "Are you sure you wanna delete this assessment?"

 [Link to buddybuild feedback from build 4](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56d460f30c02fc010018ebb1&bnum=4)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d057fac8f4aa010054eac5/25c8c98e-f665-496b-acdf-b97e3fff9de1.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>44% Unplugged</td></tr><tr><td>Memory free</td><td>193 MB / 1376 MB</td></tr></table>

**Comment by gtrsmith** [comment]
resolved
