### ISSUE TITLE
1.5.2: Incorrect Date in Monitor Module

### ISSUE THREAD

**Issue by lindasato** [EyeSeeTea/QAApp#353]
In the Monitor module, the date of the **next QA** visit is incorrect because it reports the date when the assessment was conducted instead of the date of the next visit. (the date in the red box)

![Incorrect Date in Monitor module-action plan](https://user-images.githubusercontent.com/26415203/73660158-b1d1fb00-46a8-11ea-8ce1-8a8bfba2a9b6.png)

**Comment by ifoche** [comment]
Dear @lindasato , could you please share your DB and clarify which version of the app you're using? Thank you!

**Comment by lindasato** [comment]
Dear @ifoche , this is on version 1.5.2. I have just conducted an assessment for Hypertension (score of 60%, competency class: Not competent) and exported the DB to you on nacho@eyeseetea.com

**Comment by nancyespinoza** [comment]
fixed in 1.5.3
