### ISSUE TITLE
1.5.3- Update action plan external link with missing sections

### ISSUE THREAD

**Issue by nancyespinoza** [EyeSeeTea/QAApp#355]
| Description  |
| ------------- | 
| Gaps and Action plan as reported in the url shared from the Improve module are blank. Can we have the action plans, responsible and due date populate? The gaps (questions failed) can be seen in the full assessment so we don’t need this. Also, the browser tab still says HNQIS IMCI for all health areas. We would like it to reflect the correct name for each health area, please|
|<ul><li>server:https://clone.psi-mis.org/</li><li>User:KEdemo1</li></ul>|

| How to replicate |
| ------------- | 
|<ul><li>In the action plan screen, share a completed action plan.</li><li>In the message received (email for example) open the external link.</li></ul>|

| Example |
| ------------- | 
|![External link](https://user-images.githubusercontent.com/44774809/76258057-77fc9300-6218-11ea-8cdb-5e3f04aa1ef2.gif) |

**Comment by ifoche** [comment]
This is server-side so I leave the answer to @rodmelia

**Comment by rodmelia** [comment]
The web page has not been updated. Can you confirm that the only elements that we need to update are:
1. actions,
2. responsible
3. due date
Also, we should update the title of the browser window. -.

There is a much nicer design that it is on the to do list for the workforce app.

**Comment by cristinaelle** [comment]
hi @rodmelia: I am confirming with Janet what we want to have here. I'd say:
- Change the title of the browser window
- Report the Competency Class at the bottom (before Overall QA Score)
- Delete current Gaps and Action Plan
- Create Action - Responsible - Due date times 3.

**Comment by rodmelia** [comment]
@nancyespinoza - could you please confirm that this is still a valid issue?

**Comment by nancyespinoza** [comment]
@rodmelia 
The issue remains in the previous version of the app:
https://apps.psi-mis.org/hnqis/feedback?eventId=QJPo13MbUJ1&server=https://data.psi-mis.org/

But no longer in the dev one
https://apps.psi-mis.org/hnqis-dev/feedback?eventId=QJPo13MbUJ1&server=https://data.psi-mis.org/

**Comment by ifoche** [comment]
thanks @nancyespinoza closing the issue according to your comment
