### ISSUE TITLE
1.6.0 Competency classes: wrong classification when all of the non-critical questions were unanswered.

### ISSUE THREAD

**Issue by nancyespinoza** [EyeSeeTea/QAApp#362]
| Description  |
| ------------- | 
| Expected behavior: <li>All critical steps and (≥ 89.9% non-critical steps correct or none of the non-critical steps anwered) = Competent</li> |
| Actual behavior: <li>All critical steps and none of the non-critical steps anwered = Not Competent</li> |
|<ul><li>server:https://data.psi-mis.org/</li><li>User:KEdemo1</li></ul>|

| How to replicate |
| ------------- | 
|<ul><li>In the assess module, open the survey "KE HNQIS Hypertension"</li><li>Only answer critical questions (*)</li><li>Complete the assessment</li><li>Go to Feedback module and check the competency class</li></ul>|

| Video  |
| ------------- | 
|![20200915105637](https://user-images.githubusercontent.com/44774809/93241107-27736e80-f742-11ea-8963-acb3cdad58af.gif)|

**Comment by ifoche** [comment]
Hi @nancyespinoza, I have the impression that this might be a misunderstanding in how each classification method should work. Could you please share the 2 matrix of classifications you are using for validation? (A/B/C and C/CNI/NC)

**Comment by nancyespinoza** [comment]
|A/B/C| Score|
|--|--|
|A| Critical questions between 90%-100%| 
|B| Crtical questions between 80% -89%|
|C| Critical questions between 0%-79%|

|C/CNI/NC| Score|
|-- | --|
|Competent | All critical questions correct AND (≥ 89.9% non critical questions correct OR none of the non-critical steps were answered)|
|Competent but needs improvement | All critical questions correct AND between 79.9% and < 89.9% non-critical questions correct|
|Not competent | Any critical questions missed OR below 79.9% of non-critical questions correct|

**Comment by nancyespinoza** [comment]
Fix in 1.6.1
