### ISSUE TITLE
1.6.0 Only in the first login - The app does not show the monitor Incomplete/Complete Actions screen

### ISSUE THREAD

**Issue by nancyespinoza** [EyeSeeTea/QAApp#364]
| Description  |
| ------------- | 
|  'Monitor module' in blank the first time user clicks on it|
|<ul><li>server:https://data.psi-mis.org/</li><li>User:KEdemo1</li></ul>|

| How to replicate |
| ------------- | 
|<ul><li>Log in</li><li>Go to monitor module</li></ul>|

| Video  |
| ------------- | 
|![20200915111759](https://user-images.githubusercontent.com/44774809/93243218-22fc8500-f745-11ea-9e66-1d726352f26a.gif)|

**Comment by ifoche** [comment]
Please @nancyespinoza could you provide us with the Android version and device you are using? Thanks!

**Comment by nancyespinoza** [comment]
Device specifications:
Android 6.0.1, Model SM-N910H

**Comment by ifoche** [comment]
@nancyespinoza could you re-test with the new release. Some modifications have been done to the layout, and we're unable to replicate the issue

**Comment by nancyespinoza** [comment]
Fix in 1.6.1
