### ISSUE TITLE
I don't see a vidéo 

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/QAApp#368]
## User Report
I don't see a video

## ScreenShot
![file](https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/android_screenshot1290158755865702583.jpg)
## Device Info
```
Time Stamp: 2020-10-06T07:05:41 UTC
App Version: 1.6.1 (64)
Install Source: Package Installer
Android Version: 9 (28)
Device Manufacturer: SAMSUNG
Device Model: SM-G950W
Display Resolution: 2058x1080
Display Density (Actual): 540dpi
Display Density (Bucket) Unknown
---------------------

```

**Comment by rodmelia** [comment]
@nancyespinoza  - is this still valid ?

**Comment by nancyespinoza** [comment]
It looks like this is not happening for all the devices. For example, I replicated it with android 11 (Pixel 2) but not with an android 9 (Samsung note 8)

**Comment by ifoche** [comment]
ok @nancyespinoza thanks for reporting. Our first guest is that it will probably more related to the Android version than the device itself. We will have a look and let you know asap.

**Comment by ifoche** [comment]
It looks like it would require the upgrade release that we discussed some time ago with @rodmelia . We move it to backlog so you can decide how to proceed with that release, or maybe higher levels of Android don't need to be covered for videos right now.
