### ISSUE TITLE
1.6.4 Unable to login to https://sm-dev.hnqis.org/

### ISSUE THREAD

**Issue by nancyespinoza** [EyeSeeTea/QAApp#371]
All the following users have the expected authorities and are able to login using 1.6.3:

- JLdemo1 (Jubalanddemo1!)
- PLdemo1 (Puntlanddemo1!)
- SMdemo1 (Somalilanddemo1!)

With 1.6.4 the app never stops loading. If you exit and re-open the app, the user is able to login but the lists are not shown.

**Comment by nancyespinoza** [comment]
Hi @ifoche, 

One question, the app looks for the authority or for the ID of the role?

**Comment by nancyespinoza** [comment]
HI @ifoche, 

Is this a possible bug to fix in the next version? 

Thank you

**Comment by ifoche** [comment]
oh, I missed this one, I'll let you know about it on Monday
