### ISSUE TITLE
1.6.4 Question - videos in action plan

### ISSUE THREAD

**Issue by nancyespinoza** [EyeSeeTea/QAApp#373]
1. Should the videos appear in the action plan, it make it look that they have a correct-incorrect answer. How does a question end up in the action plan?
![Screenshot_20210218-160452](https://user-images.githubusercontent.com/44774809/108427665-25d33880-7203-11eb-8e1a-932a0c38809e.png)

**Comment by ifoche** [comment]
Videos have never been represented in the action plan, they only appear in the feedback. So in case we want it, it would be a new feature. Do you need us to estimate that?

**Comment by nancyespinoza** [comment]
Hi Ignacio!
Then is it a bug? We were wondering why the action plan is showing the titles of the videos in the "non-critical steps missed". 

Thanks for your help

**Comment by ifoche** [comment]
The feedback and the non-critical steps missed should only be reading the DE type Composite Scores. I guess there are DEs of that type with that name in the program? Could that be the case?
