### ISSUE TITLE
Should Pie chart labels change according to the server?

### ISSUE THREAD

**Issue by nancyespinoza** [EyeSeeTea/QAApp#378]
I have noticed that if the server allows to use competency the monitor module change the labels to C, CNI and NC but in the pie chart it keeps A(C), B(CNI), C(NC). Is this the expected behavior or should the app display only the competency labels?

**Comment by ifoche** [comment]
@nancyespinoza Right now it is like that, but we could change the label into only C, CNI and NC if that looks better for you

**Comment by nancyespinoza** [comment]
Hi @ifoche! Thank you for your quick response. After discussing with Rodolfo, yes we should change the labels but make it dynamic. When the server allows competency class, show C, CNI and NC and if the server is working with the ABC scoring then show A, B, and C.
