### ISSUE TITLE
Demo Mode for HNQIS

### ISSUE THREAD

**Issue by rodmelia** [EyeSeeTea/QAApp#38]
There are many users that just want to show or play with the app. After downloading the app, on the login page, we need to offer a demo mode (bypassing the login)

The demo mode need both, metadata, and data. The data will need to be readjusted so get records assigned across the 4 sections of the planning: Never Assessed, Overdue, Next 30 days, Future
- How do I add an image?

**Comment by rodmelia** [comment]
The demo mode need both, metadata, and data. The data will need to be readjusted so get records assigned across the 4 sections of the planning: Never Assessed, Overdue, Next 30 days, Future.

**Comment by cristinaelle** [comment]
This has been done - we have a Demo feature of HNQIS with no need to log-in.
