### ISSUE TITLE
Metadata Download UI

### ISSUE THREAD

**Issue by rodmelia** [EyeSeeTea/QAApp#39]
1. Can we replace the DHIS logo for our own custom logo?
2. Can we give more information during the download process? 
3. downloading Cervical Cancel Program
4. downloading XXXX Program
5. donwloading Org Units for User xxxx

![screen shot 2016-03-01 at 11 25 07](https://cloud.githubusercontent.com/assets/17068010/13435174/e5e3cfc4-dfd0-11e5-8245-cb429ba75054.png)

**Comment by ifoche** [comment]
which logo would you think that is better? We will include a little bit more detail in the download process, yes

**Comment by ifoche** [comment]
I edited my last comment, so you'll be able to read it just in the waffle website, just in case you're reading it from the email

**Comment by cristinaelle** [comment]
I suggest including the HNQIS logo and the name of the country/franchise where it's being used. It will increase the buy-in from country teams and supervisors.

**Comment by ifoche** [comment]
Ok, from the app point of view there's no country differentiation. I mean, the app is the same for all the countries, but maybe we can think about having a default logo (the one we're using now?) and another logo stored somewhere in the DHIS2 server, so we can download it first and then show it. That way, we wouldn't have a different app for each country (which is harder to maintain) but we would be having what you're proposing...does it sounds good for you?

**Comment by cristinaelle** [comment]
Yes, it does! Thanks! So, let's go ahead with the HNQIS logo type and very small the PSI's one? This last shouldn't be too big because each country has a own logo and this might differ from the PSI's one.

**Comment by ifoche** [comment]
Hi @cristinaelle, I'm talking to @rodmelia and apparently this is something that has a very low priority and must be moved to somewhere in the future (H16, H17 and so...). Just wanted to inform you and introduce @rodmelia in the conversation so you can talk about it

**Comment by cristinaelle** [comment]
Closing because this has been done for 1.3.
