### ISSUE TITLE
HNQIS 1.6 not syncing in Alcatel 3T8

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#390]

**Comment by ifoche** [comment]
@nancyespinoza copying here the description of the problem:
"Hace unos días nos llegó un ticket de un chico de Angola que nos comentaba que tenía ciertas tablets que no estaban sincronizando correctamente (alrededor de unas 30). El equipo ha hecho varias pruebas y ya descartamos que sea un problema de configuración de programa o usuario. Lo que nos lleva a preguntarnos si existe alguna posibilidad que el problema provenga directamente del modelo de las tablets o incluso alguna configuración dentro de las mismas. Te comparto el modelo y versión de Android por si puedes ayudarnos a entender qué pudiese estar pasando. 

Alcatel 3T8, Modelo: 9032x, Android v10

También te comento que han probado con el nuevo apk, pensando en que pudiese ser una incompatibilidad con Android10 pero los dispositivos siguen sin poder sincronizar. "

Could you please describe what means that they cannot sync? Is it that they cannot login because the initial sync is not working?

If they could login with the latest version, then we can look for their crashes in crashlytics. Could you please take note of the time of the tests and let me know so we can look for it in crashlytics?

Thanks!

**Comment by nancyespinoza** [comment]
Hi Ignacio. 

They are able to login but once they complete an assessment, the app never push the data into the server. 

They tested the new apk yesterday (7th)  in two different servers using the "AOdemo1" user
1. https://old-dev.psi-mis.org/
2. https://ao-dev.hnqis.org/

**Comment by rodmelia** [comment]
Hi Nancy - is there an update on this one?

R

**Comment by ifoche** [comment]
@nancyespinoza if they are being able to login, then they should be able to enter the settings, activate the developers options and export their database. Could you please ask them to do it and send us those DBs?
