### ISSUE TITLE
[1.7] Unable to select Org Unit

### ISSUE THREAD

**Issue by nancyespinoza** [EyeSeeTea/QAApp#399]
**Credentials**
URL: https://staging.psi-mis.org/
User: BIdemo1
Password: Burundidemo1!

**Steps to replicate**
1. Login
2. In any of the tabs (except from the assessment one) check the OU filter. Test BI_ is available
<img width="236" alt="image" src="https://github.com/EyeSeeTea/QAApp/assets/44774809/9bdf4173-e77f-4b6a-ae68-bc696d62c5f0">

3. Create a new assessment - OU is not available
<img width="262" alt="image" src="https://github.com/EyeSeeTea/QAApp/assets/44774809/b0ce153c-f141-40a6-b998-e0fabd7d0b55">

**Comment by ifoche** [comment]
Sorry @nancyespinoza for not writing before. With the last version of the app at least we cannot replicate this issue, so we are wondering if you could please test with the release that we just generated in case that you can replicate this error.

Thank you!
