### ISSUE TITLE
Assess: Status message

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#41]
Feedback from gtsmith@psi.org : There needs to be a status message when an assessment is sent or marked as completed. Otherwise users will question what happened with their data. 

 [Link to buddybuild feedback from build 4](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56d5a92dbb9631010054d297&bnum=4)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d057fac8f4aa010054eac5/27c7bd95-c163-4c82-a8e6-467e512cda49.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>SM-T217S</td></tr><tr><td>Screen size</td><td>600</td></tr><tr><td>Screen size</td><td>600px by 1024px</td></tr><tr><td>Battery</td><td>24% Unplugged</td></tr><tr><td>Memory free</td><td>435 MB / 1347 MB</td></tr></table>

**Comment by ifoche** [comment]
We put an asterisk to identify those surveys that are not yet sent to the server as you told us. Do you think that we need to change that to a different system?

**Comment by gtrsmith** [comment]
Resolved
