### ISSUE TITLE
Improve: sort order

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#42]
Feedback from gtsmith@psi.org : What is the default sort here? We need to discuss

 [Link to buddybuild feedback from build 4](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56d5a96c946ed50100e60691&bnum=4)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d057fac8f4aa010054eac5/1ed3004b-d77e-4eff-b172-964a505d60f8.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>SM-T217S</td></tr><tr><td>Screen size</td><td>600</td></tr><tr><td>Screen size</td><td>600px by 1024px</td></tr><tr><td>Battery</td><td>24% Unplugged</td></tr><tr><td>Memory free</td><td>406 MB / 1347 MB</td></tr></table>

**Comment by gtrsmith** [comment]
This needs to be discussed further and can be done after the pilot in Kenya. We will identify solutions at a later stage. This is a low priority for the time being.

**Comment by cristinaelle** [comment]
Closing this because with the new features of 1.3, the order is the completion date.
