### ISSUE TITLE
Monitoring Section: pie colors

### ISSUE THREAD

**Issue by rodmelia** [EyeSeeTea/QAApp#46]
Please update the colors for the pie as follow:
A: keep the current green
B: use yellow (same as in planning module)
C: use red (same as in planning module)
![screen shot 2016-03-01 at 18 53 51](https://cloud.githubusercontent.com/assets/17068010/13438105/75f5f052-dfdf-11e5-9bdc-a5162adb2341.png)

**Comment by gtrsmith** [comment]
resolved
