### ISSUE TITLE
Planning module: re-scheduling should NOT require a comment.

### ISSUE THREAD

**Issue by gtrsmith** [EyeSeeTea/QAApp#47]
I am unable to click 'ok' when trying to submit a comment in the date selector. I can click 'ok' if i change the date, but not if I only submit a comment
![screenshot_2016-03-01-12-31-07](https://cloud.githubusercontent.com/assets/14224713/13439311/2aa91208-dfaa-11e5-9346-1f5ea35dfade.png)

**Comment by ifoche** [comment]
I'm not understanding the problem very well. If you don't change the date, you're not rescheduling the task, so I think it is ok if it doesn't allows you...is not that the behaviour your were expecting?

**Comment by ifoche** [comment]
Rodolfo and I discussed about it, and we think that we have to talk a little bit more about how this dialog works and, if needed, redesign it.

**Comment by cristinaelle** [comment]
The supervisors want to be able to interact with the Plan module more: they want for example to leave a comment if the facility is closed or if the provider is not there, on the date of the scheduled visit.

**Comment by rodmelia** [comment]
Let's remove the requirement to make a comment.

**Comment by gtrsmith** [comment]
The comment requirement is removed, but I can still not submit a comment without opening the date selector. This is now a low priority though.

**Comment by rodmelia** [comment]
I not Ignacio removed the requirement of a comment, but perhaps it didn't add it to the last build.
@ifoche - don't forget to also remove the '*' next to the comment

**Comment by rodmelia** [comment]
I meant: I know that ignacio removed the comment being a mandatory field. I've marked this H14.

**Comment by rodmelia** [comment]
We need to redesign this for h15

**Comment by ifoche** [comment]
shouldn't we  move this to H15? (as we're redesigning it)

**Comment by rodmelia** [comment]
For H14, all we want is to make sure that you can submit a new date, with no comment. I will take care of creating a new waffle card for H15, which will incorporate new functionality to see previous dates and comments.

**Comment by gtrsmith** [comment]
if all this ticket needs to resolve is ability to create a new data without including a comment, this is closed.

**Comment by ifoche** [comment]
yes, in principle this was just for that. I suppose that we need more background discussion about what you really think that's needed. Maybe you were thinking on submitting comments to a survey, just like in waffle, as a sort of messaging system between the supervisor and the people managing the server. I think there's another waffle card for that.
