### ISSUE TITLE
Plan module: Org Unit navigation

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#49]
Feedback from gtsmith@psi.org : I assigned this user (gdemoKE) to just 14 org units and the app became immediately difficult to navigate,  with 107 assessments in the never assessed accordion.  We need to think through how to improve the ux for this.  I have some ideas but am not sure how complicated they are to implement. Am submitting this to document the issue 

 [Link to buddybuild feedback from build 5](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56d63822cf234501007e1faa&bnum=5)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d5ef0e1a3dd001003f70d7/9cb4a1d2-4d04-48c4-a865-66bec2288d6e.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>5</td></tr><tr><td>Device type</td><td>SM-T217S</td></tr><tr><td>Screen size</td><td>600</td></tr><tr><td>Screen size</td><td>600px by 1024px</td></tr><tr><td>Battery</td><td>81% Charging</td></tr><tr><td>Memory free</td><td>287 MB / 1347 MB</td></tr></table>

**Comment by rodmelia** [comment]
This probably means that we need to incorporate some OU/ Program filtering. This is for H15/H16

**Comment by cristinaelle** [comment]
Yes - Filters for both OUs and Surveys have been included in 1.3. Closing this.
