### ISSUE TITLE
Assess: Compulsory questions

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#5]
Feedback from clussiana@psi.org : Wondering why for the IMCI checklist when all the questions are answered, the tablet automatically asks if I want to send the assessment, while for the other checklists (HIV, etc.) the system takes me back to the landing page of the Assess module even if all the questions have been answered.
Can we make this process consistent with all the checklists, please? When all the questions of a checklist have been answered, the system should ask if the supervisor wants to send the assessment.

 [Link to buddybuild feedback from build 4](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56d06fa1ac6bbd0100be5466&bnum=4)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d057fac8f4aa010054eac5/7f3b8b54-6720-4d74-a277-ddae03a54727.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>58% Unplugged</td></tr><tr><td>Memory free</td><td>284 MB / 1376 MB</td></tr></table>

**Comment by ifoche** [comment]
The point here is that the only survey that has compulsory questions is ICM. That's the reason of that behaviour. Currently, the configured workflow when the user press exit is:
- If there are compulsory questions not filled in or there are not any compulsory questions in the survey, we don't propose to mark the survey as completed. 
- If all the compulsory questions are checked then we propose to mark the survey as complete

As it was a developing server, we didn't pay attention to having compulsory questions on every survey. However, I think that there's something here that we've missed to introduced, and it is putting a red asterisk in compulsory questions, to clearly identify them. I will add that task and close this one if you agree with the explanation.

BTW, the compulsory questions in ICM are those under the headers "Introduction" and "Inquiry", if you want to test it.

There's another thing related to this, and it's the way the completion percentage is calculated. Just in case it's not clear I explain it:
- If the survey doesn't have compulsory questions, it is calculated taking into account the not hidden questions.
- If the survey do have compulsory questions, it is calculated only taking into account the compulsory questions

**Comment by cristinaelle** [comment]
@gtrsmith: looping in Graham, too, into this conversation. 
I like the fact that if all the compulsory questions are answered, the tablet automatically marks the assessment as completed and proposes to send it. We should definitely apply this functionality to all the checklists. I'm wondering where these compulsory questions come from and why we have compulsory questions for the IMCI checklist, only. Can we make this consistent with all the assessments, please? I'm happy to work with Linda to identify compulsory questions for every checklist, it won't take too long. 
For analytics purpose, if we want to compare QoC scores over time, we have to calculate our QoC scores out of the compulsory questions, only, otherwise we risk that we are comparing QoC scores calculated out of different answers. 

@gtrsmith: happy to discuss this more by email if need be.

**Comment by ifoche** [comment]
Regarding the amount of compulsory questions, please just take into account that this is a development server. I selected the compulsory questions randomly, in a random Program without any criteria, just to check that we were able to do it and the interface was working. Of course, to use it in the production server, the metadata must be properly set in the server according the real compulsory questions. 

For the other point (QoC depending just on compulsory questions) it makes sense for me, but I leave @gtrsmith to answer what he thinks about it.

**Comment by ifoche** [comment]
Just to make sure, in this issue we're just waiting for @gtrsmith to answer about the metadata. I assume that is no longer an Android issue, but a DHIS issue, so I label it like that, and leave it there until @gtrsmith says his opinion

**Comment by rodmelia** [comment]
We probably need to think about how making the 'ready to submit' process more friendly. I have added a ticket for H15 #48

**Comment by gtrsmith** [comment]
@cristinaelle as soon as we identify compulsory questions, we can update all assessments. This is content related and something we can update directly in DHIS. Lets discuss.

**Comment by gtrsmith** [comment]
@cristinaelle, we can use the 'Notes' column in our google spreadsheet to indicate whether a question should be mandatory. Lets meet this week to discuss these and other edits you'd like to make to content.

**Comment by rodmelia** [comment]
@gtrsmith - perhaps this card can be moved to the 'Done?'
