### ISSUE TITLE
Assess: Text fields

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#50]
We need to test the functionality of open text fields. I am unable to enter text here but this may be related to DHIS settings rather than application functionality. 

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56d88e4c0c683f0100baf6d2&bnum=6)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d774842ebeba010067f8b1/ae6059fd-eafe-4480-9559-63fbb630c3d8.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T217S</td></tr><tr><td>Screen size</td><td>600</td></tr><tr><td>Screen size</td><td>600px by 1024px</td></tr><tr><td>Battery</td><td>34% Unplugged</td></tr><tr><td>Memory free</td><td>303 MB / 1347 MB</td></tr></table>

**Comment by ifoche** [comment]
This problem is limited for Android less than 5.0 and not cambodian mobile phones

**Comment by rodmelia** [comment]
Marking as a bug.
