### ISSUE TITLE
Assess: Khmer text - low priority

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#51]
This issue is a low priority but I am submitting ticket for documentation and follow up. Issue: I am unable to view Khmer form name in Assess module of HNQIS. Background: I created a test program to see if Khmer would render in the application if I used Khmer in the form name of a data element. The program is "_XX KH HNQIS Khmer Text Test" and the data element is "XX KH Text Test - This is a Khmer form name". The program will download and register in HNQIS but the form name appears blank - indicating it is unable to render Khmer text. 

Ignacio, can you just let me know here whether or not this behavior is expected? I thought the app would be able to download a Khmer form name into the assess module. You can see the program by logging into HNQIS as gdemoKH, password Temp1234.

Thank you

Graham

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56d89c666844e501002b4e75&bnum=6)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d774842ebeba010067f8b1/92a3ebb7-59e5-46fa-936a-245d82ea9492.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T217S</td></tr><tr><td>Screen size</td><td>600</td></tr><tr><td>Screen size</td><td>600px by 1024px</td></tr><tr><td>Battery</td><td>30% Unplugged</td></tr><tr><td>Memory free</td><td>452 MB / 1347 MB</td></tr></table>

**Comment by ifoche** [comment]
Hi @gtrsmith . The app is not for the moment prepared for Khmer (we need to include a special library for that). We haven't tried it yet as the languages for this app, for the moment were supposed to be French, Spanish, English and Portuguese. Maybe we can discuss next week about it?

**Comment by gtrsmith** [comment]
Thanks Ignacio - makes perfect sense. We can discuss next week.

**Comment by ifoche** [comment]
related to #50
