### ISSUE TITLE
The app keeps crashing when I click on these links. I guess…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#54]
Feedback from clussiana@psi.org : The app keeps crashing when I click on these links. I guess they're not actual links, right? There's no content related to these kinks? If so, the app crashes "often" in the Improve module.

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56dbaea119e6d30100f3423b&bnum=6)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d774842ebeba010067f8b1/1f6a99b9-275e-42e8-846b-75cd3693fc78.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>68% Unplugged</td></tr><tr><td>Memory free</td><td>442 MB / 1376 MB</td></tr></table>

**Comment by gtrsmith** [comment]
This is fixed. We need to figure out a better way to make the links public but they are clickable without the app crashing at this point.
