### ISSUE TITLE
buddybuild feedback from clussiana@psi.org on build #6: Drop down menus don't work.

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#55]
Feedback from clussiana@psi.org : Drop down menus don't work.

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56dbaf078b12920100d96a37&bnum=6)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d774842ebeba010067f8b1/e50c67ea-1ebe-4463-a6c2-7a50ac52a049.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>67% Unplugged</td></tr><tr><td>Memory free</td><td>395 MB / 1376 MB</td></tr></table>

**Comment by ifoche** [comment]
I can't replicate this, can you test it on the build 7 just to be sure?

**Comment by cristinaelle** [comment]
I was clicking on the arrows while I should have clicked on the headers. I'll delete this.
