### ISSUE TITLE
buddybuild feedback from clussiana@psi.org on build #6: Make the colors of these scores consistent with our coding…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#56]
Feedback from clussiana@psi.org : Make the colors of these scores consistent with our coding (red, yellow, green).

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56dbb371ba38dc0100fe770c&bnum=6)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d774842ebeba010067f8b1/46ff114e-9f55-4422-8656-3bf1976d8d1e.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>62% Unplugged</td></tr><tr><td>Memory free</td><td>323 MB / 1376 MB</td></tr></table>

**Comment by gtrsmith** [comment]
This looks good to me - the colors are as good as they are going to get (considering the background shading) without professional re-design.
