### ISSUE TITLE
buddybuild feedback from clussiana@psi.org on build #6: ?? Empty content for the Improve module of TB.

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#58]
Feedback from clussiana@psi.org : ?? Empty content for the Improve module of TB.

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56dbb41a19e6d30100f34245&bnum=6)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d774842ebeba010067f8b1/93ac82bc-d463-403c-a849-e80539934683.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>60% Unplugged</td></tr><tr><td>Memory free</td><td>303 MB / 1376 MB</td></tr></table>

**Comment by ifoche** [comment]
I think this is related to the metadata change that @josemp10 is doing in the server. @josemp10 can you confirm that this is now working?

**Comment by cristinaelle** [comment]
Yes, it works fine on #7, thanks.
