### ISSUE TITLE
buddybuild feedback from clussiana@psi.org on build #6: Drop down menu doesn't work.

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#61]
Feedback from clussiana@psi.org : Drop down menu doesn't work.

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56dbb5802f5f410100440e79&bnum=6)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d774842ebeba010067f8b1/fff71ecd-eb74-4afb-9bf0-b1bc61bab901.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>58% Unplugged</td></tr><tr><td>Memory free</td><td>287 MB / 1376 MB</td></tr></table>

**Comment by ifoche** [comment]
again, I'm not able to replicate it, can you re-test on build 7?

**Comment by cristinaelle** [comment]
Same as for the other one, I was clicking on the arrow instead of on the header.
