### ISSUE TITLE
Make the header font size and the font consistent with the…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#62]
Feedback from clussiana@psi.org : Make the header font size and the font consistent with the one used in the headers of the other 3 modules.

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56dc32c419e6d30100f3428c&bnum=6)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d774842ebeba010067f8b1/8dba7077-a74c-4966-bbde-2624a6b452c5.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>39% Unplugged</td></tr><tr><td>Memory free</td><td>496 MB / 1376 MB</td></tr></table>

**Comment by rodmelia** [comment]
@cristinaelle  & @gtrsmith  - I'm tagging this one for H16, because we need to make a full review of all font sized and colors. We may want to consider a UX specilist.
