### ISSUE TITLE
Drop down menus icon : people will click on the…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#63]
Feedback from clussiana@psi.org : Drop down menus are not clear: people will click on the arrow instead of on 'All assessments' and 'Org units'. Can we expand the "click area" to include the drop down menu buttons?

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56dc334dba38dc0100fe7764&bnum=6)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d774842ebeba010067f8b1/fee09221-e119-4c88-a0df-c7b06b919d6c.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>39% Unplugged</td></tr><tr><td>Memory free</td><td>442 MB / 1376 MB</td></tr></table>

**Comment by rodmelia** [comment]
related to #64
