### ISSUE TITLE
Drop down menu is not clear. People will click on the arrow…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#64]
Feedback from clussiana@psi.org : Drop down menu is not clear. People will click on the arrow instead of on 'All assessments". Please, exoand the "click area" to include the drop down menu button.

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56dc33dd5f9e3e0100539f56&bnum=6)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d774842ebeba010067f8b1/20f316df-2a63-4a2d-8f6a-2214ba7cf856.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>39% Unplugged</td></tr><tr><td>Memory free</td><td>430 MB / 1376 MB</td></tr></table>

**Comment by rodmelia** [comment]
see #63
