### ISSUE TITLE
Confirm the name of the OU - Survey being deleted

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#65]
Feedback from clussiana@psi.org : Something very weird happens in the landing page of the Assess module. It seems that regardless of the assessment I want to push, the tablet always pushes the first assessment, only, the one in the top. Try to upload some assessments and push the ladt or next to last obe. You'll see that the tablet won't push what you've chosen, but the first on top. 
If I then go to the Plan module, what I wanted to pysh is still there with the same date of future QA, while what the tablet to push (the first on top) has an updated date of future QA. 
Why this? And hiw the Monitor module is affected?

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56dc3554ba38dc0100fe7765&bnum=6)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d774842ebeba010067f8b1/40860523-f962-44e4-bfc8-d700d045eed5.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>36% Unplugged</td></tr><tr><td>Memory free</td><td>438 MB / 1376 MB</td></tr></table>

**Comment by ifoche** [comment]
@cristinaelle can you confirm that this bug report is not valid anymore? Can I close it?

**Comment by cristinaelle** [comment]
It has happened yesterday during the field test. I've submitted another one yesterday and I think you've linked what I submitted yesterday to this issue. Can you try to upload some empty assessments (5/6) from at least 2 HFs and randomly delete the ones listed in the middle? And see if the tablet deletes what you've selected, please?

**Comment by rodmelia** [comment]
@cristinaelle : I think that when you tested, you did on the tablets for "PLAN B", which contained Build 6. We are improving this by ensuring the user is prompted for a confirmation of the exact Survey/ OU to be deleted.

"Are you sure that you want to delete SURVERY NAME for OU NAME?

Delete Survey NAME   | Cancel: do not delete.

**Comment by rodmelia** [comment]
Repeated in #74

**Comment by gtrsmith** [comment]
I just tested in latest build and this is resolved
