### ISSUE TITLE
Assess, FP first page is extremely slow. Can this be speeded…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#67]
Feedback from clussiana@psi.org : Assess, FP first page is extrenely slow. Can this be speeded up a bit, please?

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56dc375d8b12920100d96abe&bnum=6)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d774842ebeba010067f8b1/7765595c-2a50-4c09-b087-7c214b6038aa.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>32% Unplugged</td></tr><tr><td>Memory free</td><td>441 MB / 1376 MB</td></tr></table>

**Comment by rodmelia** [comment]
Workarounds for H14:
- Increase shade intensity
- Stop receiving user input (no more tapping allowed)
- Show processing animated wheel.

**Comment by ifoche** [comment]
For the moment just changing background is done, a refactor of a part of the code is needed to implement the whole thing

**Comment by rodmelia** [comment]
Give us a couple of days to play with the new release and see if the 4 stages  for press/ not press/ selected/ not selected are sufficient. We will get back to you to see if it is necessary to continue the work on the 'animated wheel'

**Comment by rodmelia** [comment]
@gtrsmith and @cristinaelle 

Ignacio and I are assuming that you are ok with the current response time. So no actions for H14.

What about H15? anything that needs to be done here? or this now acceptable?

**Comment by cristinaelle** [comment]
This is acceptable now, for both H14 and H15 to me.
