### ISSUE TITLE
Rearrange a bit 'Return to all assessments", at the moment…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#68]
Feedback from clussiana@psi.org : Rearrange a bit 'Return to all assessments", at the moment it overlaps with the blue arrow.

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56dc37a719e6d30100f34293&bnum=6)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d774842ebeba010067f8b1/47b15bec-a01d-4952-a74e-69bde3bf0943.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>32% Unplugged</td></tr><tr><td>Memory free</td><td>397 MB / 1376 MB</td></tr></table>

**Comment by gtrsmith** [comment]
This is resolved
