### ISSUE TITLE
Improve: For some checklists, in the feedback page, the tablet…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#69]
Feedback from clussiana@psi.org : For some checklists, in the feedback page, the tablet reports 1/0 instead if Yes/No. I've noticed this for Post paryum IUD, Labour and delivery and Newborn resuscitation.

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56dc38d719e6d30100f34294&bnum=6)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d774842ebeba010067f8b1/65f396bb-5b28-4ab1-97dc-7a2f3d561f7d.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>29% Unplugged</td></tr><tr><td>Memory free</td><td>453 MB / 1376 MB</td></tr></table>

**Comment by ifoche** [comment]
@josemp10 can you confirm it is not a server side problem?

**Comment by cristinaelle** [comment]
It's still there in #7. For some checklists, there's the list of Yes/No answer, while for others there's the list of 0/1. I'd go for Yes/No if it's possible.

**Comment by rodmelia** [comment]
Cristine - I'm going to close this one. If this is really happening in build 7, please open a new waffle. Ignacio suggest for you to delete the app, before installing build 7.
