### ISSUE TITLE
Monitoring: assessment selector - can the selector be bigger? 

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#7]
Feedback from clussiana@psi.org : Make the arrow of the drop-down menu MUCH MUCH bigger.

 [Link to buddybuild feedback from build 4](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56d0706704d0c60100678552&bnum=4)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d057fac8f4aa010054eac5/6b60aede-ee40-4747-9755-0dfe9752ceb8.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>57% Unplugged</td></tr><tr><td>Memory free</td><td>236 MB / 1376 MB</td></tr></table>

**Comment by ifoche** [comment]
@cristinaelle In fact what is clickable is not the arrow itself, but the whole line (the dropdown). The arrow is there just to make the user know that there's a dropdown. Do you find it counter-intuitive? If we make the arrow bigger we would be making the whole black background bigger. Is that the behaviour you would be expecting? Do you think that the "All Assessment" font must be bigger too? (Remember that if you're seeing the app in a very wide-screen tablet, you have to think also in how it will render in small ones)

**Comment by cristinaelle** [comment]
You're right, I've checked this on regular-size tablets and it looks much better. Can we put all the line in bold, please? "All assessments" and the arrow? What do you think?

**Comment by ifoche** [comment]
Yes, I think that it would be very good to have all the "ALL ASSESSMENTS" filters with the same appearance

**Comment by rodmelia** [comment]
Yes - it is very important that the assessment selector is the same size across the whole application.
