### ISSUE TITLE
Monitoring: What's the sorting order of the facilities? Shouldn't it be…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#70]
Feedback from clussiana@psi.org : What's the sorting order of the facilities? Shouldn't it be alphabetical to facilitate supervisor's research?

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56dc39368b12920100d96abf&bnum=6)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d774842ebeba010067f8b1/bc766235-0433-48c2-b0f7-876945e1fddd.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>27% Unplugged</td></tr><tr><td>Memory free</td><td>432 MB / 1376 MB</td></tr></table>

**Comment by rodmelia** [comment]
I'm marking this as invalid. We developed a new concept for OU-based analysis that will make it in H15/H16
