### ISSUE TITLE
Please, rearrange the labels of each range in the doughnut…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#71]
Feedback from clussiana@psi.org : Please, rearrange the labels of each range in the doughnut so that they don't overlap with each other. At the moment if a range is not large enough, the label of the previous range overlaps.

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56dc3a3dba38dc0100fe7768&bnum=6)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d774842ebeba010067f8b1/2179c0af-36ef-450b-9516-c2884208d3be.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>26% Unplugged</td></tr><tr><td>Memory free</td><td>426 MB / 1376 MB</td></tr></table>

**Comment by ifoche** [comment]
This is something more complicated than it may appear. That label is being shown by the library we're using (chart.js) to represent the charts. Should we consider this even knowing that it may be a complicated task?

**Comment by cristinaelle** [comment]
Ok, maybe disregard this. Hopefully this is relevant to the first weeks of use of the app, only. With time, the size of each portion will increase and we won't see this anymore.

**Comment by rodmelia** [comment]
As explained by Igancio, we cannot control this. Marking as invalid.
