### ISSUE TITLE
Header: reduce font size or abbreviate the header of this…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#72]
Feedback from clussiana@psi.org : Header: reduce font size or abbreviate the header of this checklist for the Monitor module. It hides the blue arrow.

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56dc3a7e5f9e3e0100539f57&bnum=6)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d774842ebeba010067f8b1/058b3e2a-52c6-4e6f-a041-78b71dc2404e.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>24% Unplugged</td></tr><tr><td>Memory free</td><td>419 MB / 1376 MB</td></tr></table>

**Comment by rodmelia** [comment]
@cristinaelle - we should think about making shorter the name of the surveys.
I'm marking this as invalid, and we will review later with the Graphic designer/ UX expert.
