### ISSUE TITLE
The doughnut and the table don't automatically upload…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#73]
Feedback from clussiana@psi.org : The doughnut and the table don't automatically upload offline. I've marked as completed an assessment on C. Cancer with 100% score, but it's not reflected here, while it should. I've tried with other assessments, too, and it's the same.

I've now noticed that even if it's online, the table and the doughnut don't upload automatically.

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56dc3bae8b12920100d96ac2&bnum=6)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d774842ebeba010067f8b1/792e53ec-bc9a-48fa-b376-6d2e77eee908.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>22% Unplugged</td></tr><tr><td>Memory free</td><td>407 MB / 1376 MB</td></tr></table>

**Comment by rodmelia** [comment]
This is related to the problems that we have with the dates (# ). As soon as that gets addressed, everything will show again in the right place. Marking as invalid.
