### ISSUE TITLE
I've deleted all the assessments that were listed in the…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#75]
Feedback from clussiana@psi.org : I've deleted all the assessments that were listed in the Assess module, undertaken a C. Cancer assessment with 100% score and pushed it (it was the only one listed). I went to the Monitor module and I can now see the doughnut and the table correctly uploaded.
The mismatch between what you want to push/delete and what the tablet actually pushes/deletes in case there's more than 1 assessment listed in the Assess module, explains why before I couldn't find the last assessments I pushed in the Monitor module. I've interpretated this as a lack of automatic upload of the Monitor module, but actually it's not. It has to do with the mismatch in the Assess module.

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56dc3fa65f9e3e0100539f5a&bnum=6)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d774842ebeba010067f8b1/6fdcb1cd-9b83-403f-9ba3-141a47cf197c.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>15% Unplugged</td></tr><tr><td>Memory free</td><td>341 MB / 1376 MB</td></tr></table>

**Comment by rodmelia** [comment]
This issue is related to the dates - Please wait until the date issue is solved, and then this will work again.
