### ISSUE TITLE
Improve: Increase spacing on landing page

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#76]
Feedback from clussiana@psi.org : Increase the font size of each row and the space in between each row.

 [Link to buddybuild feedback from build 7](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56dcf636c49f9f010026fb16&bnum=7)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56dcb154a87a4201000f2f61/1852cceb-de10-4015-b7c0-2a27f441ad2e.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>7</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>100% Full</td></tr><tr><td>Memory free</td><td>231 MB / 1376 MB</td></tr></table>

**Comment by gtrsmith** [comment]
low priority, but the spacing here is still too narrow. Users need to click on an individual assessment. Spacing should be increased slightly.

**Comment by rodmelia** [comment]
I think this is repeater, but I cannot find the other card. Yes, the spacing between rows needs to increase, as it has been done in all other listings.

**Comment by gtrsmith** [comment]
Beautiful
