### ISSUE TITLE
To discuss with RM and GS. Do we want to include the "All…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#77]
Feedback from clussiana@psi.org : To discuss with RM and GS. Do we want to include the "All org units" option, too?

 [Link to buddybuild feedback from build 7](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56dcf68c3f2d4801007bc905&bnum=7)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56dcb154a87a4201000f2f61/9d776161-20b1-4439-8033-e7b78e0f3478.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>7</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>100% Full</td></tr><tr><td>Memory free</td><td>222 MB / 1376 MB</td></tr></table>

**Comment by rodmelia** [comment]
outdated discussion. v1.3 has new filters that address this issue
