### ISSUE TITLE
Assess: If I have more than 1 assessment, now the tablet correctly…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#79]
Feedback from clussiana@psi.org : If I have more than 1 assessment, now the tablet correctly pushes the one thst I select, thanks for fixing this.
But if I have more than 1 assessment and want to delete 1, the tablet keeps deleting the last one of the list instead of the one I've selected.

 [Link to buddybuild feedback from build 7](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56dcf73f3f2d4801007bc907&bnum=7)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56dcb154a87a4201000f2f61/2771924e-f6a7-4276-bfc6-1fdb3279d09f.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>7</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>100% Full</td></tr><tr><td>Memory free</td><td>214 MB / 1376 MB</td></tr></table>

**Comment by gtrsmith** [comment]
This is resolved
