### ISSUE TITLE
Previous - Next buttons on multi-tab assessment (beginning and end)

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#8]
Feedback from clussiana@psi.org : The back and forward arrows don't work well.
The back and forward arrows at the beginning/end of the whole assessment are useless. Can we remove them?

 [Link to buddybuild feedback from build 4](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56d072862149f40100ed8db5&bnum=4)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d057fac8f4aa010054eac5/6281bbf8-4bdc-4ad0-9c52-660502d6e3c4.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>54% Unplugged</td></tr><tr><td>Memory free</td><td>240 MB / 1376 MB</td></tr></table>

**Comment by ifoche** [comment]
would you find appropriate instead of removing the arrow, just putting it darker, disabling it, or you think it is better to simply remove it?

**Comment by cristinaelle** [comment]
If it's too complicated to remove them, what if we color them with the same color of the background? Dark grey?

**Comment by ifoche** [comment]
@cristinaelle , it is not very complicated to remove it, I was just worried about the problems in the alignment that may cause  the disappearance of one element in a 3 columns layout (left arrow | tab name | right arrow). We're on it, and we've found a workaround

**Comment by rodmelia** [comment]
As long as the arrows show on multi-tab assessments, Graham and I are ok with removing/ hiding/ coloring them light at the end/ beginning of a multi-tab assessment.

**Comment by gtrsmith** [comment]
Thanks - looks good
