### ISSUE TITLE
Headers of sections and subsections shouldn't have any…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#80]
Feedback from clussiana@psi.org : Headers of sections and subsections shouldn't have any feedback associated. And please, highlight these in bold, tks!

 [Link to buddybuild feedback from build 7](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56dd727f6d745e01004ff146&bnum=7)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56dcb154a87a4201000f2f61/bead8fff-bcaa-428c-9158-4358893600a3.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>7</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>47% Unplugged</td></tr><tr><td>Memory free</td><td>147 MB / 1376 MB</td></tr></table>

**Comment by rodmelia** [comment]
1. Against the principle of no more font changes, let's set labels BOLD.
2. If feedback = null then disable the expand feature for the feedback text.

**Comment by gtrsmith** [comment]
This is resolved
