### ISSUE TITLE
The section on Injectables is missing. It skips from section…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#81]
Feedback from clussiana@psi.org : The section on Injectables is missing. It skips from section 1.2 to 1.5.

 [Link to buddybuild feedback from build 7](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56dd74c66d745e01004ff152&bnum=7)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56dcb154a87a4201000f2f61/b0e2c8ce-1571-4392-bfd6-745b4fa17fe5.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>7</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>43% Unplugged</td></tr><tr><td>Memory free</td><td>179 MB / 1376 MB</td></tr></table>

**Comment by rodmelia** [comment]
The issue is metadata - Jose is working on fixing this.
