### ISSUE TITLE
Include a completeness score at the top of the assessment,…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#82]
Feedback from clussiana@psi.org : Include a completeness score at the top of the assessment, so that the supervisor knows when she can leave the Asssess module and move to Improve. At the moment she gad to scroll up and down to look for missing questions and vrtify that everything has been filled in.

 [Link to buddybuild feedback from build 7](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56dd773fe1ae9d0100644ba5&bnum=7)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56dcb154a87a4201000f2f61/cc91e66f-572a-4bfd-8593-4e1dff53f459.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>7</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>40% Unplugged</td></tr><tr><td>Memory free</td><td>189 MB / 1376 MB</td></tr></table>

**Comment by rodmelia** [comment]
This is being implemented in v1.3 as the completion wheel
