### ISSUE TITLE
Delete: Again :) I wanted to delete an assessment and another one…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#83]
Feedback from clussiana@psi.org : Again :) I wanted to delete an assessment and another one has been deleted! This bug is still there!

 [Link to buddybuild feedback from build 7](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56dd782ec461ba0100a70612&bnum=7)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56dcb154a87a4201000f2f61/e1e348f3-87e8-472e-a297-a0a0dc0d3539.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>7</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>38% Unplugged</td></tr><tr><td>Memory free</td><td>164 MB / 1376 MB</td></tr></table>

**Comment by rodmelia** [comment]
repeated (see #79) - please do not submit more than one ticket per issue/ build.
