### ISSUE TITLE
Include a Complete button in case the supervisor wants to…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#84]
Feedback from clussiana@psi.org : Include a Complete button in case the supervisor wants to move to Improve.
Include an Incomplete and Go back button in case the supervisor wants to go back to the landing page of Assess. Or leave this to the backward arrow.
(from Sarah)

 [Link to buddybuild feedback from build 7](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56dd7935c461ba0100a70616&bnum=7)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56dcb154a87a4201000f2f61/23d7d603-5ff8-4420-a306-dbeddf1f4a96.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>7</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>37% Unplugged</td></tr><tr><td>Memory free</td><td>156 MB / 1376 MB</td></tr></table>

**Comment by cristinaelle** [comment]
This has been fixed - Thanks, closing.
