### ISSUE TITLE
When a survey is marked as completed, there should be a button "Go to feedback" in the alert that tells you that the survey has been moved to improve tab

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#89]

**Comment by ifoche** [comment]
The button would take you directly to the feedback of that survey

**Comment by gtrsmith** [comment]
I got an error message after I clicked 'go to feedback'. The error message did not seem to cause any conflicts though. The app still took me to the feedback section and I was able to simply close the message. See image:

![improve error](https://cloud.githubusercontent.com/assets/14224713/14111028/4bedda24-f586-11e5-915d-2ccbd25d95c9.png)

**Comment by ifoche** [comment]
@gtrsmith Just to clarify how the conflicts treatment is, to be sure that we're really looking to a bug. The push is happening in background, we may be sending several surveys at a time and in principle that conflict message is not necessarily related to the survey you've just sent (it can be produced by another survey). The message need to be changed however, as the import summary is not being shown by the app, I think we should say "please look at the improve tab to review the conflicting surveys" or something like that. The point is that if you go to the improve tab you should be able to  see "CONFLICT" in those surveys that have received a conflict from the server. If you enter that feedback, you should even be able to see which dataElements have produced the conflict in the server, and which have been imported without problems by the server. This situations usually comes when something change server side and the app has not refreshed its metadata. Can you confirm that you can see this conflicting survey and even see which dataElement(s) is(are) conflicting?

**Comment by gtrsmith** [comment]
oh i see - so this is due to conflicting metadata and an out of sync application. Yes, this could be confusing but perhaps something for H15. I refreshed my metadata already so I dont see the conflicts anymore and am unable to check. 

Not sure how to proceed. A simple change to the prompt for now might suffice. Do you consider the improve landing page the 'import summary'?

Graham

**Comment by ifoche** [comment]
Sorry for not answering before. I think that we can easily change the message for H14 saying "please look at the improve tab to review the conflicting surveys". The import summary is an object that we're receiving with the summary of which DEs have been imported and which haven't, after a push. So yes, there's one thing here that we definitely need to change, and it's the message prompted to the user (as the user doesn't know anything about the import summary). Apart from that, of course, if you feel that we need to change anything else in the treatment of the conflicts, it can be done, but then I would suggest H15 for those possible changes.

**Comment by rodmelia** [comment]
@gtrsmith @cristinaelle  - so let's go ahead with an updated prompt to the user, and we will address this properly in H15/16. Graham/ Cristina - can you confirm that the text below makes sense.

"There were conflicts in the survey push. The survey may have changed on the server side. Please inform your administrator about the the conflict questions by reviewing the feedback"

**Comment by cristinaelle** [comment]
I'd really like to leave supervisors out of this issue. By leaving them out I mean that we should avoid that they get a conflict message. Now if it's possible (H14) and in the future (H15). There's no action from their side, they won't do anything different in terms of Assess or Improve, so why we want them to get the conflict message?

Furthermore,"Please inform your administrator about the conflict questions by reviewing the feedback" means that they have to look for all the assessments they have sent in the Improve module and see which ones have conflict questions. 

Is there a way to prevent supervisors to get the conflict message (H14) and is there a way to prevent supervisors from updating their app if they have unsent surveys sitting on the tablet (H15)?
