### ISSUE TITLE
Assess: Complete message

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#90]
Feedback from clussiana@psi.org : When I mark a survey as completed, is it possible to report the name of the facility, too, in the box? 'The survey KE HNQIS FP for facility 1 has been marked as completed nd you can now...'.

 [Link to buddybuild feedback from build 8](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56e244cf3f17a60100cb897f&bnum=8)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56e22b6c092aa501008fc947/95981c82-a22e-4657-9f6d-86dc1b7f6de3.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>8</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>44% Unplugged</td></tr><tr><td>Memory free</td><td>212 MB / 1376 MB</td></tr></table>

**Comment by rodmelia** [comment]
Closing old issue
