### ISSUE TITLE
Monitor: Assessment display

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#91]
Feedback from clussiana@psi.org : I'm marking surveys as completed and they're not appearing in the Monitor module. March is empty and this happens with different checklists.

 [Link to buddybuild feedback from build 8](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56e247113f17a60100cb8983&bnum=8)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56e22b6c092aa501008fc947/7a32d15a-5c7d-41b9-a18c-6855baafa8e7.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>8</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>41% Unplugged</td></tr><tr><td>Memory free</td><td>220 MB / 1376 MB</td></tr></table>

**Comment by gtrsmith** [comment]
This has since been resolved
