### ISSUE TITLE
Monitoring Section seems to include the 'never assess' surveys

### ISSUE THREAD

**Issue by rodmelia** [EyeSeeTea/QAApp#93]
'assessments conducted' should be based on the total number of assessments conducted. It should include those cases with multiple assessment for a OU-Program, but exclude the 'never assess' - they have not yet been conducted. 

I think the current month is normally overstated because it includes the 'never assessed' ones.

**Comment by gtrsmith** [comment]
Monitoring section now only includes completed assessments
