### ISSUE TITLE
Settings: Default URL

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#94]
Feedback from gtsmith@psi.org : Daniel requested that we remove this default url when we post to Google play. I think the default text here can just be https://

 [Link to buddybuild feedback from build 9](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56f0d8e653fdf00100d385ad&bnum=9)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56e541525dc2880100ebb185/c0c3d64f-3b40-4d99-9f7b-31c62bb36403.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>9</td></tr><tr><td>Device type</td><td>SM-T217S</td></tr><tr><td>Screen size</td><td>600</td></tr><tr><td>Screen size</td><td>600px by 1024px</td></tr><tr><td>Battery</td><td>93% Unplugged</td></tr><tr><td>Memory free</td><td>175 MB / 1347 MB</td></tr></table>

**Comment by rodmelia** [comment]
Makes sense

**Comment by gtrsmith** [comment]
I'd like to keep the " https:// " text in the default. This way we are reducing error as much as possible.
