### ISSUE TITLE
About section : please update with text in comment

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#95]
Feedback from gtsmith@psi.org : Please update the about section with text found in this google doc:

https://docs.google.com/document/d/1DCLRycl5kGfnJ8nR-N9LSogQvyoaw5Mk2egDfJ4q7EI/edit

It should include the PSI logo and the version number

 [Link to buddybuild feedback from build 9](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56f0e0d9aaaa2d010053f287&bnum=9)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56e541525dc2880100ebb185/d9abe57c-68b3-4e5c-b89c-ba4f0c18fe62.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>9</td></tr><tr><td>Device type</td><td>SM-T217S</td></tr><tr><td>Screen size</td><td>600</td></tr><tr><td>Screen size</td><td>600px by 1024px</td></tr><tr><td>Battery</td><td>91% Unplugged</td></tr><tr><td>Memory free</td><td>168 MB / 1347 MB</td></tr></table>

**Comment by rodmelia** [comment]
Marked as low complexity.
@gtrsmith : I think the text is still the old one.  Also the logo is still missing.
Ignacio: Please wait fro Graham to confirm.

**Comment by rodmelia** [comment]
I just spoke to Graham - he needs to provide new language. So please wait for him to update the google doc.

**Comment by gtrsmith** [comment]
Cristina updated the language and it looks great. The google sheet has the most updated language. Please refresh about section with updated language in this document as of this message

https://docs.google.com/document/d/1DCLRycl5kGfnJ8nR-N9LSogQvyoaw5Mk2egDfJ4q7EI/edit

**Comment by gtrsmith** [comment]
done
