### ISSUE TITLE
Improve: Size of QoC score

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#96]
Feedback from gtsmith@psi.org : Increase size of score

 [Link to buddybuild feedback from build 9](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56f0e78016bc080100578456&bnum=9)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56e541525dc2880100ebb185/df3b63fe-e5df-4a0d-8868-bd2d1d004250.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>9</td></tr><tr><td>Device type</td><td>SM-T217S</td></tr><tr><td>Screen size</td><td>600</td></tr><tr><td>Screen size</td><td>600px by 1024px</td></tr><tr><td>Battery</td><td>87% Unplugged</td></tr><tr><td>Memory free</td><td>169 MB / 1347 MB</td></tr></table>

**Comment by rodmelia** [comment]
We are trying to minimize changes to design, and I'm trying to say NO to all of them. But this one needs to be fixed and it will be a lost opportunity to wait for the next round: Please increase significantly, probably using the same font as the text to the left of it, as well as BOLD

**Comment by gtrsmith** [comment]
Done - thanks for resolving
