### ISSUE TITLE
Improve: Scores below 50 should be red

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#97]
Feedback from gtsmith@psi.org : Scores below 50 should be red in line with our color scheme throughout

 [Link to buddybuild feedback from build 9](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56f0e7bb92912c0100dbcd8f&bnum=9)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56e541525dc2880100ebb185/a16246a9-2ee2-4367-9d35-3c2f81e481f3.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>9</td></tr><tr><td>Device type</td><td>SM-T217S</td></tr><tr><td>Screen size</td><td>600</td></tr><tr><td>Screen size</td><td>600px by 1024px</td></tr><tr><td>Battery</td><td>87% Unplugged</td></tr><tr><td>Memory free</td><td>171 MB / 1347 MB</td></tr></table>

**Comment by gtrsmith** [comment]
thanks for fixing
